#!/bin/csh -f
#
# Sets up the GNAAC EPICS UAE application directory after unpacking.
#
# Invocation:
#   ./gnaacSetup
#
# Steven M Beard
# 14 Mar 1997: CICS version.
# 27 May 1997: NIRI version.
# 17 Jun 1997: GNAAC version
#

# Check the EPICS startup script has been executed.

if ( ${?EPICS} == 0 ) then

   echo "EPICS environment variables have not been defined. Please execute" 
   echo "your local EPICS setup script (see 'gnaacLogin' for an example)."
   exit
endif

# Check that the GNAAC environment variables have been set up. This should have
# been done by executing a locally modified version of the "gnaacLogin" script.

if ( ${?GNAAC_DIR} == 0 ) then

   echo "GNAAC environment variables have not been defined. Please execute" 
   echo "your local version of the 'gnaacLogin' script to define these."
   exit
endif

echo "     Top level GNAAC directory = $GNAAC_DIR"
echo "                 GNAAC targets = $GNAAC_TARGET1, $GNAAC_TARGET2"


# Check the appropriate Gemini library directories have been defined.
# If they are not present set up GNAAC without them (which may
# result in some components failing to build).

# *** NEED TO INCLUDE A CHECK ON ASTLIB_DIR HERE AS WELL ***

if ( ${?DRAMA_DIR} && ${?DHS_DIR} && ${?SLALIB_DIR} &&  ${?TIMELIB_DIR} ) then

   applSetup -install ${GNAAC_DIR} -targets ${GNAAC_TARGET1} -targets ${GNAAC_TARGET2} -I ascii -I dl -I capfast -I src -I startup -depends ${DRAMA_DIR} -depends ${DHS_DIR} -depends ${SLALIB_DIR} -depends ${TIMELIB_DIR} -subdir_file Makefile.subdirs
else

   applSetup  -install ${GNAAC_DIR} -targets ${GNAAC_TARGET1} -targets ${GNAAC_TARGET1} -I ascii -I dl -I capfast -I src -I startup -subdir_file Makefile.subdirs

   echo "***"
   echo "*** WARNING: Gemini DHS, SLALIB and TIMELIB library environment"
   echo "*** variables not defined. GNAAC has been set up without them."
   echo "***"
endif




