#!/usr/bin/csh -f
#
# An example script for setting up EPICS and all the environment variables
# needed by the Gemini NOAO Advanced Array Controller (GNAAC).
#
# NOTE: THIS SCRIPT IS SPECIFIC TO IGPO. IT WILL NEED TO BE EDITED
# FOR YOUR OWN SITE.
#
# Steven M Beard
# 29 Jan 1997: CICS version.
# 27 May 1997: NIRI version.
# 17 Jun 1997: GNAAC version
#

# If EPICS has not already been set up, execute the Gemini EPICS startup
# script if it exists.

if ( ${?EPICS} == 0 ) then

# EDIT THE FOLLOWING FOR THE LOCATION OF EPICS AT YOUR OWN SITE.

    if ( -e ${HOME}/epics.csh ) then  

        source ${HOME}/epics.csh

    else

        echo "*** EPICS startup script not found."
        exit
    endif
endif

# If they have not already been set up, set up environment variables for
# the location of Gemini libraries if they exist.

if ( ${?GEMINI_LIB} == 0 ) then

# EDIT THE FOLLOWING FOR THE LOCATION OF THE GEMINI LIBRARIES AT YOUR OWN SITE.

    if ( -e /net/icarus/scr3/prototypes  ) then

        setenv GEMINI_LIB  /net/icarus/scr3/prototypes
        setenv SLALIB_DIR  ${GEMINI_LIB}/tcs2/slalib
        setenv TIMELIB_DIR ${GEMINI_LIB}/tcs2/timelib
        setenv DHS_DIR     ${GEMINI_LIB}/dhs/dhs0.6/rel
        setenv DRAMA_DIR   ${GEMINI_LIB}/drama/imp1.3/rel
    else

        echo "*** Gemini library directories not found."
    endif
endif

# Define the environment variables required by GNAAC.

# EDIT THE FOLLOWING FOR THE LOCATION OF THE GNAAC SOFTWARE AT YOUR OWN SITE.

setenv GNAAC_DIR	${HOME}/cics/gnaac
setenv GNAAC_TARGET1	mv167
setenv GNAAC_TARGET2	hkbaja47

# Add the necessary GNAAC directories to your PATH

setenv PATH ${PATH}:${GNAAC_DIR}:${GNAAC_DIR}/bin/solaris
