#! /bin/sh

#########################################################################
# Script for starting the stand-alone Wavefront Sensor control
# screens for the Near Infra-Red Imager.  (Derived from the
# Steven Beard's CICS startup scripts, by Hubert Yamada.)
#########################################################################

#########################################################################
# History:
#
# Original script written by Steven Beard, Based on the corresponding
# CICS script.
#
# Rewritten for NIRI and converted to use the Bourne Shell, by Hubert
# Yamada.
#
# $Log: niriWfsStart,v $
# Revision 1.2  2009/05/27 19:35:10  fkraemer
# fkraemer - copied my complete working dir over trunk
#
# Revision 1.3  1999/11/13 06:35:15  yamada
# Release 1.00 alpha 06.
#
# Revision 1.2  1999/11/12 08:13:25  yamada
# Got rid of the NN macro.  Now all screens get their titles from the
# database.  Also, modified the names of the ENG database to be consistent
# with the rest of the system.
#
# Revision 1.1  1999/11/10 21:11:31  yamada
# Rewrote configuration files to be more uniform.  Moved common startup
# files from the IS directory into the root directory.  Separated the
# shared components from the WFS screen into a separate screen.
#
#########################################################################

#########################################################################
# Configuration parameters
#########################################################################

dm=dm2.4

#########################################################################
# Check that the EPICS startup file has been sourced.
#########################################################################

if [ "${EPICS}" = "" ]; then
	echo 'EPICS environment variables have not been defined. Please source'
	echo 'your local EPICS setup script.  (The EPICS startup script is'
	echo 'normally sourced by "niriLogin".)'
	exit
fi

if [ "${NIRI_WFSDIR}" = "" ]; then
	echo 'NIRI WFS environment variables have not been defined. Please source'
	echo 'your local EPICS setup script, e.g., "niriLogin".'
	exit
fi

#########################################################################
# If a search path for the display screens has already been defined,
# Add the current directory and "data" subdirectories in front of
# the search path for display screens, creating a path if necessary.
#########################################################################

if [ "${EPICS_DISPLAY_PATH}" = "" ]; then
	EPICS_DISPLAY_PATH=${NIRI_ENGDIR}/data
else
	EPICS_DISPLAY_PATH=${NIRI_ENGDIR}/data:${EPICS_DISPLAY_PATH}
fi
EPICS_DISPLAY_PATH=${NIRI_LIBDIR}/data:${EPICS_DISPLAY_PATH}
EPICS_DISPLAY_PATH=${NIRI_WFSDIR}/data:${EPICS_DISPLAY_PATH}
EPICS_DISPLAY_PATH=.:${EPICS_DISPLAY_PATH}
export EPICS_DISPLAY_PATH

#########################################################################
# Finally, start the display screens in the background. The macros T,
# S, and C define the prefixes used for the EPICS record names.  The
# macro NN defines the overall system name.
#########################################################################

echo "Starting NIRI Components Controller screens..."
$dm niriWfs.dl "T=$NIRI_PREFIX, S=$NIRI_SADPREFIX, C=wfs:" &
