#! /bin/sh
#
# Sets up the NIRS LIB EPICS UAE application directory after unpacking.
#
# Invocation:
#   source nirsSetup
#
# Steven M Beard, Hubert Yamada
# 17 Mar 1997: CICS version.
# 27 May 1997: NIRS version.
#

#######################################################################
# Start with a few sanity checks.
#######################################################################

#
# Check that the EPICS startup script has been executed.
#

if [ ${EPICS-undefined} = undefined ]; then
	echo "*** EPICS environment variables have not been defined. Please"
	echo "*** source your local EPICS setup script (see \"nirsLogin\""
	echo "for an example)."
	exit 1
fi

#
# Check that the local login script has been executed.
#

if [ ${NIRS_LIBDIR-undefined} = undefined ]; then
	echo "*** ERROR: NIRS_LIBDIR environment variable not defined."
	echo "*** Please set up NIRS from the top level 'nirsSetup' script."
	exit 1
fi

#######################################################################
# Now set up the application directory.
#######################################################################

cd ${NIRS_LIBDIR}

#
# If this file already exists, then it is not overwritten.  Remove it,
# to be safe.
#

if [ -f config/CONFIG.Defs ]; then
	echo "* Removing old CONFIG.Defs"
	rm -f config/CONFIG.Defs
fi

applSetup -install ${NIRS_LIBDIR} -targets ${NIRS_TARGETS} \
	-subdir_file Makefile.subdirs \
	-I dl -I capfast -I src \
	-depends ${NIRS_ENGDIR} -depends ${NIRS_ASTLIBDIR} \
	-depends ${NIRS_SLALIBDIR} -depends ${NIRS_TIMELIBDIR}

exit $?
