#! /bin/csh -f
#
# gmEditFileField
#
# Description:
#   Edit the specified GMOS text file (e.g. lookup table) where
#   the directory and name of the file are obtained from a EPICS
#   fields. If there are problems reading the contents of an
#   EPICS field it will be assumed the string provided contains
#   the directory or file name itself.
#
# Invocation:
#   gmEditFileField EPICS-fieldname-dir EPICS-fieldname-fil
#

#
# Check the EPICS field name has been specified
#
if ($1 == "") then
  echo "Usage : gmEditFileField dirfieldname namefieldname"
  echo "Where dirfieldname contains the directory name:"
  echo "Where namefieldname contains the file name:"
  exit 1
endif

#
# Get the directory name from the specified EPICS field
#
set dirname = `caget -t $1`
if ($dirname == "") then
  set dirname = $1
endif

#
# Get the file name from the specified EPICS field
#
set filename = `caget -t $2`
if ($filename == "") then
  set filename = $2
endif

#
# Use the defined GMOS editor to edit the specified text file.
#
if (${?IS_EDITOR}) then
    echo "Editing "${dirname}/${filename}" with "$GMOS_EDITOR
    $IS_EDITOR ${dirname}/${filename} &
else
    echo "No IS_EDITOR variable found - Editing "${dirname}/${filename}" with emacs"
    xemacs ${dirname}/${filename} &
endif
