#! /bin/csh -f
#
# gmEditFile
#
# Description:
#   Edit the specified GMOS text file (e.g. lookup table)
#
# Invocation:
#   gmEditFile filename
#
#
# Check the file name has been specified.
#
if ($1 == "") then
  echo "Usage : gmEditFile filename"
  exit 1
endif
#
#
# Use the defined GMOS editor to edit the specified text file.
#
if (${?GMOS_EDITOR}) then
    echo "Editing "$1" with "$GMOS_EDITOR
    $GMOS_EDITOR $1 &
else
    echo "No GMOS_EDITOR variable found - Editing "$1" with emacs"
    emacs $1 &
endif
