#!/bin/csh -f
setenv PATH ${PATH}:./rel/bin/solaris:./gmosdc/bin/solaris
setenv EPICS_DISPLAY_PATH .:./data:./rel/data:./gmosdc/data
dm2.4 -iconic gmosTop.dl "T=g7:, S=g7:, C1=cc:, C2=cc:, CC=cc:, DC=dc:" &
