#! /bin/csh -f
#
# gmSeqDoCommand
#
# Description:
#   Execute a command by marking its CAD records and sending
#   a START directive to the apply record. This is a useful
#   script to execute from a "dm" screen to allow a command
#   to be invoked by a single button.
#
# Invocation:
#   gmSeqDoCommand cad <a b c d e f>
#
# Assumptions:
#   It is assumed the cad record name starts with a standard instrument
#   sequencer prefix that includes one colon, such as gm:init

#
# Remove unwanted output from caput
#

alias caput "caput -ts"

#
# Check the correct arguments have been specified.
#
if ($1 == "") then
  echo "Usage : gmSeqDoCommand cadname <p1 p2 p3 p4 p5 p6>"
  echo "Where cadname includes prefix:"
  exit 1
endif

#
# Extract the EPICS prefix from the CAD name, assuming it is delimited by a colon.
#

set EPICS_PREFIX = `echo $1 | cut -d\: -f1`:
set CAD          = `echo $1 | cut -d\: -f2`
if ($EPICS_PREFIX == ":") then
  echo "Illegal record prefix specified" $1
  exit 1
endif

#
# First send a CLEAR directive to make sure commands that are marked
# unexpectedly do not execute in preference to the one requested.
#

set response = `caput ${EPICS_PREFIX}apply.DIR CLEAR`

#
# Mark the CAD record and set any attributes that may have been specified.
# Use the "set response" trick to throw away output from caput.
#

set response = `caput ${EPICS_PREFIX}${CAD}.DIR MARK`
if ($2 != "") then
  set response = `caput ${EPICS_PREFIX}${CAD}.A $2`
endif
if ($3 != "") then
  set response = `caput ${EPICS_PREFIX}${CAD}.B $3`
endif
if ($4 != "") then
  set response = `caput ${EPICS_PREFIX}${CAD}.C $4`
endif
if ($5 != "") then 
  set response = `caput ${EPICS_PREFIX}${CAD}.D $5`
endif
if ($6 != "") then 
  set response = `caput ${EPICS_PREFIX}${CAD}.E $6`
endif
if ($7 != "") then 
  set response = `caput ${EPICS_PREFIX}${CAD}.F $7`
endif

#
# Now start the command by sending a START directive to the top
# level apply record, mimicing the action of the OCS.
#

set response = `caput ${EPICS_PREFIX}apply.DIR START`

#
# Wait for a second then read the response from the apply record.
# Display this on the screen if debugging - otherwise the echo commands
# are commented out.
#

sleep 1
set v = `caget -n ${EPICS_PREFIX}apply.VAL`; shift v
if ($v < 0) then
  #echo "Command ${EPICS_PREFIX}${CAD} rejected"
  #caget ${EPICS_PREFIX}apply.MESS
  set v = 1
else 
  #echo "Command ${EPICS_PREFIX}${CAD} accepted"
  set v = 0
endif
exit $v
