#!/bin/csh -f
setenv PATH ${PATH}:./rel/bin/solaris:../gmos_DC/control/bin/solaris
setenv EPICS_DISPLAY_PATH .:./data:./rel/data:../gmos_DC/control/data
dm2.4 gmSeq.dl "T=gm:, S=gm;, C1=cc:, C2=cc:, CC=cc:, DC=dc:" &
