# Include file identifying the target architecture (defines the T_A
# macro) and application configuration definitions

include Target.include
include .applTop/config/CONFIG

# External libraries on which this directory is dependent.
# DEPLIBS      =

# User compiler and loader flags
# SNC_FLAGS    =
# USR_CFLAGS   =
# USR_INCLUDES =
# USR_LDFLAGS  =
# USR_LDLIBS   =

# Add the source code files to this variable. The default has all .c files 
SRCS.c	= \
	../addLoad.c \
	../devAiSoftHS.c \
	../devHsGimbal.c \
	../devHsSoft.c \
	../devHsStage.c \
	../devHsWheel.c \
	../devHsBinary.c \
	../devHsSlide.c \
	../devHmotorHoms.c \
	../devHmotorSoftHS.c \
	../devHmotorTsim.c \
	../drvHoms.c \
	../drvSoftHS.c \
	../recHallStep.c \
	../recHmotor.c \
	../drvOcyc.c \
	../devAiOcyc.c \
	../recTcon.c \
	../devTconOcyc.c \
	../devTconTsim.c \
	../drvOcyd.c \
	../devAiOcyd.c \
	../recTsen.c \
	../devTsenOcyd.c \
	../devTsenTsim.c \
	../recCool.c \
	../devCoolSoft.c \
	../devAiTsim.c \
	../drvTsim.c \
	../ints.c \
	../xy490.c \
	../state.c

# Add the object files in one of these two variables. 
# LIBOBJS += test.o
OBJS	=  $(strip $(patsubst ../%.c,    %.o, $(SRCS.c))             \
		   $(patsubst ../%.st,   %.o, $(wildcard ../*.st  )) \
                   $(patsubst ../%.stpp, %.o, $(wildcard ../*.stpp))) \
				   ccSt.o wfsSt.o

# Standard macros for files which are to be built and installed.
# PROD (products) and SCRIPTS are installed in INSTALL_BIN
# PROD	= $(strip $(patsubst %.o, %, $(OBJS))                        \
#		  $(patsubst ../%.vws, %, $(wildcard ../*.vws)))
PROD	= eng.o
SCRIPTS	=

# LIBNAME is installed in INSTALL_LIB
LIBNAME	=

# INC is installed in INSTALL_INCLUDE
INC	= \
	../recHmotor.h \
	../drvHoms.h \
	../recHallStep.h \
	../ifaErrors.h \
	../xy490.h

# MAN1 is installed in INSTALL_MAN/man1
MAN1	=

# DOCS are installed in INSTALL_DOC
DOCS	=

# DATA are installed in INSTALL_DATA
DATA	=

# Any extra targets can be placed in a TARGETS macro (the build target
# builds only pre_build, LIBNAME, TARGETS and PROD, not SCRIPTS, INC etc)
TARGETS	=

# Rules for building targets
include .applTop/config/RULES.Build

# There is no product rule, but one can be added and edited.
$(PROD): $(OBJS)
	$(RM) $@
	$(LINK.c) $@ $(OBJS)

#
# Generate global operations files, for both the CC and the WFS
#

ccSt.st: ../stateSt.stem
	$(RM) $@
	cpp $(USR_INCLUDES) $(VX_INCLUDES) -DCC ../stateSt.stem > $@ 

ccSt.c: ccSt.st

ccSt.o: ccSt.c
	$(CC) $(CFLAGS) -c ccSt.c

wfsSt.st: ../stateSt.stem
	$(RM) $@
	cpp $(USR_INCLUDES) $(VX_INCLUDES) -DWFS ../stateSt.stem > $@ 

wfsSt.c: wfsSt.st

wfsSt.o: wfsSt.c
	$(CC) $(CFLAGS) -c wfsSt.c
