
include Target.include
include .applTop/config/CONFIG

# You can change the way the sf2db and sch2edif tools work by adding to
# the following flags
# SF2DB_FLAGS    =
# SCH2EDIF_FLAGS =
# E2SR_SYSFLAGS  =
E2SR_SYSFLAGS  = -ate -d ../edb.def
#

# List of ASCII database (*.db) files 
# DEPSCHS is a list of schematics they depend on

DEPSCHS = $(wildcard ../*.sch)
DATA	= 	  nirsSeqTop.db nirsSeqSadTop.db
#gmSeqTopMKRR.db gmSeqTopCP.db  \
#	  gmSeqTopMKSS.db gmSeqTopMKSS2.db \
#	  gmSeqSadTopMKRR.db gmSeqSadTopCP.db \
#	  gmSeqSadTopMKSS.db gmSeqSadTopMKSS2.db\

# Remove these databases from the build list until required
#	  gmSeqTopMKRS.db gmSeqTopMKSR.db
#	  gmSeqSadTopMKRS.db gmSeqSadTopMKSR.db
#	  gmosDcSimTop.db gmosCcSadSimTop.db

include .applTop/config/RULES.Build
