include Target.include
include .applTop/config/CONFIG

# The resource.def will be placed in the data data directory
SCRIPTS	= $(patsubst ../%.SH, %, $(wildcard ../*.SH)) util.sh

include .applTop/config/RULES.Build

../%: ../%.SH ../subst .applTop/config.par
	../subst < ../$*.SH > $@
