# Include file identifying the target architecture (defines the T_A
# macro) and application configuration definitions

include Target.include
include .applTop/config/CONFIG

# External libraries on which this directory is dependent.
# DEPLIBS      =

# User compiler and loader flags
# SNC_FLAGS    =
# USR_CFLAGS   =
# USR_INCLUDES = 
# USR_LDFLAGS  =
# USR_LDLIBS   =

# Add the source code files to this variable. The default has all .c files 
SRCS.c	= $(wildcard ../*.c) 
#SRCS.c	= ../recLutin.c ../devLutinSoft.c \
#	  ../recLutout.c ../devLutoutSoft.c \
#	  ../moveCad.c ../resetCad.c

# Add the object files in one of these two variables. 
# LIBOBJS += test.o
OBJS	=  $(strip $(patsubst ../%.c,    %.o, $(SRCS.c))             \
		   $(patsubst ../%.st,   %.o, $(wildcard ../*.st  )) \
                   $(patsubst ../%.stpp, %.o, $(wildcard ../*.stpp)))

# Standard macros for files which are to be built and installed.
# PROD (products) and SCRIPTS are installed in INSTALL_BIN
#
# NOTE: PROD modified so object files no longer have their ".o" suffix
#       stripped off.
#
#PROD	= $(strip $(patsubst %.o, %, $(OBJS))                        \
#		  $(patsubst ../%.vws, %, $(wildcard ../*.vws)))
PROD    = cics.o comp.o eng.o sys.o

SCRIPTS	=

# LIBNAME is installed in INSTALL_LIB
LIBNAME	=

# INC is installed in INSTALL_INCLUDE
#INC	= cicsLib.h cicsConst.h compLib.h

# MAN1 is installed in INSTALL_MAN/man1
MAN1	=

# DOCS are installed in INSTALL_DOC
DOCS	=

# DATA are installed in INSTALL_DATA
DATA	=

# Any extra targets can be placed in a TARGETS macro (the build target
# builds only pre_build, LIBNAME, TARGETS and PROD, not SCRIPTS, INC etc)
TARGETS	=

# Rules for building targets
include .applTop/config/RULES.Build

# There is no product rule, but one can be added and edited.

CICSOBJS = $(strip $(patsubst ../%.c,    %.o, $(wildcard ../cics*.c)))

cics.o: $(CICSOBJS)
	$(RM) $@
	$(LINK.c) $@ $(CICSOBJS)

COMPOBJS = $(strip $(patsubst ../%.c,    %.o, $(wildcard ../comp*.c))) \
	$(patsubst ../%.stpp, %.o, $(wildcard ../comp*.stpp))

comp.o: $(COMPOBJS)
	$(RM) $@
	$(LINK.c) $@ $(COMPOBJS)

ENGOBJS = $(strip $(patsubst ../%.c,    %.o, $(wildcard ../eng*.c))) \
	$(patsubst ../%.stpp, %.o, $(wildcard ../eng*.stpp))

eng.o: $(ENGOBJS)
	$(RM) $@
	$(LINK.c) $@ $(ENGOBJS)

SYSOBJS = $(strip $(patsubst ../%.c,    %.o, $(wildcard ../sys*.c))) \
	$(patsubst ../%.stpp, %.o, $(wildcard ../sys*.stpp))

sys.o: $(SYSOBJS)
	$(RM) $@
	$(LINK.c) $@ $(SYSOBJS)
