[schematic2]
uniq 68
[tools]
[detail]
w 488 -949 100 0 n#63 hwin.hwin#62.in 512 -960 512 -960 esirs.minInt.INP
w -120 -949 100 0 n#61 hwin.hwin#60.in -96 -960 -96 -960 esirs.exposed.INP
[cell use]
use esirs 1648 199 100 0 obsepoch
xform 0 1856 352
p 1744 176 100 0 1 DESC:EPOCH at exposure start
p 1584 0 100 0 0 EGU:time
p 1584 -64 100 0 0 FDSC:EPOCH at exposure start
p 1744 144 100 0 1 FTVL:DOUBLE
p 1840 128 100 0 0 PREC:11
p 1744 80 100 0 1 PV:$(sadtop)
p 1744 112 100 0 1 SNAM:
p 1760 192 100 1024 0 name:$(sadtop)$(I)
use esirs 1056 -729 100 0 dhsMissing
xform 0 1264 -576
p 1152 -752 100 0 1 DESC:DHS server connected
p 992 -928 100 0 0 EGU:0/1
p 992 -992 100 0 0 FDSC:Is DHS server connected? (1=Yes/0=NO)
p 1152 -784 100 0 1 FTVL:LONG
p 1152 -848 100 0 1 PV:$(sadtop)
p 1152 -816 100 0 1 SNAM:
p 1168 -736 100 1024 0 name:$(sadtop)$(I)
use esirs 512 -1209 100 0 minInt
xform 0 720 -1056
p 608 -1248 100 0 1 DESC:minimum integration time
p 704 -1344 100 0 0 SCAN:1 second
p 624 -1216 100 1024 0 name:$(sadtop)$(I)
use esirs 1056 679 100 0 qlStream
xform 0 1264 832
p 1152 656 100 0 1 DESC:Current DHS quick look stream
p 992 480 100 0 0 EGU:
p 992 416 100 0 0 FDSC:Current DHS quick look stream
p 1152 624 100 0 1 FTVL:STRING
p 1152 560 100 0 1 PV:$(sadtop)
p 1152 592 100 0 1 SNAM:
p 1168 672 100 1024 0 name:$(sadtop)$(I)
use esirs 1056 199 100 0 dhsConnected
xform 0 1264 352
p 1152 176 100 0 1 DESC:DHS server connected
p 992 0 100 0 0 EGU:0/1
p 992 -64 100 0 0 FDSC:Is DHS server connected? (1=Yes/0=NO)
p 1152 144 100 0 1 FTVL:LONG
p 1152 80 100 0 1 PV:$(sadtop)
p 1152 112 100 0 1 SNAM:
p 1168 192 100 1024 0 name:$(sadtop)$(I)
use esirs 1120 -1209 100 0 elapsed
xform 0 1328 -1056
p 1216 -1232 100 0 1 DESC:Total elapsed time
p 1216 -1296 100 0 1 EGU:seconds
p 1056 -1472 100 0 0 FDSC:Total elapsed time
p 1216 -1264 100 0 1 FTVL:DOUBLE
p 1216 -1360 100 0 1 PV:$(sadtop)
p 1216 -1328 100 0 1 SNAM:
p 1232 -1216 100 1024 0 name:$(sadtop)$(I)
use esirs -96 -1209 100 0 exposed
xform 0 112 -1056
p 0 -1232 100 0 1 DESC:Actual total integration time
p 0 -1296 100 0 1 EGU:seconds
p -160 -1472 100 0 0 FDSC:Actual total integration time
p 0 -1264 100 0 1 FTVL:DOUBLE
p 0 -1360 100 0 1 PV:$(sadtop)
p 0 -1328 100 0 1 SNAM:
p 16 -1216 100 1024 0 name:$(sadtop)$(I)
use esirs -704 -1209 100 0 exposedRQ
xform 0 -496 -1056
p -608 -1232 100 0 1 DESC:Requested total integration time
p -608 -1296 100 0 1 EGU:seconds
p -768 -1472 100 0 0 FDSC:Requested total integration time
p -608 -1264 100 0 1 FTVL:DOUBLE
p -608 -1360 100 0 1 PV:$(sadtop)
p -512 -1344 100 0 0 SCAN:1 second
p -608 -1328 100 0 1 SNAM:
p -592 -1216 100 1024 0 name:$(sadtop)$(I)
use esirs 512 -729 100 0 utend
xform 0 720 -576
p 608 -752 100 0 1 DESC:UT at exposure end
p 448 -928 100 0 0 EGU:time
p 448 -992 100 0 0 FDSC:UT at exposure end
p 608 -784 100 0 1 FTVL:STRING
p 608 -848 100 0 1 PV:$(sadtop)
p 608 -816 100 0 1 SNAM:
p 624 -736 100 1024 0 name:$(sadtop)$(I)
use esirs -96 -729 100 0 utstart
xform 0 112 -576
p 0 -752 100 0 1 DESC:UT at exposure start
p -160 -928 100 0 0 EGU:time
p -160 -992 100 0 0 FDSC:UT at exposure start
p 0 -784 100 0 1 FTVL:STRING
p 0 -848 100 0 1 PV:$(sadtop)
p 0 -816 100 0 1 SNAM:
p 16 -736 100 1024 0 name:$(sadtop)$(I)
use esirs -704 -729 100 0 utnow
xform 0 -496 -576
p -608 -752 100 0 1 DESC:Universal Time now
p -768 -928 100 0 0 EGU:time
p -768 -992 100 0 0 FDSC:Universal Time now
p -608 -784 100 0 1 FTVL:STRING
p -608 -848 100 0 1 PV:$(sadtop)
p -608 -880 100 0 1 SCAN:1 second
p -608 -816 100 0 1 SNAM:
p -592 -736 100 1024 0 name:$(sadtop)$(I)
use esirs 512 -249 100 0 nframes
xform 0 720 -96
p 608 -272 100 0 1 DESC:Frames per data set
p 608 -336 100 0 1 EGU:number
p 448 -512 100 0 0 FDSC:Frames per data set
p 608 -304 100 0 1 FTVL:LONG
p 608 -400 100 0 1 PV:$(sadtop)
p 608 -368 100 0 1 SNAM:
p 624 -256 100 1024 0 name:$(sadtop)$(I)
use esirs 512 679 100 0 bunit
xform 0 720 832
p 608 656 100 0 1 DESC:Data units
p 448 480 100 0 0 EGU:
p 448 416 100 0 0 FDSC:Data units (as generated by array)
p 608 624 100 0 1 FTVL:STRING
p 608 560 100 0 1 PV:$(sadtop)
p 608 592 100 0 1 SNAM:
p 624 672 100 1024 0 name:$(sadtop)$(I)
use esirs -96 -249 100 0 nexp
xform 0 112 -96
p 0 -272 100 0 1 DESC:Actual exposures per data set
p 0 -336 100 0 1 EGU:number
p -160 -512 100 0 0 FDSC:Actual exposures per data set
p 0 -304 100 0 1 FTVL:LONG
p 0 -400 100 0 1 PV:$(sadtop)
p 0 -368 100 0 1 SNAM:
p 16 -256 100 1024 0 name:$(sadtop)$(I)
use esirs -704 679 100 0 nexpRQ
xform 0 -496 832
p -608 656 100 0 1 DESC:Requested exposures per data set
p -608 592 100 0 1 EGU:number
p -768 416 100 0 0 FDSC:Requested exposures per data set
p -608 624 100 0 1 FTVL:LONG
p -608 528 100 0 1 PV:$(sadtop)
p -608 560 100 0 1 SNAM:
p -592 672 100 1024 0 name:$(sadtop)$(I)
use esirs -96 679 100 0 dataFrame
xform 0 112 832
p 0 656 100 0 1 DESC:Data frame number
p 0 592 100 0 1 EGU:counter
p -160 416 100 0 0 FDSC:Data frame number
p 0 624 100 0 1 FTVL:LONG
p 0 528 100 0 1 PV:$(sadtop)
p 0 560 100 0 1 SNAM:
p 16 672 100 1024 0 name:$(sadtop)$(I)
use esirs 512 199 100 0 svAddr
xform 0 720 352
p 608 176 100 0 1 DESC:DHS server IP address
p 448 0 100 0 0 EGU:IP 
p 448 -64 100 0 0 FDSC:DHS server IP address
p 608 144 100 0 1 FTVL:STRING
p 608 80 100 0 1 PV:$(sadtop)
p 608 112 100 0 1 SNAM:
p 624 192 100 1024 0 name:$(sadtop)$(I)
use esirs -96 199 100 0 svName
xform 0 112 352
p 0 176 100 0 1 DESC:DHS server name
p -160 0 100 0 0 EGU:
p -160 -64 100 0 0 FDSC:DHS server name
p 0 144 100 0 1 FTVL:STRING
p 0 80 100 0 1 PV:$(sadtop)
p 0 112 100 0 1 SNAM:
p 16 192 100 1024 0 name:$(sadtop)$(I)
use esirs -704 199 100 0 daqState
xform 0 -496 352
p -608 176 100 0 1 DESC:Data acquisition state
p -768 0 100 0 0 EGU:
p -768 -64 100 0 0 FDSC:Data acquisition state
p -608 144 100 0 1 FTVL:STRING
p -608 80 100 0 1 PV:$(sadtop)
p -608 112 100 0 1 SNAM:
p -592 192 100 1024 0 name:$(sadtop)$(I)
use esirs -704 -249 100 0 dataLabel
xform 0 -496 -96
p -608 -272 100 0 1 DESC:Latest data label
p -768 -448 100 0 0 EGU:label
p -768 -512 100 0 0 FDSC:Latest data label
p -608 -304 100 0 1 FTVL:STRING
p -608 -368 100 0 1 PV:$(sadtop)
p -608 -336 100 0 1 SNAM:
p -592 -256 100 1024 0 name:$(sadtop)$(I)
use esirs 1056 -249 100 0 instrument
xform 0 1264 -96
p 992 -352 100 0 1 DESC:Instrument name
p 1152 -304 100 1024 1 name:$(sadtop)$(I)
use esirs 1648 -249 100 0 datestart
xform 0 1856 -96
p 1744 -272 100 0 1 DESC:DATE at exposure start
p 1584 -448 100 0 0 EGU:time
p 1584 -512 100 0 0 FDSC:DATE at exposure start
p 1744 -304 100 0 1 FTVL:STRING
p 1744 -368 100 0 1 PV:$(sadtop)
p 1744 -336 100 0 1 SNAM:
p 1760 -256 100 1024 0 name:$(sadtop)$(I)
use hwin -960 -521 100 0 hwin#50
xform 0 -864 -480
p -957 -488 100 0 -1 val(in):Bancomm address
use hwin -912 -1001 100 0 hwin#59
xform 0 -816 -960
p -909 -968 100 0 -1 val(in):integTime.VAL
use hwin -288 -1001 100 0 hwin#60
xform 0 -192 -960
use hwin 320 -1001 100 0 hwin#62
xform 0 416 -960
p 323 -968 100 0 -1 val(in):$(top)minInt.VAL
use CBorder -1120 -1496 -100 0 frame
xform 0 560 -192
p 1952 -1364 75 1536 -1 Author:Steven M. Beard
p 1448 -1360 100 1536 1 Date:13 Jun 97
p 1552 -1264 300 1792 -1 Dnumber:
p 1680 -1280 150 1536 -1 Title:dataSad.sch
use notes 1568 -1113 100 0 notes#38
xform 0 1824 -928
p 1596 -802 100 0 -1 COMMENT1:This schematic contains the Status Alarm
p 1596 -834 100 0 -1 COMMENT2:database records for GNAAC data
p 1596 -864 100 0 -1 COMMENT3:handling.
p 1596 -960 100 0 -1 COMMENT6:The Status Alarm Database must be loaded
p 1596 -992 100 0 -1 COMMENT7:separately from the rest of the GNAAC
p 1596 -1024 100 0 -1 COMMENT8:database.
[comments]
