
include Target.include
include .applTop/config/CONFIG

# You can change the way the sf2db and sch2edif tools work by adding to
# the following flags
# SF2DB_FLAGS    =
# SCH2EDIF_FLAGS =
#

E2SR_SYSFLAGS = -aetc -d ../edb.def
SF2DB         = $(EPICS_BASE)/bin/$(HOST_ARCH)/sf2db
SCH2EDIF      = $(CAPDIR)/sch2edif
#SCH2EDIF      = /home/p3/wcs/bin/sch2edif

# List of ASCII database (*.db) files 
# DEPSCHS is a list of schematics they depend on

DEPSCHS = $(wildcard ../*.sch)
#DATA	= $(patsubst ../%.sch, %.db, $(wildcard ../*.sch))
#DATA	= naacTop.db naacSadTop.db dqDummy.db noaoTop.db noaoSadTop.db niriTop.db niriSadTop.db nirsTop.db nirsSadTop.db
DATA	= nirsTop.db nirsSadTop.db
include .applTop/config/RULES.Build
