#! /bin/sh

#
# This script adds all the necessary links to the "capfast" subdirectory.
# It should be executed with the capfast subdirectory as the
# current directory.
#
# Invocation:
#    makeLinks
#       Makes the links but does not remove any existing real files.
#    makeLinks -f
#       Forces makeLinks to remove any existing files of the same name.
#

. .applTop/config.par

#
# Parse command line options
#

rmfiles=no
if [ "$1" = '-f' ]; then
	rmfiles=yes
fi

#
# Links to EPICS fixes (these should disappear one day, I hope)
#

fixes="
	egenSub.sym
	escan.sym
	escans.sym
	estringin.sym
	estringins.sym
	ewait.sym
	ecad2.sym
	ecad4.sym
"

#
# Links to Gemini and CICS utility schematics
#

utils="
	                  eapplyx.sym
	cadCar.sch        cadCar.sym
	cadPlus.sch       cadPlus.sym
	carPlus.sch       carPlus.sym
	comb2mSad.sch     comb2mSad.sym
	combCar.sch       combCar.sym
	combSadHealth.sch combSadHealth.sym
	combVal.sch       combVal.sym
	link2Dir.sch      link2Dir.sym
	mfanout.sch       mfanout.sym
	notes.sch         notes.sym
	snl.sch           snl.sym
	templateC.sch
	templateD.sch
	templateTop.sch
  	                  dummy.sym
"

#
# Links to component schematics obtained from the CICS Components
# Controller.
#

ccs="
	comp1CadSel.sch       comp1CadSel.sym
	comp1Car.sch          comp1Car.sym
	comp1m.sch            comp1m.sym
	comp1mCad.sch         comp1mCad.sym
	comp1mCadCmd.sch      comp1mCadCmd.sym
	comp1mSad.sch         comp1mSad.sym
	comp1mSadEng.sch      comp1mSadEng.sym
	comp1mSadHealth.sch   comp1mSadHealth.sym
	comp1mSadRec.sch      comp1mSadRec.sym
	comp1pCadCmd.sch      comp1pCadCmd.sym
	comp2CadSel.sch       comp2CadSel.sym
	comp2Car.sch          comp2Car.sym
	comp2m.sch            comp2m.sym
	comp2mCad.sch         comp2mCad.sym
	comp2mCadAlt.sch      comp2mCadAlt.sym
	comp2mCadCmd.sch      comp2mCadCmd.sym
	comp2mSad.sch         comp2mSad.sym
	comp2mSadAlt.sch      comp2mSadAlt.sym
	comp3mCadCmd.sch      comp3mCadCmd.sym
	compCad.sch           compCad.sym
	compSnlArg.sch        compSnlArg.sym
	compSnlCmd.sch        compSnlCmd.sym
	lock.sch              lock.sym
	lockCad.sch           lockCad.sym
	lockCar.sch           lockCar.sym
	lockSad.sch           lockSad.sym
	lockSadHealth.sch     lockSadHealth.sym
	tmpSad.sch            tmpSad.sym
	tmpSadCool.sch        tmpSadCool.sym
	tmpSadCtrl.sch        tmpSadCtrl.sym
	tmpSadSens.sch        tmpSadSens.sym
"

#
# First remove all existing references to the .sch and .sym files
# linked by this script. If rmfiles="yes", then real files are removed,
# otherwise only links are removed.
#

if [ $rmfiles = "yes" ]; then
	#
	# Remove all existing references to the .sch and .sym files.
	#

	rm -f $fixes $utils $ccs
else
	#
	# Remove only existing links to .sch and .sym files.
	#

	rm -f `find . \( -name '*.sch' -o -name '*.sym' \) -type l -print`
fi

#
# Make links
#

for file in $fixes $utils $ccs; do
	ln -s $libdir/capfast/$file
done
