#! /bin/sh

#
# This script removes the generated top-level capfast diagrams,
#
#    cleanTop *Set.sch
#

if [ $# -lt 1 ]; then
	2>&1 echo "`basename $0`: `basename $0` FILE1Set.sch [...]"
	exit 1
fi

for file in $@; do
	case $file in
	*Set.sch)
		prefix=`echo $1 | sed 's;\(.*\)Set.sch;\1;'`
		echo Deleting ${prefix}Top.sch
		rm -f ${prefix}Top.sch
		shift
		;;
	*)
		1>&2 echo "$file: name is invalid (ignored)"
		;;
	esac
done
