# Makefile,v 1.2 1995/09/02 01:45:04 epics Exp
#

include .applTop/config/CONFIG

APPLIC_DIR_TYPE = src

include .applTop/config/RULES.Dirs

# DO NOT DELETE THIS LINE -- make depend depends on it.

tnetDev.o: tnetDev.h /usr/include/sys/types.h
tnetDev.o: /usr/include/sys/feature_tests.h /usr/include/sys/isa_defs.h
tnetDev.o: /usr/include/sys/machtypes.h /usr/include/sys/socket.h
tnetDev.o: /usr/include/sys/netconfig.h /usr/include/netinet/in.h
tnetDev.o: /usr/include/sys/stream.h /usr/include/sys/vnode.h
tnetDev.o: /usr/include/sys/t_lock.h /usr/include/sys/machlock.h
tnetDev.o: /usr/include/sys/dki_lkinfo.h /usr/include/sys/dl.h
tnetDev.o: /usr/include/sys/sleepq.h /usr/include/sys/turnstile.h
tnetDev.o: /usr/include/sys/param.h /usr/include/sys/unistd.h
tnetDev.o: /usr/include/sys/pirec.h /usr/include/sys/mutex.h
tnetDev.o: /usr/include/sys/rwlock.h /usr/include/sys/semaphore.h
tnetDev.o: /usr/include/sys/condvar.h /usr/include/sys/time.h
tnetDev.o: /usr/include/sys/cred.h /usr/include/sys/uio.h
tnetDev.o: /usr/include/vm/seg_enum.h /usr/include/sys/poll.h
tnetDev.o: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
tnetDev.o: /usr/include/arpa/inet.h /usr/include/
tnetDev.o: /usr/include/sys/types.h /usr/include/sys/feature_tests.h
tnetDev.o: /usr/include/sys/isa_defs.h /usr/include/sys/machtypes.h
tnetDev.o: /usr/include/sys/socket.h /usr/include/sys/netconfig.h
tnetDev.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
tnetDev.o: /usr/include/sys/vnode.h /usr/include/sys/t_lock.h
tnetDev.o: /usr/include/sys/machlock.h /usr/include/sys/dki_lkinfo.h
tnetDev.o: /usr/include/sys/dl.h /usr/include/sys/sleepq.h
tnetDev.o: /usr/include/sys/turnstile.h /usr/include/sys/param.h
tnetDev.o: /usr/include/sys/unistd.h /usr/include/sys/pirec.h
tnetDev.o: /usr/include/sys/mutex.h /usr/include/sys/rwlock.h
tnetDev.o: /usr/include/sys/semaphore.h /usr/include/sys/condvar.h
tnetDev.o: /usr/include/sys/time.h /usr/include/sys/cred.h
tnetDev.o: /usr/include/sys/uio.h /usr/include/vm/seg_enum.h
tnetDev.o: /usr/include/sys/poll.h /usr/include/sys/strmdep.h
tnetDev.o: /usr/include/sys/byteorder.h /usr/include/arpa/inet.h
tnetDev.o: /usr/include/
