
include Target.include
include .applTop/config/CONFIG

# You can change the way the sf2db and sch2edif tools work by adding to
# the following flags
# SF2DB_FLAGS    =
# SCH2EDIF_FLAGS =
# E2SR_SYSFLAGS  =
#

# List of ASCII database (*.db) files 
# DEPSCHS is a list of schematics they depend on
E2SR_SYSFLAGS = -atec -d ../edb.def
DEPSCHS = $(wildcard ../*.sch)
#DATA	= $(patsubst ../%.sch, %.db, $(wildcard ../*.sch))
DATA = nirsCCTop.db nirsCCSadTop.db temperatureControl.db
#CcSadTop.db
include .applTop/config/RULES.Build
