#! /bin/sh
#
# Sets up all the NIRS EPICS UAE application directories after unpacking.
#
# Invocation:
#   ./nirsSetup
#
# Steven M Beard, Hubert Yamada
# 14 Mar 1997: CICS version.
# 27 May 1997: NIRS version.
# 28 May 1997: Added WFS.
#

########################################################################
# Start with a few sanity checks.
########################################################################

#
# Check that the EPICS startup file has been sourced.
#

if [ ${EPICS:-undefined} = undefined ]; then
   1>&2 echo 'EPICS environment variables have not been defined.  Please'
   1>&2 echo 'source your local EPICS setup script (see "nirsLogin_SAMPLE"'
   1>&2 echo 'for an example).'
   exit 1
fi

#
# Check that the NIRS environment variables have been set up. This
# should have been done by sourcing a locally modified version of the
# "nirsLogin" script.
#

#if [ ${NIRS_DIR:-undefined} = undefined ]; then
#   1>&2 echo "NIRS environment variables have not been defined. Please source" 
#   1>&2 echo "your local version of the 'nirsLogin' script to define these."
#   exit 1
#fi
echo $DHS_DIR
#exec ./nirs.env
export DHS_DIR
export NIRS_DIR
export NIRS_LIBDIR
export NIRS_ENGDIR
export NIRS_CCDIR
export NIRS_WFSDIR
export NIRS_WCSDIR
export NIRS_DCDIR
export NIRS_ISDIR
export NIRS_DIR
export NIRS_TARGETS
export NIRS_TIMELIBDIR
export NIRS_SLALIBDIR
export NIRS_ASTLIBDIR
export NIRS_PREFIX
export NIRS_SADPREFIX
export NIRS_DCPREFIX
export NIRS_DCSADPREFIX
export NIRS_NAME
export NIRS_TMPSCAN
export NIRS_TMPVAR
export NIRS_TMPHB
export NIRS_AGPREFIX
export NIRS_USEVXTIME
export NIRS_USEBANCOMM
#
# Now that we've made some attempt to insure that the variables are
# defined, let the user know what is defined.
#

echo "                  Top level NIRS directory = ${NIRS_DIR}"
#echo "            NIRS common/library directory  = $NIRS_LIBDIR"
#echo "                NIRS Engineering directory = $NIRS_ENGDIR"
echo " NIRS/CICS Components Controller directory = ${NIRS_CCDIR}"
echo "      NIRS/CICS Wavefront Sensor directory = ${NIRS_WFSDIR}"
echo "                   NIRS/CICS WCS directory = ${NIRS_WCSDIR}"
echo "   Detector Controller Interface directory = ${NIRS_DCDIR}"
echo "            Instrument Sequencer directory = ${NIRS_ISDIR}"
echo "                              NIRS targets = ${NIRS_TARGETS}"
#
# Define a function to add a pattern to a cvs file.
#
# Syntax: addcvs CVSIGNOREFILE PATTERN
#

addcvs () {
	cvsignore=$1
	pattern=$2

	if [ "`grep -c $pattern $cvsignore`" -eq 0 ]; then
		echo "* Adding \"$pattern\" to $cvsignore".
		echo "$pattern" >> $cvsignore
	fi
}
#
# Define a function to add a directory name to the Makefile.subdirs file
#
# Syntax: addsubdir PATTERN
#

addsubdir () {
	dir=$1

	if [ "`grep -c $dir Makefile.subdirs`" -eq 0 ]; then
	    echo "* Adding $dir directory to Makefile.subdirs"
	    mv Makefile.subdirs Makefile.tmp
	    echo "DIRS += $dir" | cat >Makefile.subdirs
	    cat Makefile.tmp >>Makefile.subdirs
	    /usr/bin/rm -f Makefile.tmp
	fi 
}


###########################################################################
# Set up subdirectories.
###########################################################################

#
# Define a function to be used to set up subdirectories:
#
# Syntax:
#     setupdir PATH DESCRIPTION


setupdir () {
	dirpath="$1"
	dirname="$2"

	echo cd $dirpath
	cd $dirpath

	echo "* Setting up $dirname."
	echo "---------------------------------------------------------------------"

	$dirpath/nirsSetup
	status=$?

	echo "---------------------------------------------------------------------"

	if [ $status -ne 0 ]; then
		echo "*** $dirname setup failed. NIRS setup abandoned. ***"
		exit $status
	elif [ ! -h $dirpath/.applTop ]; then
		echo "*** $dirname failed. NIRS setup abandoned. ***"
		exit 1
	else
		echo "* $dirname set up successfully"
	fi
}

#setupdir "$NIRS_LIBDIR" "NIRS library (LIB) directory"
if [ ${1:-undefined} = DC ]; then
    
	setupdir "$NIRS_DCDIR" "NIRS detector interface (DC) directory" 
elif [ ${1:-undefined} = CC ]; then
	setupdir "$NIRS_CCDIR" "NIRS components controller (CC) directory"
elif [ ${1:-undefined} = IS ]; then
	setupdir "$NIRS_ISDIR" "NIRS instrument sequencer (IS) directory"
elif [ ${1:-undefined} = WFS ]; then
	setupdir "$NIRS_WFSDIR" "NIRS wavefront sensor components (WFS) directory"
else
	setupdir "$NIRS_DCDIR" "NIRS detector interface (DC) directory" 
	setupdir "$NIRS_ISDIR" "NIRS instrument sequencer (IS) directory"
	setupdir "$NIRS_CCDIR" "NIRS components controller (CC) directory"
	setupdir "$NIRS_WFSDIR" "NIRS wavefront sensor components (WFS) directory"
	#setupdir "$NIRS_WCSDIR" "NIRS wavefront sensor components (WCS) directory"
	#setupdir "$NIRS_ENGDIR" "NIRS low-level functions (ENG) directory"


    ###########################################################################
    # Finally, set up the top level directory.
    ###########################################################################
    cd $NIRS_DIR
    
    echo "---------------------------------------------------------------------"
    echo "* Setting up top-level NIRS directory."

    #
    # If these files exist, they won't be overwritten.  Remove them to
    # be safe.
    #

    if [ -f config/CONFIG.Defs ]; then
	    echo "* Removing old CONFIG.Defs."
	    rm config/CONFIG.Defs
    fi

    if [ -f startup/local.vws ]; then
	    echo "* Removing old local.vws."
	    rm startup/local.vws
    fi
    
    if [ -f startup/resource.def ]; then
	    echo "* Removing old startup/resource.def."
	    rm startup/resource.def
    fi

    #
    # Now set up the epics directory
    #
   # -base ${NIRS_EPICS_DIR}
    applSetup -install ${NIRS_DIR}  -targets ${NIRS_TARGETS} -P ${NIRS_INSTPATH} \
	    -I startup -I ascii -I src -I dl -I capfast  -I pv -I testing -s Makefile.subdirs
    

    addsubdir WFS 
    addsubdir IS
    addsubdir CC 
    addsubdir DC 
    #addsubdir WCS 
    #addsubdir LIB 
    #addsubdir ENG
    ###########################################################################
    # Generate configuration files.
    ###########################################################################

    echo "* Generating config.par. ${NIRS_DIR}"
    addcvs startup/.cvsignore resource.def
    addcvs startup/.cvsignore UAE.dist
    addcvs .cvsignore config.par
fi
###########################################################################
# Force the LIB, CC, WFS, WCS, IS, DC, and ENG directories to be included 
# at the beginning of Makefile.subdirs so that a "gmake" on the top level
# directory will build these as well, and build them first.  Note that
# a directory must precede any directories that it depends on.
###########################################################################



cat << _EOF_ > config.par


##########################################################################
# This file was automatically generated by `whoami`@`hostname`
# using nirsSetup on:
#     `date`.
#
# Do not edit this file by hand, because it will be destroyed the next
# time that nirsSetup is run.
##########################################################################
	agprefix=${NIRS_AGPREFIX}
	astlibdir=${NIRS_ASTLIBDIR}
	ccdir=${NIRS_CCDIR}
	dcdir=${NIRS_DCDIR}
	dcprefix=${NIRS_DCPREFIX}
	dcsadprefix=${NIRS_DCSADPREFIX}
	dir=${NIRS_DIR}
	engdir=${NIRS_ENGDIR}
	epicsdir=${EPICS}
	hostarch=${HOST_ARCH}
	isdir=${NIRS_ISDIR}
	libdir=${NIRS_LIBDIR}
	name=${NIRS_NAME}
	prefix=${NIRS_PREFIX}
	sadprefix=${NIRS_SADPREFIX}
	slalibdir=${NIRS_SLALIBDIR}
	timelibdir=${NIRS_TIMELIBDIR}
	usevxtime=${NIRS_USEVXTIME}
	usebancomm=${NIRS_USEBANCOMM}
	wcsdir=${NIRS_WCSDIR}
	wfsdir=${NIRS_WFSDIR}
	wfswfsdir=${NIRS_WFSWFSDIR}
_EOF_
