#! /bin/sh

# $Id: listCad,v 1.2 2009/05/27 19:33:55 fkraemer Exp $

#
# A quick-and-dirty script to list all CAD records, for documentation
# purposes.
#

. .applTop/config.par

files=`for file in [A-Z]*[A-Z]; do
	if [ -d $file/data ]; then
		find $file/data -name \*.db
	fi
done`

cat $files | nawk '
	/^[	 ]*record\(/ {
		gsub(/^[ 	]*record\(/,"")
		gsub(/\)[ 	]*{[ 	]*$/,"")

		record=$0
		gsub(/,.*/,"",record)

		name=$0
		gsub(/^[0-9a-zA-Z]*,"/,"",name)
		gsub(/"$/,"",name)
		gsub(/'${sadprefix}'/,"",name)
	}

	/^[	 ]*field\(/ {
		gsub(/^[ 	]*field\(/,"")
		gsub(/\)$/,"")

		field=$0
		gsub(/,.*/,"",field)

		value=$0
		gsub(/^[0-9a-zA-Z]*,"/,"",value)
		gsub(/"$/,"",value)

		if (field == "DESC") {
			desc = value
		}
	}

	/}/ {
		if (record == "cad") {
			printf "%s: \"%s\"\n", name, desc
		}
	}

	{ next }
'
