#!/bin/csh
#
# Tidies up a NIRI appication directory prior to release by giving the
# user the option of removing certain files.
#
/usr/bin/rm -i `find * -name "*.ps" -print`
/usr/bin/rm -i `find * -name "*.xwd" -print`
/usr/bin/rm -i `find * -name "*.tmp" -print`
/usr/bin/rm -i `find * -name "*.bak" -print`
/usr/bin/rm -i `find * -name "*.undo" -print`
/usr/bin/rm -i `find * -name "*%" -print`
/usr/bin/rm -i `find * -name "*.*_*" -print`
/usr/bin/rm -i `find * -name "textedit.*" -print`

