#! /bin/sh

#########################################################################
# Script for starting the stand-alone Detector Controller control
# screens for the Near Infra-Red Imager.  (Derived from the
# Steven Beard's CICS startup scripts, by Hubert Yamada.)
#########################################################################

#########################################################################
# History:
#
# Original script written by Steven Beard, Based on the corresponding
# CICS script.
#
# Rewritten for NIRI and converted to use the Bourne Shell, by Hubert
# Yamada.
#
# $Log: niriDcStart,v $
# Revision 1.2  2009/05/27 19:33:55  fkraemer
# fkraemer - copied my complete working dir over trunk
#
# Revision 1.13  1999/11/13 06:31:19  yamada
# Release 1.00 alpha 06.
#
# Revision 1.12  1999/11/13 06:27:44  yamada
# Release 1.00 alpha 06.
#
# Revision 1.11  1999/11/12 08:12:18  yamada
# Got rid of the NN macro.  Now all screens get their titles from the
# database.
#
# Revision 1.10  1999/11/12 03:25:17  yamada
# Simplified engineering startup scripts and made the names more similar to
# the names for the system-wide startup scripts.  Final rearrangement of
# directory structure.  Final cleanup for release 1.00 alpha 6.
#
# Revision 1.9  1999/11/10 21:10:55  yamada
# Rewrote configuration files to be more uniform.  Moved common startup
# files from the IS directory into the root directory.
#
#########################################################################

#########################################################################
# Configuration parameters
#########################################################################

dm=dm2.4

#########################################################################
# Check that the EPICS startup file has been sourced.
#########################################################################

if [ "${EPICS}" = "" ]; then
   echo 'EPICS environment variables have not been defined. Please source'
   echo 'your local EPICS setup script.  (The EPICS startup script is'
   echo 'normally sourced by "niriLogin".)'
   exit
fi

if [ "${NIRI_DIR}" = "" ]; then
   echo 'NIRI DC environment variables have not been defined. Please source'
   echo 'your local EPICS setup script, e.g., "niriLogin".'
   exit
fi

#########################################################################
# If a search path for the display screens has already been defined,
# Add the current directory and "data" subdirectories in front of
# the search path for display screens, creating a path if necessary.
#########################################################################

if [ "${EPICS_DISPLAY_PATH}" = "" ]; then
	EPICS_DISPLAY_PATH=.:${NIRI_DCPKGDIR}/data:${EPICS_DISPLAY_PATH}
else
	EPICS_DISPLAY_PATH=.:${NIRI_DCPKGDIR}/data
fi
export EPICS_DISPLAY_PATH

#########################################################################
# Finally, start the display screens in the background. The macros T,
# and S define the prefixes used for the EPICS record names.
#########################################################################

echo "Starting NIRI stand-alone Detector Controller screens..."
$dm gnaacEngDisp.dl "T=${NIRI_DCPREFIX}dc:, S=${NIRI_DCSADPREFIX}dc:" &
