#! /bin/sh
#
# Sets up all the NIRI EPICS UAE application directories after unpacking.
#
# Invocation:
#   ./niriSetup
#
# Steven M Beard, Hubert Yamada
# 14 Mar 1997: CICS version.
# 27 May 1997: NIRI version.
# 28 May 1997: Added WFS.
#

########################################################################
# Start with a few sanity checks.
########################################################################

#
# Check that the EPICS startup file has been sourced.
#

if [ ${EPICS:-undefined} = undefined ]; then
   1>&2 echo 'EPICS environment variables have not been defined.  Please'
   1>&2 echo 'source your local EPICS setup script (see "niriLogin_SAMPLE"'
   1>&2 echo 'for an example).'
   exit 1
fi

#
# Check that the NIRI environment variables have been set up. This
# should have been done by sourcing a locally modified version of the
# "niriLogin" script.
#

if [ ${NIRI_DIR:-undefined} = undefined ]; then
   1>&2 echo "NIRI environment variables have not been defined. Please source" 
   1>&2 echo "your local version of the 'niriLogin' script to define these."
   exit 1
fi

#
# Now that we've made some attempt to insure that the variables are
# defined, let the user know what is defined.
#

echo "                  Top level NIRI directory = $NIRI_DIR"
echo "            NIRI common/library directory  = $NIRI_LIBDIR"
echo "                NIRI Engineering directory = $NIRI_ENGDIR"
echo " NIRI/CICS Components Controller directory = $NIRI_CCDIR"
echo "      NIRI/CICS Wavefront Sensor directory = $NIRI_WFSDIR"
echo "                   NIRI/CICS WCS directory = $NIRI_WCSDIR"
echo "   Detector Controller Interface directory = $NIRI_DCDIR"
echo "            Instrument Sequencer directory = $NIRI_ISDIR"
echo "                              NIRI targets = $NIRI_TARGETS"

###########################################################################
# Set up subdirectories.
###########################################################################

#
# Define a function to be used to set up subdirectories:
#
# Syntax:
#     setupdir PATH DESCRIPTION
#

setupdir () {
	dirpath="$1"
	dirname="$2"

	cd $dirpath

	echo "* Setting up $dirname."
	echo "---------------------------------------------------------------------"

	$dirpath/niriSetup
	status=$?

	echo "---------------------------------------------------------------------"

	if [ $status -ne 0 ]; then
		echo "*** $dirname setup failed. NIRI setup abandoned. ***"
		exit $status
	elif [ ! -h $dirpath/.applTop ]; then
		echo "*** $dirname failed. NIRI setup abandoned. ***"
		exit 1
	else
		echo "* $dirname set up successfully"
	fi
}

setupdir "$NIRI_LIBDIR" "NIRI library (LIB) directory"
#setupdir "$NIRI_DCDIR" "NIRI detector interface (DC) directory"
#setupdir "$NIRI_ISDIR" "NIRI instrument sequencer (IS) directory"
#setupdir "$NIRI_CCDIR" "NIRI components controller (CC) directory"
setupdir "$NIRI_WFSDIR" "NIRI wavefront sensor components (WFS) directory"
#setupdir "$NIRI_WCSDIR" "NIRI wavefront sensor components (WCS) directory"
setupdir "$NIRI_ENGDIR" "NIRI low-level functions (ENG) directory"

###########################################################################
# Finally, set up the top level directory.
###########################################################################

cd $NIRI_DIR

echo "---------------------------------------------------------------------"
echo "* Setting up top-level NIRI directory."

#
# If these files exist, they won't be overwritten.  Remove them to
# be safe.
#

if [ -f config/CONFIG.Defs ]; then
	echo "* Removing old CONFIG.Defs."
	rm config/CONFIG.Defs
fi

if [ -f startup/local.vws ]; then
	echo "* Removing old local.vws."
	rm startup/local.vws
fi

if [ -f startup/resource.def ]; then
	echo "* Removing old startup/resource.def."
	rm startup/resource.def
fi

#
# Now set up the epics directory
#

applSetup -install ${NIRI_DIR} -targets ${NIRI_TARGETS} \
	-depends ${NIRI_LIBDIR} -subdir_file Makefile.subdirs \
	-I startup -I scripts -I dl

###########################################################################
# Force the LIB, CC, WFS, WCS, IS, DC, and ENG directories to be included 
# at the beginning of Makefile.subdirs so that a "gmake" on the top level
# directory will build these as well, and build them first.  Note that
# a directory must precede any directories that it depends on.
###########################################################################

#
# Define a function to add a directory name to the Makefile.subdirs file
#
# Syntax: addsubdir PATTERN
#

addsubdir () {
	dir=$1

	if [ "`grep -c $dir Makefile.subdirs`" -eq 0 ]; then
	    echo "* Adding $dir directory to Makefile.subdirs"
	    mv Makefile.subdirs Makefile.tmp
	    echo "DIRS += $dir" | cat >Makefile.subdirs
	    cat Makefile.tmp >>Makefile.subdirs
	    /usr/bin/rm -f Makefile.tmp
	fi 
}

addsubdir WFS 
addsubdir IS
addsubdir CC 
addsubdir DC 
addsubdir WCS 
addsubdir LIB 
addsubdir ENG 

###########################################################################
# The configuration procedure overwrites my .cvsignore files.  Fix them.
###########################################################################

#
# Define a function to add a pattern to a cvs file.
#
# Syntax: addcvs CVSIGNOREFILE PATTERN
#

addcvs () {
	cvsignore=$1
	pattern=$2

	if [ "`grep -c $pattern $cvsignore`" -eq 0 ]; then
		echo "* Adding \"$pattern\" to $cvsignore".
		echo "$pattern" >> $cvsignore
	fi
}

addcvs startup/.cvsignore resource.def
addcvs startup/.cvsignore UAE.dist
addcvs .cvsignore config.par

###########################################################################
# Generate configuration files.
###########################################################################

echo "* Generating config.par."
cat << _EOF_ > config.par
##########################################################################
# This file was automatically generated by `whoami`@`hostname`
# using niriSetup on:
#     `date`.
#
# Do not edit this file by hand, because it will be destroyed the next
# time that niriSetup is run.
##########################################################################
	agprefix=${NIRI_AGPREFIX}
	astlibdir=${NIRI_ASTLIBDIR}
	ccdir=${NIRI_CCDIR}
	dcdir=${NIRI_DCDIR}
	dcprefix=${NIRI_DCPREFIX}
	dcsadprefix=${NIRI_DCSADPREFIX}
	dir=${NIRI_DIR}
	engdir=${NIRI_ENGDIR}
	epicsdir=${EPICS}
	hostarch=${HOST_ARCH}
	isdir=${NIRI_ISDIR}
	libdir=${NIRI_LIBDIR}
	name=${NIRI_NAME}
	prefix=${NIRI_PREFIX}
	sadprefix=${NIRI_SADPREFIX}
	slalibdir=${NIRI_SLALIBDIR}
	timelibdir=${NIRI_TIMELIBDIR}
	usevxtime=${NIRI_USEVXTIME}
	usebancomm=${NIRI_USEBANCOMM}
	wcsdir=${NIRI_WCSDIR}
	wfsdir=${NIRI_WFSDIR}
_EOF_
