#! /bin/sh

# $Id: niriWfsStart,v 1.2 2009/05/27 19:33:56 fkraemer Exp $

if [ "$NIRI_WFSDIR" = "" ]; then
	1>&2 echo "NIRI_WFSDIR is not in your current environment.  Please execute"
	1>&2 echo "your local version of the 'niriLogin' script to add it."
	exit 1
fi

exec ${NIRI_WFSDIR}/niriWfsStart
