#! /bin/csh
#
#
setenv CVS_RELEASE gnirs_northV1-1_AT
setenv NIRS_PREFIX nirs:
setenv NIRS_TARGETS mv167
setenv NIRS_NAME NIRS
setenv NIRS_TMPSCAN "10 second"
setenv NIRS_TMPVAR nirs:sad:cc:tempState
setenv NIRS_TMPHB nirs:sad:cc:heartBeat
setenv NIRS_WFSENGINSTPATH pisces:/gemini/GEM5/gnirs/WFS/WFS/ENG/${CVS_RELEASE}
setenv NIRS_WFSLIBINSTPATH  /gemini/GEM5/gnirs/WFS/WFS/LIB/${CVS_RELEASE}
setenv NIRS_WFSWFSINSTPATH pisces:/gemini/GEM5/gnirs/WFS/WFS/${CVS_RELEASE}

setenv NIRS_ENGDIR /home/mrippa/root/src/gnirsCVS/WFS/ENG
setenv NIRS_LIBDIR /home/mrippa/root/src/gnirsCVS/WFS/LIB
setenv NIRS_WFSWFSDIR /home/mrippa/root/src/gnirsCVS/WFS/WFS
setenv NIRS_ASTLIBDIR /gemini/astlib
setenv NIRS_SLALIBDIR /gemini/slalib
setenv NIRS_TIMELIBDIR /gemini/timelib


