#! /bin/sh

# $Id: niriEtWish,v 1.2 2009/05/27 19:34:40 fkraemer Exp $

TCLSCRIPTS=${NIRI_ENGDIR}/bin/${HOST_ARCH}

exec et_wish << _EOF_
	lappend auto_path ${TCLSCRIPTS}

	source ${TCLSCRIPTS}/init.tcl

	if [$@] {
		exit
	}
_EOF_
