#define ACQ1 "In"
#define ACQ2 "Out"
#define CAMERA1 "ShortRed_G5522"
#define CAMERA2 "LongRed_G5516"
#define CAMERA3 "ShortBlue_G5521"
#define CAMERA4 "LongBlue_G5515"
#define CAMERA5 "open"
#define CAMERA6 "LB+LXD_G5515"
#define CAMERA7 "LB+SXD_G5515"
#define COVER1 "Closed"
#define COVER2 "Open"
#define DECKER1 "ifu1"
#define DECKER2 "LC_XD"
#define DECKER3 "SC_XD"
#define DECKER4 "Wollaston"
#define DECKER5 "LC_Long"
#define DECKER6 "SC_Long"
#define DECKER7 "Acquisition"
#define DECKER8 "ifu2"
#define DECKER9 "PupilViewer"
#define FOCUS1 "auto"
#define FOCUS2 "manual"
#define GRATING1  "Mirror"
#define GRATING2 "Grating_one"
#define GRATING3 "Grating_two"
#define GRATING4 "Grating_three"
#define GRATING5 "Grating_four"
#define GRATING6 "Grating_five"
#define GRATING7 "Grating_six"
#define GRATING8 "Grating_seven"
#define GRATING9 "Grating_eight"
#define GRATING10 "Grating_nine"
#define GRATING11 "Grating_ten"
#define SLIT1 "0.10 arcsec"
#define SLIT2 "0.15 arcsec"
#define SLIT13 "High_res_IFU"
#define SLIT3 "0.20 arcsec"
#define SLIT4 "0.30 arcsec"
#define SLIT5 "0.45 arcsec"
#define SLIT6 "0.675 arcsec"
#define SLIT7 "1.0 arcsec"
#define SLIT8 "Acquisition"
#define SLIT9 "pupil viewer"
#define SLIT10 "SmPinholes"
#define SLIT11 "LgPinholes"
#define SLIT12 "6mm"
#define XDISP1 "SXD_G5509"
#define XDISP2 "MIR_G5511"
#define XDISP3 "LXD_G5508"
#define XDISP4 "WOLL_G5510"
#define XDISP5 ""
#define XDISP6 ""
