
include Target.include
include .applTop/config/CONFIG

ADL2DL = $(EPICS_EXTENSIONS)/bin/$(HOST_ARCH)/adl2dl2.4
# List of display (*.dl) files
DATA    = gmColors.dl \
          $(patsubst ../%.adl, %.dl, $(wildcard ../*.adl ../*.bit ../*.tk ../*.sh))

# Startup scripts to install in the BIN directory
SCRIPTS = gnaacStart

include .applTop/config/RULES.Build
