#!/bin/csh -f
setenv NIRI_ENGDIR /home/gemini/gnirs/niri/ENG
setenv NIRI_PREFIX nirs:
setenv nirsDIR /home/gemini/gnirs/control
setenv niriDIR /home/gemini/gnirs/niri
#setenv TCL_LIBRARY /mpgt/local/lib/tcl8.3
setenv TCL_LIBRARY /home/gemini/epics/epics3.12.2GEM5/extensions/src/tcllib/lib/tcl
setenv TK_LIBRARY /home/gemini/epics/epics3.12.2GEM5/extensions/src/tcllib/lib/tk
setenv EPICS_CA_AUTO_ADDR_LIST YES
setenv EPICS_CA_ADDR_LIST "140.252.31.231 140.252.31.234 140.252.31.207 140.252.31.210 140.252.31.202 140.252.31.212 140.252.1.98"
setenv PATH ${PATH}:${niriDIR}/ENG/bin/${HOST_ARCH}:/home/gemini/epics/epics3.12.2GEM5/extensions/bin/solaris
setenv EPICS_DISPLAY_PATH ${nirsDIR}/data:${nirsDIR}/DC/data:${niriDIR}/ENG/data:${niriDIR}/WFS/data:${niriDIR}/LIB/data
echo EPICS_DISPLAY_PATH
dm2.4 nirsSeqTop.dl "T=nirs:, S=nirs:sad:, C1=cc:, C2=cc:, CC=cc:, DC=dc:" &
