#!/bin/csh -f
setenv NIRI_ENGDIR /home/gnirs/WFS/ENG
setenv NIRI_PREFIX nirs:
setenv nirsDIR /gemini/gnirs/dev
setenv niriDIR /gemini/gnirs/dev/WFS
setenv TCL_LIBRARY /usr/local/epics/epics3.12.2GEM5/extensions/src/tcllib/lib/tcl
setenv TK_LIBRARY /usr/local/epics/epics3.12.2GEM5/extensions/src/tcllib/lib/tk
setenv EPICS_CA_AUTO_ADDR_LIST YES
setenv EPICS_CA_ADDR_LIST "172.17.2.82 172.17.2.85 172.17.3.84"
setenv PATH ${PATH}:${niriDIR}/ENG/bin/${HOST_ARCH}:/usr/local/epics/epics3.12.2GEM5/extensions/bin/solaris:${nirsDIR}/bin/solaris
setenv EPICS_DISPLAY_PATH ${nirsDIR}/data:${nirsDIR}/DC/data:${niriDIR}/ENG/data:${niriDIR}/WFS/data:${niriDIR}/LIB/data:${nirsDIR}/CC/data:${nirsDIR}/IS/data
echo EPICS_DISPLAY_PATH
dm2.4 nirsSeqTop.dl "T=nirs:, S=nirs:sad:, C1=cc:, C2=cc:, CC=cc:, DC=dc:" &
xterm -sb -sl 500 -title "DC epics" -n "DC epics" -e telnet gnirs-annex 5005 &
xterm -sb -sl 500 -title "DC Coadder" -n "DC Coadder" -e telnet gnirs-annex 5006 &
xterm -sb -sl 500 -title "CC" -n "CC" -e telnet gnirs-annex 5003 &
xterm -sb -sl 500 -title "WFS" -n "WFS" -e telnet gnirs-annex 5002 &
