#! /bin/echo cycle.tcl should not be run directly from the command line

# $Id: cycle.tcl,v 1.2 2009/05/27 19:34:51 fkraemer Exp $

set help(cycle) \
	{Help not yet written}

proc cycle:reScan { w mech } {
	global ca

	set status 0

	$w.reScan configure -state disabled

	if { !$status } {
		set status [ca:readVars ${mech}Busy.VAL]
	}

	if { $ca(${mech}Busy.VAL) } {
		tk_dialog .dialog {Busy} {Mechanism is busy} warning 1 Ok
	} else {
		if { !$status } {
			set ca(${mech}Hallstep.CSET) YES
			set status [ca:writeVars ${mech}Hallstep.CSET]
		}

		if { !$status } {
			set ca(${mech}Op.VAL) 5
			set status [ca:writeVars ${mech}Op.VAL]
		}

		while { !$status } {
			set status [ca:readVars ${mech}Busy.VAL]

			if { !$status && !$ca(${mech}Busy.VAL) } {
				break
			}

			after 50	
		}

		if { !$status } {
			set status [ca:readVars "
				${mech}Hallstep.V1PA
				${mech}Hallstep.V1BA
				${mech}Hallstep.V1PB
				${mech}Hallstep.V1BB
				${mech}Hallstep.V1PC
				${mech}Hallstep.V1BC
				${mech}Hallstep.V2PA
				${mech}Hallstep.V2BA
				${mech}Hallstep.V2PB
				${mech}Hallstep.V2BB
				${mech}Hallstep.V2PC
				${mech}Hallstep.V2BC
			"]

			#
			# A kludge to make sure that the displayed fields
			# show the correct values.  There appears to be a bug in 
			# the pv read routine.  
			#

			set ca(${mech}Hallstep.V1PA) $ca(${mech}Hallstep.V1PA)
			set ca(${mech}Hallstep.V1BA) $ca(${mech}Hallstep.V1BA)
			set ca(${mech}Hallstep.V2PA) $ca(${mech}Hallstep.V2PA)
			set ca(${mech}Hallstep.V2BA) $ca(${mech}Hallstep.V2BA)
			set ca(${mech}Hallstep.V1PB) $ca(${mech}Hallstep.V1PB)
			set ca(${mech}Hallstep.V1BB) $ca(${mech}Hallstep.V1BB)
			set ca(${mech}Hallstep.V2PB) $ca(${mech}Hallstep.V2PB)
			set ca(${mech}Hallstep.V2BB) $ca(${mech}Hallstep.V2BB)
			set ca(${mech}Hallstep.V1PC) $ca(${mech}Hallstep.V1PC)
			set ca(${mech}Hallstep.V1BC) $ca(${mech}Hallstep.V1BC)
			set ca(${mech}Hallstep.V2PC) $ca(${mech}Hallstep.V2PC)
			set ca(${mech}Hallstep.V2BC) $ca(${mech}Hallstep.V2BC)
		}
	}

	$w.reScan configure -state normal
}

proc cycle:write { w mech } {
	global ca parms env

	set cancel [tk_dialog .dialog {Confirm} \
		"Generate $parms($mech,file)" question  1 Ok Cancel]

	if { $cancel } {
		return
	}

	set fd [open $parms($mech,file) w]
	set base "\$(top)[string range $mech [string length $env(NIRI_PREFIX)] end]"

	puts -nonewline $fd {# $}; puts $fd {Id$}
	puts $fd "# $ca(${mech}Label.VAL)"
	puts $fd "# $mech"
	puts $fd {}
	puts $fd {# -- Do not edit by hand --}
	puts $fd {# This file was automatically generated by cycle.tcl, on}
	puts $fd "# [exec date]"
	puts $fd {}
	puts $fd "group {"
	puts $fd "\tdouble ${base}Hallstep.E1PA = $ca(${mech}Hallstep.V1PA);"
	puts $fd "\tdouble ${base}Hallstep.E1BA = $ca(${mech}Hallstep.V1BA);"
	puts $fd "\tdouble ${base}Hallstep.E1PB = $ca(${mech}Hallstep.V1PB);"
	puts $fd "\tdouble ${base}Hallstep.E1BB = $ca(${mech}Hallstep.V1BB);"
	puts $fd "\tdouble ${base}Hallstep.E1PC = $ca(${mech}Hallstep.V1PC);"
	puts $fd "\tdouble ${base}Hallstep.E1BC = $ca(${mech}Hallstep.V1BC);"
	puts $fd "\tdouble ${base}Hallstep.E2PA = $ca(${mech}Hallstep.V2PA);"
	puts $fd "\tdouble ${base}Hallstep.E2BA = $ca(${mech}Hallstep.V2BA);"
	puts $fd "\tdouble ${base}Hallstep.E2PB = $ca(${mech}Hallstep.V2PB);"
	puts $fd "\tdouble ${base}Hallstep.E2BB = $ca(${mech}Hallstep.V2BB);"
	puts $fd "\tdouble ${base}Hallstep.E2PC = $ca(${mech}Hallstep.V2PC);"
	puts $fd "\tdouble ${base}Hallstep.E2BC = $ca(${mech}Hallstep.V2BC);"
	puts $fd "};"

	close $fd
}

proc cycle:connect { w mech } {
	global parms const ca

	set status [ca:connect "
		${mech}Busy.VAL
		${mech}Hallstep.CSET
		${mech}Op.VAL
		${mech}Label.VAL
		${mech}Ident.VAL
		${mech}Subdir.VAL
		${mech}Hallstep.V1PA
		${mech}Hallstep.V1BA
		${mech}Hallstep.V2PA
		${mech}Hallstep.V2BA
		${mech}Hallstep.V1PB
		${mech}Hallstep.V1BB
		${mech}Hallstep.V2PB
		${mech}Hallstep.V2BB
		${mech}Hallstep.V1PC
		${mech}Hallstep.V1BC
		${mech}Hallstep.V2PC
		${mech}Hallstep.V2BC
	"]

	set parms($mech,file) \
		$const(pvDir)/$ca(${mech}Subdir.VAL)/$ca(${mech}Ident.VAL).pv
	set parms($w,mech) $mech

	if { $w == {} } {
		wm title . "$ca(${mech}Label.VAL) -- Cycle Tool"
	} else {
		wm title $w "$ca(${mech}Label.VAL) -- Cycle Tool"
	}

	$w.mech configure -text $mech
	$w.reScan configure -command "cycle:reScan {$w} {$mech}"
	$w.write configure -command "cycle:write {$w} {$mech}"
	$w.ident configure -text $ca(${mech}Ident.VAL)
	$w.subdir configure -text $ca(${mech}Subdir.VAL)
	$w.fileName configure -textvar parms($mech,file)
	foreach pos { A B C } {
		$w.v1p${pos} configure -textvar ca(${mech}Hallstep.V1P$pos)
		$w.v2p${pos} configure -textvar ca(${mech}Hallstep.V2P$pos)
		$w.v1b${pos} configure -textvar ca(${mech}Hallstep.V1B$pos)
		$w.v2b${pos} configure -textvar ca(${mech}Hallstep.V2B$pos)
	}

	return $status
}

proc cycle:win { w } {
	global const

	set status 0

	util:win $w cycle

	foreach pos { A B C } {
		frame $w.w$pos -border 0.5m -relief groove
		pack $w.w$pos -in $w.main -padx 0.5m -pady 0.5m -fill x

		label $w.v1p${pos}_t -text V1P$pos -anchor e
		blt_table $w.w$pos $w.v1p${pos}_t 0,0
		label $w.v1p${pos} -anchor e -width 12 -relief sunken -border 0.6m \
			-bg gray
		blt_table $w.w$pos $w.v1p${pos} 0,1 -fill x

		label $w.v2p${pos}_t -text V2P$pos -anchor e
		blt_table $w.w$pos $w.v2p${pos}_t 0,2
		label $w.v2p${pos} -anchor e -width 12 -relief sunken -border 0.6m \
			-bg gray
		blt_table $w.w$pos $w.v2p${pos} 0,3 -fill x

		label $w.v1b${pos}_t -text V1B$pos -anchor e
		blt_table $w.w$pos $w.v1b${pos}_t 1,0
		label $w.v1b${pos} -anchor e -width 12 -relief sunken -border 0.6m \
			-bg gray
		blt_table $w.w$pos $w.v1b${pos} 1,1 -fill x

		label $w.v2b${pos}_t -text V2B$pos -anchor e
		blt_table $w.w$pos $w.v2b${pos}_t 1,2
		label $w.v2b${pos} -anchor e -width 12 -relief sunken -border 0.6m \
			-bg gray
		blt_table $w.w$pos $w.v2b${pos} 1,3 -fill x
	}

	util:table $w.params 50 "
		{ label $w.mech {Mech} {The EPICS prefix} }
		{ label $w.pvDir {.pv base directory} \
			{Default base directory for .pv files} }
		{ label $w.subdir {.pv subdirectory} \
			{Current subdirectory for .pv files} }
		{ label $w.ident {Ident} {Base name for .pv file} }
		{ entry $w.fileName {Out File} {What .pv file to write} }
	"
	pack $w.params -in $w.main -fill x -padx 0.5m -pady 0.5m

	$w.pvDir configure -text $const(pvDir)

	button $w.reScan -text "ReScan"
	pack $w.reScan -in $w.main -fill x -padx 0.5m -pady 0.5m

	button $w.write -text "Write"
	pack $w.write -in $w.main -fill x -padx 0.5m -pady 0.5m

	return $status
}

proc cycle:subRun { mech } {
	global parms

	set status 0

	set w .w$parms(winNo)
	incr parms(winNo)
	toplevel $w

	if { !$status } {
		set status [cycle:win $w]
	}

	if { !$status } {
		set status [cycle:connect $w $mech]
	}

	return $status 
}

proc cycle:run { w t c m } {
	set status 0

	util:init $t$c$m

	if { !$status } {
		set status [cycle:win $w]
	}

	if { !$status } {
		set status [cycle:connect $w $t$c$m]
	}

	return $status
}
