#! /bin/echo pos.tcl should not be run directly from the command line

# $Id: pos.tcl,v 1.2 2009/05/27 19:34:52 fkraemer Exp $

set pos(nrows) 15

set help(pos) \
	{Help not yet written}

proc pos:reScan { w mech } {
	global ca pos

	set status 0

	$w.reScan configure -state disabled
	$w.write configure -state disabled

	if { !$status } {
		set status [ca:readVars ${mech}Busy.VAL]
	}

	if { !$status } {
		if { $ca(${mech}Busy.VAL) } {
			tk_dialog .dialog {Busy} {Mechanism is busy} warning 1 Ok
			set status 1
		}
	}

	#
	# We always want to be in User mode, because these values will
	# always be used in User mode.
	#

	if { !$status } {
		set status [ca:readVars ${mech}Hallstep.RAW]
		set oldRaw $ca(${mech}Hallstep.RAW)
	}

	if { !$status } {
		set ca(${mech}Hallstep.RAW) User
		set status [ca:writeVars ${mech}Hallstep.RAW]
	}

	foreach def $pos($mech,cfgList) {
		if { !$status } {
			update
			set status [pos:move $mech $def]
		}
	}

	if { !$status } {
		set ca(${mech}Hallstep.RAW) $oldRaw 
		set status [ca:writeVars ${mech}Hallstep.RAW]
	}

	$w.reScan configure -state normal
	$w.write configure -state normal
}

proc pos:move { mech name } {
	global ca pos

	set status 0

	if { !$status } {
		set ca(${mech}MoveTo.VAL) $pos($mech,pos,$name)
		set status [ca:writeVars ${mech}MoveTo.VAL]
	}

	after 50	

	while { !$status } {
		set status [ca:readVars ${mech}Busy.VAL]

		if { !$status && !$ca(${mech}Busy.VAL) } {
			break
		}

		after 50	
	}

	after 50	

	if { !$status } {
		set status [ca:readVars ${mech}Done.VAL]

		if { !$status && $ca(${mech}Done.VAL) != 0 } {
			set cancel [tk_dialog .dialog {Error} \
				"Move to \"$name\" failed" error  1 Ok]
			set status 1
		}
	}

	if { !$status } {
		set status [ca:readVars "
			${mech}Hallstep.RVLP
			${mech}Hallstep.RVLB
		"]
	}

	if { !$status } {
		set pos($mech,valp,$name) $ca(${mech}Hallstep.RVLP)
		set pos($mech,valb,$name) $ca(${mech}Hallstep.RVLB)
	}

	return $status
}

proc pos:write { w mech } {
	global ca parms pos env

	set cancel [tk_dialog .dialog {Confirm} \
		"Generate $parms($mech,outFile)" question  1 Ok Cancel]

	if { $cancel } {
		return
	}

	set fd [open $parms($mech,outFile) w]
	set base "\$(top)[string range $mech [string length $env(NIRI_PREFIX)] end]"

	puts -nonewline $fd {# $}; puts $fd {Id$}
	puts $fd "# $ca(${mech}Label.VAL)"
	puts $fd "# $mech"
	puts $fd {}
	puts $fd {# -- Do not edit by hand --}
	puts $fd {# This file was automatically generated by pos.tcl, on}
	puts $fd "# [exec date]"
	puts $fd {}

	foreach def $pos($mech,cfgList) {
		puts -nonewline $fd [format "%-5s 4 "   $def]
		puts -nonewline $fd [format "%7d "      $pos($mech,pos,$def)]
		puts -nonewline $fd [format "%4d "     -$pos($mech,ptol,$def)]
		puts -nonewline $fd [format "%3d "      $pos($mech,ptol,$def)]
		puts -nonewline $fd [format "%6.3f "    $pos($mech,valp,$def)]
		puts -nonewline $fd [format "%6.3f "   -$pos($mech,tol,$def)]
		puts -nonewline $fd [format "%6.3f "    $pos($mech,tol,$def)]
		puts -nonewline $fd [format "%6.3f "    $pos($mech,valb,$def)]
		puts -nonewline $fd [format "%6.3f "   -$pos($mech,tol,$def)]
		puts -nonewline $fd [format "%6.3f "    $pos($mech,tol,$def)]
		puts            $fd [format "%6.3f 0 0" $pos($mech,tol,$def)]
	}

	close $fd
}

proc pos:connect { w mech } {
	global parms const ca pos

	set status [ca:connect "
		${mech}Busy.VAL
		${mech}Done.VAL
		${mech}Hallstep.CSET
		${mech}Op.VAL
		${mech}Label.VAL
		${mech}Ident.VAL
		${mech}Subdir.VAL
		${mech}MoveTo.VAL
		${mech}Hallstep.RVLP
		${mech}Hallstep.RVLB
		${mech}Hallstep.RAW
	"]

	set parms($mech,ident) $ca(${mech}Ident.VAL)
	set parms($mech,dir) $ca(${mech}Subdir.VAL)
	set parms($mech,outFile) $const(lutDir)/$parms($mech,dir)/$parms($mech,ident).lut
	set parms($w,mech) $mech

	if { $w == {} } {
		wm title . "$ca(${mech}Label.VAL) -- Position Tool"
	} else {
		wm title $w "$ca(${mech}Label.VAL) -- Position Tool"
	}

	$w.mech configure -text $mech
	$w.reScan configure -command "pos:reScan {$w} {$mech}"
	$w.write configure -command "pos:write {$w} {$mech}"
	$w.fileName configure -textvar parms($mech,outFile)
	$w.subdir configure -text $ca(${mech}Subdir.VAL)
	$w.ident configure -text $ca(${mech}Ident.VAL)

	foreach line $const(defs,$parms($mech,ident)) {
		lappend pos($mech,cfgList) [lindex $line 0]
		set pos($mech,pos,[lindex $line 0]) [lindex $line 1] 
		set pos($mech,ptol,[lindex $line 0]) [lindex $line 2] 
		set pos($mech,tol,[lindex $line 0]) [lindex $line 3] 
	}

	set row 1
	foreach def $pos($mech,cfgList) {
		$w.def$row configure -text $def
		$w.pos$row configure -textvar pos($mech,pos,$def)
		$w.ptol$row configure -textvar pos($mech,ptol,$def)
		$w.tol$row configure -textvar pos($mech,tol,$def)
		$w.valp$row configure -textvar pos($mech,valp,$def)
		$w.valb$row configure -textvar pos($mech,valb,$def)
		incr row
	}

	return $status
}

proc pos:win { w } {
	global const pos

	set status 0

	util:win $w pos

	frame $w.results -border 0.5m -relief groove
	pack $w.results -in $w.main -padx 0.5m -pady 0.5m -fill x

	util:table $w.params 50 "
		{ label $w.mech {Mech} {The EPICS prefix} }
		{ label $w.lutDir {.lut base directory} \
			{Default base directory for .lut files} }
		{ label $w.subdir {.lut Subdirectory} \
			{Current subdirectory for .lut file} }
		{ label $w.ident {Ident} {Base name for .lut file} }
		{ entry $w.fileName {Out File} {What .lut file to write} }
	"
	pack $w.params -in $w.main -fill x -padx 0.5m -pady 0.5m

	$w.lutDir configure -text $const(lutDir)

	button $w.reScan -text "ReScan"
	pack $w.reScan -in $w.main -fill x -padx 0.5m -pady 0.5m

	button $w.write -text "Write"
	pack $w.write -in $w.main -fill x -padx 0.5m -pady 0.5m

	label $w.def0
	blt_table $w.results $w.def0 0,0 -fill x
	label $w.pos0 -anchor c -text {count}
	blt_table $w.results $w.pos0 0,1 -fill x
	label $w.ptol0 -anchor c -text {count tol}
	blt_table $w.results $w.ptol0 0,2 -fill x
	label $w.tol0 -anchor c -text {val tol}
	blt_table $w.results $w.tol0 0,3 -fill x
	label $w.valp0 -anchor c -text {sens (p)}
	blt_table $w.results $w.valp0 0,4 -fill x
	label $w.valb0 -anchor c -text {sens (b)}
	blt_table $w.results $w.valb0 0,5 -fill x

	for {set i 1} {$i <= $pos(nrows)} {incr i} {
		label $w.def$i -anchor e
		blt_table $w.results $w.def$i $i,0 -fill x
		label $w.pos$i -anchor e -width 12 -relief sunken -border 0.6m -bg gray
		blt_table $w.results $w.pos$i $i,1 -fill x
		label $w.ptol$i -anchor e -width 12 -relief sunken -border 0.6m -bg gray
		blt_table $w.results $w.ptol$i $i,2 -fill x
		label $w.tol$i -anchor e -width 12 -relief sunken -border 0.6m -bg gray
		blt_table $w.results $w.tol$i $i,3 -fill x
		label $w.valp$i -anchor e -width 12 -relief sunken -border 0.6m -bg gray
		blt_table $w.results $w.valp$i $i,4 -fill x
		label $w.valb$i -anchor e -width 12 -relief sunken -border 0.6m -bg gray
		blt_table $w.results $w.valb$i $i,5 -fill x
	}

	return $status
}

proc pos:subRun { mech } {
	global parms const

	set status 0

	set w .w$parms(winNo)
	incr parms(winNo)
	toplevel $w

	if { !$status } {
		set status [pos:win $w]
	}

	if { !$status } {
		set status [pos:connect $w $mech]
	}

	return $status 
}

proc pos:run { w t c m } {
	global const

	set status 0

	util:init $t$c$m

	source $const(cfgFile)

	if { !$status } {
		set status [pos:win $w]
	}

	if { !$status } {
		set status [pos:connect $w $t$c$m]
	}

	return $status
}
