#+
#  AcqCamInst.itcl
#
#  This is the AcqCam specific version of the instrument class.
#
#  D Terrett 23 November 2001
#
#  Copyright CCLRC
#+

package require AcqCam 1.0

itcl::class AcqCamInst {
   inherit GenericInst
   public {
      constructor {} {}
      destructor {}
      method description {}
      method observe {label whendone}
      method setup {whendone}
   }
   private {
      method obsoktest {}
      variable setupaction
   }
}

# Create the principle system objects for AcqCam.

namespace eval AcqCamInst {
   global Flags
   seq::PrincipalSystem ACQCAM acqcam::apply -debug $Flags(traceinst)  \
         -simulate $Flags(simac) -delay 0
}

itcl::body AcqCamInst::constructor {} {

# Set the public variables that are used to position the science fold. The
# acquistion camera is a special case because it is always on port 1 and 
# doesn't appear in the list of a&g port names. The name "ac" is recogised
# by the RealTcs object.
   set agname ac
   set sfname ac

# Set the protected variables used by the generic instrument methods to the
# name of the principle system used by the observe action and the prefix
# for the sequence commands.
   set psys AcqCamInst::ACQCAM
   set prefix acqcam

# Create the instrument configuration object. The fully qualified namespace 
# has to be used so that the object is accessible outside this class. The
# AcqCam object is configured from the parameter settings in the sequence
# file by the Sequence object as it is created.
   set instobj [namespace current]::[AcqCam::AcqCam #auto]

# Configure the object with the parameters that are never changed.
   $instobj configure -dir . -file hrwfs.fits -simfile NONE \
         -dhsstream hrwfsScience -dhsoption 1 -output 1 -dhsoption 3

# Create the action for configuring the instrument. The apply record remains
# BUSY until the configuration is complete so this action does not need to
# have -waitvar or -oktest options set. Completion of the action is handled
# by methods inhierited from GenericInst.
   set setupaction [seq::Action #auto $psys]
   $setupaction configure -onstart [itcl::code $instobj apply] \
         -onerror [itcl::code $this setuperror] \
         -ontimeout [itcl::code $this setuptimeout] \
         -onok [itcl::code $this setupok]

# Create the actions for observing and continuing. This actions needs to be 
# accessible to GenericInst so that it can restart an observation after a
# pause.
   set obsaction [namespace current]::[seq::Action #auto $psys]
   $obsaction configure -onerror [itcl::code $this obserror] \
         -ontimeout [itcl::code $this obstimeout] \
         -onok [itcl::code $this obsok] \
         -oktest [itcl::code $this obsoktest] \
         -waitvar AcqCam::observeStatus

# The timeout on the continue action is set by GenericInst.
   set contaction [namespace current]::[seq::Action #auto $psys]
   $contaction configure -onerror [itcl::code $this obserror] \
         -onok [itcl::code $this obsok] \
         -oktest [itcl::code $this obsoktest] \
         -waitvar AcqCam::observeStatus
   $contaction set acqcam::continue dummy MARK
}

itcl::body AcqCamInst::destructor {} {
   itcl::delete object $obsaction
   itcl::delete object $contaction
   itcl::delete object $setupaction
   itcl::delete object $instobj
}

itcl::body AcqCamInst::observe {label whendone} {

# Sends an "observe" sequence command to the instrument with the DHS
# label set to $label and calls the $whendone script when the exposure 
# has finished.

#  Only proceed if an observe is not already in progress.
   if { $GenericInst::observing } {
      lappend Sequence::errormsg "Error sending observe: observe already in\
            progress"
      return 0
   } else {

# Save the done proc.
      set doneproc $whendone

# Set the data label.
      $obsaction set ${prefix}::observe label $label

# Set the action timeout.
      
      set timeOut [expr [$instobj cget -exposureTime] + 30]
      set timeOut [expr { int($timeOut) }]

      $obsaction configure -timeout $timeOut

# Post the observe command.
      if { [catch {$obsaction start} msg] } {
         lappend ::Sequence::errormsg "Error starting exposure: $msg"
         return 0
      } else {

# Record that an observe is in progress and the time that it was started.
         set GenericInst::observing 1
         set GenericInst::starttime [clock seconds]
         return 1
      }
   }
}
itcl::body AcqCamInst::obsoktest {} {
   return [string equal IDLE [sa acqcam::status get observe]]
}

itcl::body AcqCamInst::setup {whendone} {

# Configures the instrument ready to take an exposure.
#  Only proceed if an observe is not in progress.
   if { $GenericInst::observing } {
      lappend Sequence::errormsg "Error configuring instrument: observe\
            already in progress"
      return 0
   } else {

# Save the done proc.
      set doneproc $whendone

# Start the setup action.
      if { [catch {$setupaction start} msg] } {
         lappend ::Sequence::errormsg \
               "Error configuring the acquisition camera: $msg"
         return 0
      } else {
         return 1
      }
   }
}

itcl::body AcqCamInst::description {} {

# Returns the current filter name and exposure time.
   return "[$instobj cget -clfilter] [$instobj cget -exposureTime]s"
}
