#+
#  GenericInst.itcl
#
#  A GenericInst object provides a base class for a specific instrument
#  object.
#
#  The derived class must set the values of the following protected variables:
#
#     psys - The name of the principle system object for the instrument.
#
#     prefix - The prefix for the command senders for the instrument.
#
#     obsaction - The name of the action that starts the observe
#
#     contaction - The name of the action that continues an observation.
#
#  and these public variables.
#
#     agname - The instrument name as it appears in the A&G port label
#              records.
#
#     sfname - The instrument name as used to construct the science fold
#              position. This is normally fixed but can depend on the
#              configuration of the instrument in some cases.
#
#  and provide implementations of the observe and setup methods. These must
#  store the name of the "whendone" procedure in the protected variable
#  'doneproc'.
#
#  It must also set the class common variables GenericInst::observing to 1
#  when an observation is started and GenericInst::startime to the time
#  (as returned by [clock seconds]) at which the observation was started.
#
#  The method "description" can be overriden to return a text string that
#  describes the instrument configuration for the step (a filter name for
#  example).
#
#  D Terrett 12 December 2001
#
#  Copyright CCLRC
#+

itcl::class GenericInst {
   public {
      constructor {} {}
      destructor {}
      method stop {}
      method abort {}
      method continue {{whendone ""}}
      method description {} {return ""}
      method endobserve {}
      method setup {whendone} {}
      method observe {label whendone} {}
      method pause {}
      variable agname ""
      variable sfname ""
      variable dhsobj ""
      variable instobj
      variable object
   }
   protected {
      method obserror {args}
      method obsok {}
      method obstimeout {}
      method setuperror {args}
      method setupok {}
      method setuptimeout {}
      common observing 0
      common starttime
      variable contaction
      variable doneproc
      variable obsaction
      variable prefix
      variable psys
   }
}

itcl::body GenericInst::abort {} {

# Cancel any currently active actions for this instrument.
   if { $observing } {
      $psys cancel ""

# Send an "abort" sequence command to the instrument.
      cs ${prefix}::abort set dummy MARK
      if { [catch {cs ${prefix}::abort post} msg] } {
         lappend ::Sequence::errormsg "Error aborting exposure: $msg"
         return 0
      }

# Invoke the done procedure with a failure status.
      lappend ::Sequence::errormsg "observation was aborted by user"
      after idle $doneproc 0
      set observing 0
      return 1
   } else {
      lappend Sequence::errormsg "Error aborting exposure: observe not in\
            progress"
      return 0
   }
}

itcl::body GenericInst::continue {{whendone ""}} {

if {![string is space $whendone]} {
   set doneproc $whendone
   }

# Sends a "continue" sequence command to the instrument.
   if { $observing } {
      $contaction start
      return 1
   } else {
      lappend Sequence::errormsg "Error continuing exposure: observe not in\
            progress"
      return 0
   }
}

itcl::body GenericInst::endobserve {} {

# Sends an "endObserve" sequence command to the instrument.
     cs ${prefix}::endObserve set dummy MARK
     if { [catch {cs ${prefix}::endObserve post} msg] } {
        lappend ::Sequence::errormsg "Error sending endObserve to instrument:\
              $msg"
        return 0
    }
      return 1
}

itcl::body GenericInst::pause {} {

# Sends a "pause" sequence command to the instrument.
   if { $observing } {
      cs ${prefix}::pause set dummy MARK
      if { [catch {cs ${prefix}::pause post} msg] } {
         lappend ::Sequence::errormsg "Error pausing exposure: $msg"
         return 0
      }

# Cancel the current action.
      $psys cancel ""

# Calculate a timeout for the continue action. This is the timeout on
# the observe action minus the time that the exposure has been running.
      set newtimeout [expr { [$obsaction cget -timeout] - \
            ( $starttime - [clock seconds] ) } ]
      $contaction configure -timeout $newtimeout
      return 1
   } else {
      lappend Sequence::errormsg "Error pausing exposure: observe not in\
            progress"
      return 0
   }
} 

itcl::body GenericInst::setupok {} {

# Called when setting up the instrument completes successfully.
   $doneproc 1
}

itcl::body GenericInst::setuperror { args } {

# Called when setting up the instrument fails.
   lappend ::Sequence::errormsg "Instrument setup ended in error"
   if { [llength $args] } {
      eval lappend ::Sequence::errormsg $args
      }
   $doneproc 0
}

itcl::body GenericInst::setuptimeout {} {

# Called when setting up the instrument fails.
   lappend ::Sequence::errormsg "Instrument setup timed out"
   $doneproc 0
}

itcl::body GenericInst::obsok {} {

# Called when an observe completes sucessfully.
   set observing 0
   $doneproc 1
}

itcl::body GenericInst::obserror {args} {

# Called when an observe fails.
   lappend ::Sequence::errormsg "Observe ended in error"
   if { [llength $args] } {
      eval lappend ::Sequence::errormsg $args
      }
   set observing 0
   $doneproc 0
}

itcl::body GenericInst::obstimeout {} {

# Called when an observe times out.
   lappend ::Sequence::errormsg "Observe timed out"
   set observing 0
   $doneproc 0
}

itcl::body GenericInst::stop {} {

   if { $observing } {
# Send a "stop" sequence command to the instrument.
      cs ${prefix}::stop set dummy MARK
      if { [catch {cs ${prefix}::stop post} msg] } {
         lappend ::Sequence::errormsg "Error stopping exposure: $msg"
         return 0
      }
# doneproc will be invoked when the stopped observe returns IDLE
# set observing to 0 to avoid repeated STOP
      set observing 0
      return 1
   } else {
      lappend Sequence::errormsg "Error stopping exposure: observe not in\
            progress"
      return 0
   }
}

