#+
#  HeaderInfo <- itk::Widget
#
#  A ComponentControl widget with widgets for the user-entries needed to fill
#  missing headers
#
#  Methods:
#
#  D Terrett, M Bec 29 November 2001
#
#  Copyright CCLRC, Gemini
#+

itcl::class HeaderInfo {
   inherit itk::Widget

   constructor args {}
   private {
      method setdatalabel {}
      common objectCAL [list Bias Dark GCALflat CuAr Ar Kr ThAr Twilight Domeflat \
      Maskimage Slitimage Pinhole]
      common objectENG [ list Hartmann Pupil]
      }

   public {
      variable site
      }
}

itk::usual HeaderInfo {
   keep -borderwidth -cursor -highlightthickness -insertborderwidth \
         -insertofftime -insertontime -insertwidth -labelfont -popupcursor \
         -selectborderwidth -textfont
}

itcl::body HeaderInfo::constructor {args} {

   set w $itk_interior

# Frame
   itk_component add frame {
      iwidgets::Labeledframe $w.frame -labelpos nw \
            -labeltext "Header Information" -ipadx 5 -ipady 5
   }
   pack $itk_component(frame) -fill x -expand 1
   set w [$itk_component(frame) childsite]
	
# DHS label
   itk_component add dhslab {
      label $w.dhslabel -text "DHS label" -anchor w
   }
   itk_component add dhs {
      iwidgets::entryfield $w.dhs -justify right -state disabled \
            -textvariable dhshdr::dhslabel
   }

# data label
   itk_component add datalablab {
      label $w.datalablab -text "Data Label" -anchor w
   }
   itk_component add datalab {
      frame $w.datalab
   }
   itk_component add gemprgid {
      iwidgets::entryfield $w.datalab.gemprgid -justify right \
            -textvariable dhshdr::gemprgid -width 16
   }
   itk_component add dash1 {
      label $w.datalab.dash1 -text "-" -width 1
   }
   itk_component add obsid {
      iwidgets::entryfield $w.datalab.obsid -width 4 -justify center \
            -textvariable dhshdr::obsid
   }
   itk_component add dash2 {
      label $w.datalab.dash2 -text "-" -width 1
   }
   itk_component add datalabel {
      iwidgets::entryfield $w.datalab.datalabel -width 6 -justify center \
            -validate numeric -textvariable dhshdr::datalabel
   }
   pack $itk_component(gemprgid) -side left -expand 1 -fill x
   pack $itk_component(dash1) $itk_component(obsid) $itk_component(dash2) \
         $itk_component(datalabel) -side left
		
# obstype
   itk_component add obstypelab {
      label $w.obstypelab -text "Observation Type" -anchor w
   }
   itk_component add obstype {
      iwidgets::combobox $w.obstype -completion 0 -textvariable dhshdr::obstype
   }
   $itk_component(obstype) insert list end \
         OBJECT SKY FLAT ARC DARK BIAS ZERO ENG TEST UNDEFINED
   [$itk_component(obstype) component entry] config -justify right

# object
   itk_component add objectlab {
      label $w.objectlab -text "Object" -anchor w
   }
   itk_component add object {
      iwidgets::combobox $w.object -completion 0 -textvariable dhshdr::object \
            -selectioncommand [itcl::code $this setdatalabel]
   }
   eval $itk_component(object) insert list end \
         [lsort [eval list $objectCAL $objectENG]] 
         
   [$itk_component(object) component entry] config -justify right

# observer
   itk_component add observerlab {
      label $w.observerlab -text "Observer" -anchor w
   }
   itk_component add observer {
      iwidgets::entryfield $w.observer -justify right \
            -textvariable dhshdr::observer
   }
	
# ssa
   itk_component add ssalab {
      label $w.ssalab -text "SSA" -anchor w
   }
   itk_component add ssa {
      iwidgets::entryfield $w.ssa -justify right -textvariable dhshdr::ssa
   }

# rawiq
   itk_component add rawiqlab {
      label $w.rawiqlab -text "Raw Image Quality" -anchor w
   }
   itk_component add rawiq {
      iwidgets::combobox $w.rawiq -completion 0 -textvariable dhshdr::rawiq
   }
   $itk_component(rawiq) insert list end Any 80-percentile 50-percentile \
         20-percentile
   set  dhshdr::rawiq Any       
   [$itk_component(rawiq) component entry] config -justify right
	
# rawcc
   itk_component add rawcclab {
      label $w.rawcclab -text "Raw Cloud Cover" -anchor w
   }
   itk_component add rawcc {
      iwidgets::combobox $w.rawcc -completion 0 -textvariable dhshdr::rawcc
   }
   $itk_component(rawcc) insert list end Any 90-percentile 70-percentile \
         50-percentile 20-percentile
   set dhshdr::rawcc Any
   [$itk_component(rawcc) component entry] config -justify right

# rawwv
   itk_component add rawwvlab {
      label $w.rawwvlab -text "Raw Water Vapour/Transparency" -anchor w
   }
   itk_component add rawwv {
      iwidgets::combobox $w.rawwv -completion 0 -textvariable dhshdr::rawwv
   }
   $itk_component(rawwv) insert list end Any 80-percentile 50-percentile \
         20-percentile
   set dhshdr::rawwv Any
   [$itk_component(rawwv) component entry] config -justify right

# rawbg
   itk_component add rawbglab {
      label $w.rawbglab -text "Raw Background" -anchor w
   }
   itk_component add rawbg {
      iwidgets::combobox $w.rawbg -completion 0 -textvariable dhshdr::rawbg
   }
   $itk_component(rawbg) insert list end Any 80-percentile 50-percentile \
         20-percentile
   set dhshdr::rawbg Any
   [$itk_component(rawbg) component entry] config -justify right

# rawpireq
   itk_component add rawpireqlab {
      label $w.rawpireqlab -text "PI Requirements met" -anchor w
   }
   itk_component add rawpireq {
      iwidgets::combobox $w.rawpireq -completion 0 -textvariable dhshdr::rawpireq
   }
   $itk_component(rawpireq) insert list end YES NO
   set dhshdr::rawpireq YES
   [$itk_component(rawpireq) component entry] config -justify right

# rawgemqa
   itk_component add rawgemqalab {
      label $w.rawgemqalab -text "Gemini Quality Assessment" -anchor w
   }
   itk_component add rawgemqa {
      iwidgets::combobox $w.rawgemqa -completion 0 -textvariable dhshdr::rawgemqa
   }
   $itk_component(rawgemqa) insert list end USABLE BAD
   set dhshdr::rawgemqa USABLE
   [$itk_component(rawgemqa) component entry] config -justify right


   grid $itk_component(dhslab) $itk_component(dhs) -sticky ew
   grid $itk_component(datalablab) $itk_component(datalab) -sticky ew
   grid $itk_component(obstypelab) $itk_component(obstype) -sticky ew
   grid $itk_component(objectlab) $itk_component(object) -sticky ew
   grid $itk_component(observerlab) $itk_component(observer) -sticky ew
   grid $itk_component(ssalab) $itk_component(ssa) -sticky ew
   grid $itk_component(rawiqlab) $itk_component(rawiq) -sticky ew
   grid $itk_component(rawcclab) $itk_component(rawcc) -sticky ew
   grid $itk_component(rawwvlab) $itk_component(rawwv) -sticky ew
   grid $itk_component(rawbglab) $itk_component(rawbg) -sticky ew
   grid $itk_component(rawpireqlab) $itk_component(rawpireq) -sticky ew
   grid $itk_component(rawgemqalab) $itk_component(rawgemqa) -sticky ew
   grid columnconfigure $w 0 -weight 0
   grid columnconfigure $w 1 -weight 1

   eval itk_initialize $args
}

itcl::body HeaderInfo::setdatalabel {} {
   if { [lsearch -exact $objectENG [$itk_component(object) get]] != -1 } {
      $itk_component(gemprgid) delete 0 end
      $itk_component(gemprgid) insert 0 $site-ENG[clock format [clock seconds] -gmt 1 -format  "%Y%m%d"]
      }\
   elseif { [lsearch -exact $objectCAL [$itk_component(object) get]] != -1 } {
      $itk_component(gemprgid) delete 0 end
      $itk_component(gemprgid) insert 0 $site-CAL[clock format [clock seconds] -gmt 1 -format  "%Y%m%d"]
      }
   }

itcl::configbody HeaderInfo::site {
   switch $site {
      MK - GN {
         set site GN
         }
      CP - GS {
         set site GS
         }
      default {
         set site XXX
         }
      }
   }
