#+
#  NiriInst.itcl
#
#  This is the Niri specific version of the instrument class.
#
#  D Terrett 6 February 2002
#
#  Copyright CCLRC
#+

package require Niri
package require niriDhshdr

itcl::class NiriInst {
   inherit GenericInst
   public {
      constructor {} {}
      destructor {}
      method description {}
      method endobserve {}
      method observe {label whendone}
      method setup {whendone}
   }
   private {
      method obsoktest {}
      method setupDC {}
      method setsfname {n1 n2 op}
      variable setupISaction
      variable setupDCaction
   }
}

# Create the principle system objects for Niri.

namespace eval NiriInst {
   global Flags
   seq::PrincipalSystem NIRI niri::apply -debug $Flags(traceinst)  \
         -simulate 1 -delay 1
   seq::PrincipalSystem NIRIDC niri::dcapply -debug $Flags(traceinst) \
         -simulate $Flags(simniri) -delay 1
}

itcl::body NiriInst::constructor {} {

# Set the public variables used to determine the science fold position.
   set agname NIRI
   set sfname niri

# Set the protected variables used by the generic instrument methods to the
# name of the principle system used by the observe action and the prefix
# for the sequence commands.
   set psys NiriInst::NIRIDC
   set prefix niri

# Create the instrument configuration object. The fully qualified namespace 
# has to be used so that the object is accessible outside this class. The
# Niri object is configured from the parameter settings in the sequence
# file by the Sequence object as it is created.
   set instobj [namespace current]::[Niri::Niri #auto]

# Create the actions for configuring the instrument. The apply record remains
# BUSY until the configuration is complete so these actions do not need to
# have -waitvar or -oktest options set. Completion of the DC action is handled
# by methods inhierited from GenericInst.
   set setupISaction [seq::Action #auto NiriInst::NIRI]
   $setupISaction configure\
         -onerror [itcl::code $this setuperror] \
         -ontimeout [itcl::code $this setuptimeout] \
         -onok [itcl::code $this setupDC] \
         -timeout 180

   set setupDCaction [seq::Action #auto NiriInst::NIRIDC]
   $setupDCaction configure\
         -onerror [itcl::code $this setuperror] \
         -ontimeout [itcl::code $this setuptimeout] \
         -onok [itcl::code $this setupok]
   $setupDCaction connect niri::dcconfig

$instobj configDCaction [namespace current]::$setupDCaction
$instobj configCCaction [namespace current]::$setupISaction


# Create the actions for observing and continuing. This actions needs to be 
# accessible to GenericInst so that it can restart an observation after a
# pause.
   set obsaction [namespace current]::[seq::Action #auto NiriInst::NIRIDC]
   $obsaction configure -onerror [itcl::code $this obserror] \
         -ontimeout [itcl::code $this obstimeout] \
         -onok [itcl::code $this obsok] \
         -oktest [itcl::code $this obsoktest] \
         -waitvar niri::observeDCStatus

# The timeout on the continue action is set by GenericInst.
   set contaction [namespace current]::[seq::Action #auto NiriInst::NIRIDC]
   $contaction configure -onerror [itcl::code $this obserror] \
         -onok [itcl::code $this obsok] \
         -oktest [itcl::code $this obsoktest] \
         -waitvar niri::observeDCStatus
   $contaction set niri::continue dummy MARK

# Set up a read trace on sfname that modified its value according to the
# niri object's -camera option.
   trace variable sfname r [itcl::code $this setsfname]
}

itcl::body NiriInst::destructor {} {
   itcl::delete object $obsaction
   itcl::delete object $contaction
   itcl::delete object $setupISaction
   itcl::delete object $setupDCaction
   itcl::delete object $instobj
}

itcl::body NiriInst::endobserve {} {
# not needed
      return 1
}

itcl::body NiriInst::observe {label whendone} {

# Sends an "observe" sequence command to the instrument with the DHS
# label set to $label and calls the $whendone script when the exposure 
# has finished.

#  Only proceed if an observe is not already in progress.
   if { $GenericInst::observing } {
      lappend Sequence::errormsg "Error sending observe: observe already in\
            progress"
      return 0
   } else {

# Save the done proc.
      set doneproc $whendone

# Set the data label.
      $obsaction set ${prefix}::observe label $label

# Set the action timeout.
      $obsaction configure -timeout [$instobj calcTimeout]

# Post the observe command.
      $obsaction start
# Record that an observe is in progress and the time that it was started.
      set GenericInst::observing 1
      set GenericInst::starttime [clock seconds]
      return 1
   }
}
itcl::body NiriInst::obsoktest {} {
   return [string equal IDLE [sa niri::dcstatus get observe]]
}

itcl::body NiriInst::setup {whendone} {

# Configures the instrument ready to take an exposure.

#  Only proceed if an observe is not in progress.
   if { $GenericInst::observing } {
      lappend Sequence::errormsg "Error configuring instrument: observe\
            already in progress"
      return 0
   } else {

# Save the done proc.
      set doneproc $whendone

# Start the instrument sequencer setup action.
      $instobj apply components
      return 1
   }
}

itcl::body NiriInst::setupDC {} {

# Start the detector controller setup action.
   $instobj apply detector
}

itcl::body NiriInst::description {} {

# Returns the current filter name and exposure time.
   return "[$instobj cget -filter]\
      [$instobj cget -coadds]x[$instobj cget -exposureTime]s"
}

itcl::body NiriInst::setsfname {n1 n2 op} {

   switch [$instobj cget -camera] {
      "f/6" {
         set sfname nirif6p
      }
      "f/14" {
         set sfname nirif14p
      }
      "f/32" {
         set sfname nirif32p
      }
      default {
         switch [sa niri::status get camera] {
            "f6" {
               set sfname niri6p
            }
            "f13.9" {
               set sfname nirif14p
            }
            "f32" {
               set sfname nirif32p
            }
            default {
               error "can't figure out Niri camera"
            }
         }
      }
   }
}
