#+
#  NirsInst.itcl
#
#  This is the NIRS specific version of the instrument class.
#
#  D Terrett 30 November 2001
#
#  Copyright CCLRC
#+

package require Nirs
package require nirsDhshdr

itcl::class NirsInst {
   inherit GenericInst
   public {
      constructor {} {}
      destructor {}
      method description {}
      method observe {label whendone}
      method setup {whendone}
      }
   private {
      method obsoktest {}
      method setupDC {}
      variable setupISaction
      variable setupDCaction
   }
}

# Create the principle system objects for Nirs.

namespace eval NirsInst {
   global Flags
   global env
   seq::PrincipalSystem NIRS nirs::apply -debug $Flags(traceinst)  \
         -simulate $Flags(simnirs) -delay 1
   seq::PrincipalSystem NIRSDC nirs::dcapply -debug $Flags(traceinst) \
         -simulate $Flags(simnirs) -delay 1
}

itcl::body NirsInst::constructor {} {

# Set the public variables used to determine the science fold position.
   set agname NIRS
   set sfname nirs

# Set the protected variables used by the generic instrument methods to the
# name of the principle system used by the observe action and the prefix
# for the sequence commands.
   set psys NirsInst::NIRSDC
   set prefix nirs

# Create the instrument configuration object. The fully qualified namespace 
# has to be used so that the object is accessible outside this class. The
# Nirs object is configured from the parameter settings in the sequence
# file by the Sequence object as it is created.
   set instobj [namespace current]::[Nirs::Nirs #auto]

# Create the actions for configuring the instrument. The apply record remains
# BUSY until the configuration is complete so these actions do not need to
# have -waitvar or -oktest options set. Completion of the DC action is handled
# by methods inhierited from GenericInst.
   set setupISaction [seq::Action #auto NirsInst::NIRS]
   $setupISaction configure\
         -onerror [itcl::code $this setuperror] \
         -ontimeout [itcl::code $this setuptimeout] \
         -onok [itcl::code $this setupDC] \
         -timeout 600

   set setupDCaction [seq::Action #auto NirsInst::NIRSDC]
   $setupDCaction configure\
         -onerror [itcl::code $this setuperror] \
         -ontimeout [itcl::code $this setuptimeout] \
         -onok [itcl::code $this setupok]
   $setupDCaction connect nirs::dcconfig

$instobj configDCaction [namespace current]::$setupDCaction
$instobj configCCaction [namespace current]::$setupISaction


# Create the actions for observing and continuing. This actions needs to be 
# accessible to GenericInst so that it can restart an observation after a
# pause.
   set obsaction [namespace current]::[seq::Action #auto NirsInst::NIRSDC]
   $obsaction configure -onerror [itcl::code $this obserror] \
         -ontimeout [itcl::code $this obstimeout] \
         -onok [itcl::code $this obsok] \
         -oktest [itcl::code $this obsoktest] \
         -waitvar nirs::observeDCStatus

# The timeout on the continue action is set by GenericInst.
   set contaction [namespace current]::[seq::Action #auto NirsInst::NIRSDC]
   $contaction configure -onerror [itcl::code $this obserror] \
         -onok [itcl::code $this obsok] \
         -oktest [itcl::code $this obsoktest] \
         -waitvar nirs::observeDCStatus
   $contaction set nirs::continue dummy MARK
}

itcl::body NirsInst::destructor {} {
   itcl::delete object $obsaction
   itcl::delete object $contaction
   itcl::delete object $setupISaction
   itcl::delete object $setupDCaction
   itcl::delete object $instobj
}

itcl::body NirsInst::observe {label whendone} {

# Sends an "observe" sequence command to the instrument with the DHS
# label set to $label and calls the $whendone script when the exposure 
# has finished.

#  Only proceed if an observe is not already in progress.
   if { $GenericInst::observing } {
      lappend Sequence::errormsg "Error sending observe: observe already in\
            progress"
      return 0
   } else {

# Save the done proc.
      set doneproc $whendone

# Set the data label.
      $obsaction set ${prefix}::observe label $label

# Set the action timeout to the exposure time plus 5 minutes.
      $obsaction configure -timeout [$instobj calcTimeout]

# Post the observe command.
      $obsaction start

# Record that an observe is in progress and the time that it was started.
      set GenericInst::observing 1
      set GenericInst::starttime [clock seconds]
      return 1
   }
}

itcl::body NirsInst::obsoktest {} {
   return [string equal IDLE [sa nirs::dcstatus get observe]]
}

itcl::body NirsInst::setup {whendone} {

# Configures the instrument ready to take an exposure.

#  Only proceed if an observe is not in progress.
   if { $GenericInst::observing } {
      lappend Sequence::errormsg "Error configuring instrument: observe\
            already in progress"
      return 0
   } else {

# Save the done proc.
      set doneproc $whendone

# If the observe type is DARK or BIAS the don't bother with the CC
# configuration and call the DC setup directly.
      set obstype [$instobj cget -observeType]
      if { $obstype == "DARK" || $obstype == "BIAS" } {
         # Start the detector controller setup action.
         $instobj apply detector
         return 1
      } else {

# Start the instrument sequencer setup action.
         $instobj apply components
         return 1
      }
   }
}

itcl::body NirsInst::setupDC {} {

# Start the detector controller setup action.
   $instobj apply detector
}

itcl::body NirsInst::description {} {

# Returns the current filter name and exposure time.
   return "[$instobj cget -filter] [$instobj cget -exposureTime]s"
}

