#+
#  OcsSession
#
#  Represents an OCS session with methods for retrieving the observations
#  in the queue, fetching coordinate information associated with an
#  observation and updating the state of an observation.
#
#  Options:
#
#  Methods:
#          listObs   Returns a list of the observation ids currently in the
#                   session.
#
#          getField  Returns the field definition associated with an
#                    observation as an XML string.
#
#          getSequence   Returns the sequence definition associated with an
#                   observation as an XML string.
#
#          idleReason Set the reason for the session being idle.
#
#          obsEnd    Informs the session that an observation has ended.
#
#          obsStart  Informs the session that an observation has started.
#
#          obsAbort  Informs the session that an observation has been
#                    abandoned.
#
#          seqEnd    Informs the session that a sequence has ended.
#
#          seqStart  Informs the session that a sequence has started.
#
#  D Terrett 27 October 2002
#
#  Copyright CCLRC
#+

package require SOAP

itcl::class OcsSession {
   constructor {name} {}
   public {
      method datComplete {obsid datasetid}
      method getField {obsid}
      method getSequence {obsid}
      method listObs {}
      method obsStart {obsid}
      method obsEnd {obsid}
      method idleReason {reason comment}
      method obsAbort {obsid reason}
      method seqEnd {obsid}
      method seqStart {obsid}
   }
   private {
      variable sessionName
      variable sessionUri urn:gemini/session
      variable sessionProxy http://scott:9000/axis/services/Session
      variable tccUri urn:gemini/Tcc
      variable tccProxy http://scott:9000/axis/services/Tcc
      variable execUri urn:gemini/Exec
      variable execProxy http://scott:9000/axis/services/Exec
   }
}

itcl::body OcsSession::constructor {name} {

# Store the session name.
   set sessionName $name

# Create a namespace for the SOAP methods.
   namespace eval ocs {}

# Create the soap methods.
   if { [llength [info commands ::OcsSession::_datasetComplete]] == 0 } {
      SOAP::create _datasetComplete -uri $sessionUri -proxy $sessionProxy \
            -params {sessionid string obsid string datasetid string} \
            -name datasetComplete
   }
   if { [llength [info commands ::OcsSession::_getCoordinates]] == 0 } {
      SOAP::create _getCoordinates -uri $tccUri -proxy $tccProxy \
            -params {obsid string} -name getCoordinates
   }
   if { [llength [info commands ::OcsSession::_getSequence]] == 0 } {
      SOAP::create _getSequence -uri $execUri -proxy $execProxy \
            -params {obsid string} -name getSequence
   }
   if { [llength [info commands ::OcsSession::_getObservations]] == 0 } {
      SOAP::create _getObservations -uri $sessionUri -proxy $sessionProxy \
            -params {sessionId string} -name getObservations
   }
   if { [llength [info commands ::OcsSession::_observationEnd]] == 0 } {
      SOAP::create _observationEnd -uri $sessionUri -proxy $sessionProxy \
            -params {sessionid string obsid string} -name observationEnd
   }
   if { [llength [info commands ::OcsSession::_observationStart]] == 0 } {
      SOAP::create _observationStart -uri $sessionUri -proxy $sessionProxy \
            -params {sessionid string obsid string} -name observationStart
   }
   if { [llength [info commands ::OcsSession::_observationAbort]] == 0 } {
      SOAP::create _observationAbort -uri $sessionUri -proxy $sessionProxy \
            -params {sessionid string obsid string reason string} \
            -name observationAbort
   }
   if { [llength [info commands ::OcsSession::_sequenceEnd]] == 0 } {
      SOAP::create _sequenceEnd -uri $sessionUri -proxy $sessionProxy \
            -params {sessionid string obsid string} -name sequenceEnd
   }
   if { [llength [info commands ::OcsSession::_sequenceStart]] == 0 } {
      SOAP::create _sequenceStart -uri $sessionUri -proxy $sessionProxy \
            -params {sessionid string obsid string} -name sequenceStart
   }
   if { [llength [info commands ::OcsSession::_setIdleCause]] == 0 } {
      SOAP::create _setIdleCause -uri $sessionUri -proxy $sessionProxy \
            -params \
            {sessionid string catagory string comment string} \
            -name setIdleCause
   }
}

itcl::body OcsSession::datComplete {obsid datasetid} {
   _datasetComplete $sessionName $obsid $datasetid
}

itcl::body OcsSession::getField {obsid} {
   return [_getCoordinates $obsid]
}

itcl::body OcsSession::getSequence {obsid} {
   return [_getSequence $obsid]
}

itcl::body OcsSession::listObs {} {
   return [_getObservations $sessionName]
}

itcl::body OcsSession::obsEnd {obsid} {
   _observationEnd $sessionName $obsid
}

itcl::body OcsSession::obsStart {obsid} {
   _observationStart $sessionName $obsid
}

itcl::body OcsSession::idleReason {reason comment} {
   _setIdleCause $sessionName $reason $comment
}

itcl::body OcsSession::obsAbort {obsid reason} {
   _observationAbort $sessionName $obsid $reason
}

itcl::body OcsSession::seqEnd {obsid} {
   _sequenceEnd $sessionName $obsid
}

itcl::body OcsSession::seqStart {obsid} {
   _sequenceStart $sessionName $obsid
}
