#+
# ProgressPopup <- itk::Widget
#
# A ProgressPopup pops an unmanaged feedback.
#
# Methods:
#     update
#     progresspopup
#+

itcl::class ProgressPopup {
   inherit itk::Toplevel
   
   constructor {title steps args} {}
   
   public {
      method update { {value 1} }
      proc progresspopup {title {steps 100}}
   }
   
}

itk::usual ProgressPopup {
    keep -background -cursor -modality 
}

itcl::body ProgressPopup::constructor {title steps args} {
   wm withdraw $itk_component(hull)
   wm overrideredirect $itk_component(hull) 1 
   itk_component add feedback {
      iwidgets::feedback $itk_interior.feedback -labeltext $title -steps $steps
   } {
      usual
   }
   pack $itk_component(feedback) -fill both -expand yes
   
   wm geometry $itk_component(hull) +[expr { [winfo rootx .] + [winfo width .]/2 - 50}]+[expr { [winfo rooty .] + [winfo width .]/2 - 25}]

   
   wm deiconify $itk_component(hull)
   eval itk_initialize $args
}

itcl::body ProgressPopup::update { {value 1} } {
   $itk_component(feedback) step $value
}

#
# Provide a lowercased access method for the Shell class.
# 
itcl::body ProgressPopup::progresspopup { title { steps 100 } } {
    ProgressPopup .#auto $title $steps
}
