#+
#  RealGcal.itcl
#
#  A RealGcal object controls GCAL, setting the filter, diffuser, shutter
#  and lamp states.
#
#  The current state of the tcs is stored in the array tcsstate when the
#  setup is started.
#
#  Note - Control of the IR lamp and shutter not implemented yet.
#
#  D Terrett 12 December 2001
#
#  Copyright CCLRC
#+

itcl::class RealGcal {

   common trace 0

   public {
      constructor {args} {}
      destructor {}
      method setup {whendone}
      variable filter ""
      variable diffuser ""
      variable lamp ""
      variable shutter ""
   }
   private {
      method getstate {}
      method setuperror {args}
      method setupok {}
      method setuptimeout {}
      variable doneproc
      variable setupaction
      variable state
   }
}


namespace eval RealGcal {
   global Flags
   seq::PrincipalSystem GCAL gcal::Apply -debug $Flags(tracegcal)  \
         -simulate $Flags(simgcal) -delay 0
}

itcl::body RealGcal::constructor {args} {

   set setupaction [seq::Action #auto RealGcal::GCAL]
   $setupaction configure -onerror [itcl::code $this setuperror] \
         -ontimeout [itcl::code $this setuptimeout] \
         -onok [itcl::code $this setupok]
   $setupaction connect gcal::filtSel
   $setupaction connect gcal::lampSel
   $setupaction connect gcal::diffuseSel
   $setupaction connect gcal::shutter

   # Create the status acceptor for reading the state of the gcal
   # and the one for GCAL seq::PrincipalSystem
   
   if { [catch {sa gcal::status info}] } {
      epics sa gcal::status
   }
   if { [catch {sa gcal::Apply info}] } {
      epics sa gcal::Apply
   }
}

itcl::body RealGcal::destructor {} {
   itcl::delete object $setupaction
}


itcl::body RealGcal::setup {whendone} {

# Configures GCAL.

# Get the current state.
   getstate

# Turn off any lamps (except for the IR lamp) that are on but shouldn't be 
# for this step.
   foreach l {Ar Kr CuAr ThAr QH} {
      if { $state(${l}LampState) == "ON" && $l != $lamp } {
         if { $trace } {
            puts "trace: cs gcal::lampSel set name $l"
            puts "trace: cs gcal::lampSel set state OFF"
            puts "trace: cs gcal::lampSel postWait"
         }
         cs gcal::lampSel set name $l
         cs gcal::lampSel set state OFF
         cs gcal::lampSel postWait
         set state(${l}LampState) OFF
      }
   }
# The only way to turn low (=off) the IR lamp is to turn everything off
   if { $state(IRLampState) == "ON" && "OFF" == $lamp } {
      if { $trace } {
         puts "trace: cs gcal::lampSel set name OFF"
         puts "trace: cs gcal::lampSel postWait"
      }
      cs gcal::lampSel set name OFF
      cs gcal::lampSel set state OFF
      cs gcal::lampSel postWait
      set state(IRLampState) OFF
   }

# Assume that we won't need to do anything.
   set needaction 0

# Check for a lamp that needs to be turned on.
   $setupaction unset gcal::lampSel name
   $setupaction unset gcal::lampSel state
   foreach l {IR Ar Kr CuAr ThAr QH} {
      if { $state(${l}LampState) != "ON" && $l == $lamp } {
         $setupaction set gcal::lampSel name $l
         $setupaction set gcal::lampSel state ON
         set needaction 1
         break
      }
   }

# Look for mechanisms that need to be moved.
   if { $diffuser != "" && $state(diffuser) != $diffuser } {
      $setupaction set gcal::diffuseSel name $diffuser
      set needaction 1
   } else {
      $setupaction unset gcal::diffuseSel name
   }
   if { $filter != "" && $state(filter) != $filter } {
      $setupaction set gcal::filtSel name $filter
      set needaction 1
   } else {
      $setupaction unset gcal::filtSel name
   }
   if { $shutter != "" && $state(shutter) != $shutter } {
      $setupaction set gcal::shutter position $shutter
      set needaction 1
   } else {
      $setupaction unset gcal::shutter position
   }

# If action is needed, save the when done proc and start the action.
   if { $needaction } {
      set doneproc $whendone
      $setupaction start
   } else {

# Call the whendone procedure directly.
      after idle $whendone 1
   }
   return 1
}

itcl::body RealGcal::getstate {} {

# Captures the state of the gcal (as relevant to the sequence executor).

# The shutter is either OPEN or CLOSE.
   switch [sa gcal::status get shutter] {
      OPEN {set state(shutter) OPEN}
      CLOSE {set state(shutter) CLOSE}
      default {set state(shutter) UNKNOWN}
   }

# The filter is a name.
   set state(filter) [sa gcal::status get filter]

# The diffuser is a name.
   set state(diffuser) [sa gcal::status get diffuser]

# The lamp states are ON or OFF.
   foreach l {IR Ar Kr CuAr ThAr QH} {
      switch [sa gcal::status get ${l}LampState] {
         ON {set state(${l}LampState) ON}
         OFF {set state(${l}LampState) OFF}
         default {set state(${l}LampState) UNKNOWN}
      }
   }
}

# These config bodies map the OT filter, lamp and diffuser names into GCAL
# names.

itcl::configbody RealGcal::filter {
   switch $filter {
      "none" {set filter CLEAR}
      "clear" {set filter CLEAR}
      "GMOS balance" {set filter GMOS}
      "HROS balance" {set filter HROS}
   }
}

itcl::configbody RealGcal::diffuser {
   switch $diffuser {
      IR {set diffuser IR}
      visible {set diffuser VISIBLE}
   }
}

itcl::configbody RealGcal::lamp {
   switch $lamp {
      "IR grey body" {set lamp IR}
      "IR high" {set lamp IR}
      "IR grey body - high" {set lamp IR}
      "IR low" {set lamp OFF}
      "IR grey body - low" {set lamp OFF}
      "Quartz Halogen" {set lamp QH}
      "Ar arc" {set lamp Ar}
      "Kr arc" {set lamp Kr}
      "ThAr arc" {set lamp ThAr}
      "CuAr arc" {set lamp CuAr}
   }
   }

itcl::configbody RealGcal::shutter {
   switch $shutter {
      "Open" {set shutter OPEN}
      "Closed" {set shutter CLOSE}
   }
   }

itcl::body RealGcal::setupok {} {

# Called when setting up the instrument completes successfully.
   $doneproc 1
}

itcl::body RealGcal::setuperror {args} {

# Called when setting up the instrument fails.
   lappend ::Sequence::errormsg "GCAL setup ended in error"
   if { [llength $args] } {
      eval lappend ::Sequence::errormsg $args
      }
   $doneproc 0
}

itcl::body RealGcal::setuptimeout {} {

# Called when setting up the instrument fails.
   lappend ::Sequence::errormsg "GCAL setup timed out"
   $doneproc 0
}
