#+
#  RealGpol.itcl
#
#  A RealGpol object controls GPOL, setting the filter, diffuser, shutter
#  and lamp states.
#
#  The current state of the tcs is stored in the array tcsstate when the
#  setup is started.
#
#  Note - Control of the IR lamp and shutter not implemented yet.
#
#  D Terrett 12 December 2001
#
#  Copyright CCLRC
#+

itcl::class RealGpol {

   common trace 0

   public {
      constructor {args} {}
      destructor {}
      method setup {whendone}

      variable modulator ""
      variable calibrator ""
      variable angle ""

      variable inUse 0
   }
   private {
      method setuperror {args}
      method setupok {}
      method setuptimeout {}
      variable doneproc
      variable setupaction
      variable state1 ""
      variable state2 ""
      variable state3 ""
      
      # park default
      variable parkSwitch1 "CLOSED"
      variable parkSwitch2 "CLOSED"
      variable parkSwitch3 "CLOSED"
      variable beamSwitch1 "OPEN"
      variable beamSwitch2 "OPEN"
      variable beamSwitch3 "OPEN"
      
      
      variable angle1 ""
      variable angle_wpval ""
      variable angle_wpname ""
      
   }
}


namespace eval RealGpol {
   global Flags
   seq::PrincipalSystem GPOL gpol::Apply -debug 1  \
         -simulate $Flags(simgpol) -delay 0
}

itcl::body RealGpol::constructor {args} {

   set setupaction [seq::Action #auto RealGpol::GPOL]
   $setupaction configure -onerror [itcl::code $this setuperror] \
         -ontimeout [itcl::code $this setuptimeout] \
         -onok [itcl::code $this setupok]
   $setupaction connect gpol::seq
   $setupaction configure -timeout 180

   # Create the status acceptor for reading the state of the gpol
   # and the one for GPOL seq::PrincipalSystem
   
   if { [catch {sa gpol::Apply info}] } {
      epics sa gpol::Apply
   }
   if { [catch {sa gpol::status info}] } {
      epics sa gpol::status
   }
}

itcl::body RealGpol::destructor {} {
   itcl::delete object $setupaction
}


itcl::body RealGpol::setup {whendone} {

  $setupaction unset gpol::seq state1
  $setupaction unset gpol::seq state2
  $setupaction unset gpol::seq state3
  $setupaction unset gpol::seq angle1
  $setupaction unset gpol::seq angle2
  $setupaction unset gpol::seq angle3
  
  
   set marked 0

# Configures GPOL.

   if { ! $inUse } {
      set state1 PARKED
      set state2 PARKED
      set state3 PARKED
      set parkSwitch1 CLOSED
      set beamSwitch1 OPEN
      set parkSwitch2 CLOSED
      set beamSwitch2 OPEN
      set parkSwitch3 CLOSED
      set beamSwitch3 OPEN
      }
      
   # plate 1 state
   if { ![string is space $state1] } {
      set _parkSwitch1 [sa gpol::status get parkSwitch1 value]
      set _beamSwitch1 [sa gpol::status get beamSwitch1 value]
      if { ![string equal $parkSwitch1 $_parkSwitch1] || ![string equal $beamSwitch1 $_beamSwitch1] } {
         $setupaction set gpol::seq state1 "$state1"
         set marked 1
         }\
      else {
         puts stdout "state1 already in place, skipping that config"
         }
      }
      
   # plate 2 state
   if { ![string is space $state2] } {
      set _parkSwitch2 [sa gpol::status get parkSwitch2 value]
      set _beamSwitch2 [sa gpol::status get beamSwitch2 value]
      if { ![string equal $parkSwitch2 $_parkSwitch2] || ![string equal $beamSwitch2 $_beamSwitch2] } {
         $setupaction set gpol::seq state2 "$state2"
         set marked 1
         }\
      else {
         puts stdout "state2 already in place, skipping that config"
         }
      }
      
   # plate 3 state
   if { ![string is space $state3] } {
      set _parkSwitch3 [sa gpol::status get parkSwitch3 value]
      set _beamSwitch3 [sa gpol::status get beamSwitch3 value]
      if { ![string equal $parkSwitch3 $_parkSwitch3] || ![string equal $beamSwitch3 $_beamSwitch3] } {
         $setupaction set gpol::seq state3 "$state3"
         set marked 1
         }\
      else {
         puts stdout "state3 already in place, skipping that config"
         }
      }

   # only set the angle when GPOL in use
   if { $inUse } {
      # plate 1 angle
      if { ![string is space $angle1] } {
         set _angle1 [sa gpol::status get angle1 value]
         if { [ expr { abs( $angle1 - $_angle1) > .1 }] } {
            $setupaction set gpol::seq angle1 "$angle1"
            set marked 1
            }\
         else {
            puts stdout "angle1 already in place, skipping that config"
            }
         }
      # other plate angle
      if { ![ string is space $angle_wpname] && ![ string is space $angle_wpval]} {
         set _angle_wpval [sa gpol::status get $angle_wpname value]
         if { [ expr { abs( $angle_wpval - $_angle_wpval) > .1 }]  } {
            $setupaction set gpol::seq $angle_wpname "$angle_wpval"
            set marked 1
            }\
         else {
            puts stdout "$angle_wpname already in place, skipping that config"
            }
         }
         
      }

# save the when done proc and start the action.

   set doneproc $whendone
   
   if {$marked} {
      $setupaction start
      }\
   else {
      after idle [$setupaction cget -onok]
      }

   return 1
}

itcl::body RealGpol::setupok {} {

# Called when setting up the instrument completes successfully.
   $doneproc 1
}

itcl::body RealGpol::setuperror {args} {

# Called when setting up the instrument fails.
   lappend ::Sequence::errormsg "GPOL setup ended in error"
   if { [llength $args] } {
      eval lappend ::Sequence::errormsg $args
      }
   $doneproc 0
}

itcl::body RealGpol::setuptimeout {} {

# Called when setting up the instrument fails.
   lappend ::Sequence::errormsg "GPOL setup timed out"
   $doneproc 0
}

itcl::configbody RealGpol::modulator  {
   set inUse 1
   switch $modulator {
      "Optical/near-IR" {
         set state2 INBEAM
         set state3 PARKED
         set angle_wpname angle2
         set parkSwitch2 OPEN
         set parkSwitch3 CLOSED
         set beamSwitch2 CLOSED
         set beamSwitch3 OPEN
         }
      "Thermal IR" {
         set state2 PARKED
         set state3 INBEAM
         set angle_wpname angle3
         set parkSwitch3 OPEN
         set parkSwitch2 CLOSED
         set beamSwitch3 CLOSED
         set beamSwitch2 OPEN
         }
      default {
         set state2 PARKED
         set state3 PARKED
         set angle_wpname ""
         set parkSwitch3 CLOSED
         set parkSwitch2 CLOSED
         set beamSwitch3 OPEN
         set beamSwitch2 OPEN
         }
      }
}
itcl::configbody RealGpol::calibrator  {
   set inUse 1
   switch $calibrator {
      "None" {
         set state1 PARKED
         set parkSwitch1 CLOSED
         set beamSwitch1 OPEN
         }
      "Wire-grid" {
         set state1 INBEAM
         set angle1 0.0
         set parkSwitch1 OPEN
         set beamSwitch1 CLOSED
         }
      "UV polaroid" {
         set state1 INBEAM
         set angle1 120.0
         set parkSwitch1 OPEN
         set beamSwitch1 CLOSED
         }
      "Optical polaroid" {
         set state1 INBEAM
         set angle1 240.0
         set parkSwitch1 OPEN
         set beamSwitch1 CLOSED
         }
      }
}
itcl::configbody RealGpol::angle  {
   set inUse 1
   set angle_wpval $angle
}
