#+
#  SequenceNSloop.itcl
#
#  A sequenceNSloop is a nod and shuffle sequence, that loops over a  
#  limited number of Step
#
#  Matthieu Bec 31 October 2002
#
#+

itcl::class SequenceNSloop {
   inherit Sequence
   public {
      method description {idx}
      method shortdescription {idx}
      method moveindex {ind {system "all"}}
      method obsindex {ind}
   }
   protected {
      method postparse {}
   }
   
   private {
      common nodSequence { B A A B }
      method stepconfig { index }
      variable nsPix
      variable nsMode
      variable nsCount
      variable nsXoff
      variable nsYoff
      variable gpolInUse
      variable gcalInUse
      variable gpolmodulator
      variable gpolcalibrator
      variable gpolangle
      variable gcalfilter
      variable gcaldiffuser
      variable gcallamp
      variable gcalshutter
      variable NODA_p             
      variable NODA_q             
      variable NODA_guideWithOIWFS
      variable NODB_p             
      variable NODB_q             
      variable NODB_guideWithOIWFS
      variable NODA_observeType   
      variable NODB_observeType   
      variable NODA_exposureTime  
      variable NODB_exposureTime   
      variable NODA_nsRows        
      variable NODB_nsRows        
      }

}


#------------------------------------------------------------------------------
# description
#------------------------------------------------------------------------------
itcl::body SequenceNSloop::description {idx} {

# Returns the short description of the specified step (for display by the user
# interface).

set step ::Sequence::StepNames::[lindex $steplist $idx]
set tcsobj [$step cget -tcsobj]
set p [$tcsobj cget -p]
set q [$tcsobj cget -q]
set obstype [$tcsobj cget -observeType]

return [format "%-8s\t\t%s %s %s %s" \
                 "Step $idx"  $p $q $obstype [[$step cget -instobj] description]]
}

#------------------------------------------------------------------------------
# shortdescription
#------------------------------------------------------------------------------
itcl::body SequenceNSloop::shortdescription {idx} {
return "Step $idx"
}

#------------------------------------------------------------------------------
# postparse
#------------------------------------------------------------------------------
itcl::body SequenceNSloop::postparse {} {

# the defaults
   set nsIter               0
   set nsRows               0
   set NODA_p               0.0
   set NODA_q               0.0
   set NODA_guideWithOIWFS  ""
   set NODB_p               ""
   set NODB_q               ""
   set NODB_guideWithOIWFS  ""
   set NODA_observeType     ""
   set NODB_observeType     ""
   set NODA_exposureTime    ""
   set NODB_exposureTime    ""     
   set NODA_nsRows          0
   set NODB_nsRows          0

# basic integrity check
   if { [llength $steplist] != 2 } {
      # clean up is done at a higher level
      set errormsg "Doesn't appear to be a nod/shuffle (doesn't define 2 steps)"
      # Clean up.
         if { ![string is space $seqobj] } {
            #puts "SequenceNSloop cleanup $seqobj"
            itcl::delete object $seqobj
            set seqobj ""
            }
      return
      }

# read the sequence object for nod/shuffle parameters
# note: this use the usual regression trick
   foreach nod { A B } stepobj [$seqobj cget -subellist] {
      
# Append the step object to the list of step objects.
      lappend objlist $stepobj

# get the NODs parameters
      foreach {param system} {
         p telescope \
         q telescope \
         guideWithOIWFS telescope \
         observeType observe \
         exposureTime observe
      } {

# Search the list of steps starting with the last.
         set value ""
         for {set i 0} {$i < [llength $objlist] && $value == ""} {incr i} {
            set value [seqparse::sequence::findpar [lindex $objlist end-$i] $system $param]
         }
         if { $value != "" } {
            set NOD$nod\_$param $value
         }
      }
   
# get the shuffle and iteration parameters
      foreach {param system} {
         nsIter nodshuffle\
         nsRows nodshuffle\
         nsMode nodshuffle
      } {

# Search the list of steps starting with the last.
         set value ""
         for {set i 0} {$i < [llength $objlist] && $value == ""} {incr i} {
            set value [seqparse::sequence::findpar [lindex $objlist end-$i] $system $param]
         }
         if { $value != "" } {
             set $param $value
         }
      }      
# NODA_nsRows is 0
      set NODB_nsRows $nsRows
   }


# get the gcal parameters
set gcalInUse 0

      foreach {param system} {
         filter calibration\
         diffuser calibration\
         lamp calibration\
         shutter calibration\
      } {

# Search the list of steps starting with the last.
         set value ""
         for {set i 0} {$i < [llength $objlist] && $value == ""} {incr i} {
            set value [seqparse::sequence::findpar [lindex $objlist end-$i] $system $param]
         }
         if { $value != "" } {
             set gcalInUse 1
             set gcal$param $value
         }\
         else {
            set gcal$param ""
            }
      }

# get the gpol parameters
set gpolInUse 0

      foreach {param system} {
         modulator gpol \
         calibrator gpol\
         angle gpol\
      } {

# Search the list of steps starting with the last.
         set value ""
         for {set i 0} {$i < [llength $objlist] && $value == ""} {incr i} {
            set value [seqparse::sequence::findpar [lindex $objlist end-$i] $system $param]
         }
         if { $value != "" } {
             set gpolInUse 1
             set gpol$param $value
         }\
         else {
            set gpol$param ""
            }
      }

   set nsPix   $nsRows
   set nsCount $nsIter
   set nsXoff  $NODB_p
   set nsYoff  $NODB_q


# puts "** nsRows $nsRows"
# puts "** nsIter $nsIter"
# puts "** nsXoff $nsXoff"
# puts "** nsYoff $nsYoff"
# puts "** NODA_p $NODA_p"
# puts "** NODA_q $NODA_q"
# puts "** NODA_nsRows $NODA_nsRows"
# puts "** NODA_exposureTime $NODA_exposureTime"
# puts "** NODA_observeType $NODA_observeType"
# puts "** NODA_guideWithOIWFS $NODA_guideWithOIWFS"
# puts "** NODB_p $NODB_p"
# puts "** NODB_q $NODB_q"
# puts "** NODB_nsRows $NODB_nsRows"
# puts "** NODB_exposureTime $NODB_exposureTime"
# puts "** NODB_observeType $NODB_observeType"
# puts "** NODB_guideWithOIWFS $NODB_guideWithOIWFS"
# foreach p { filter diffuser lamp shutter } {
#    puts "** gcal-> $p [set gcal$p]"
#    }
# foreach p { modulator calibrator angle } {
#    puts "** gpol-> $p [set gpol$p]"
#    }



#******************************************************************************
#************* missing here ***************************************************
#******************************************************************************
# second integrity check
#  check thos 3 params actually came in
#******************************************************************************


set stepA [lindex $steplist 0]
set stepB [lindex $steplist 1]


# expand the sequence
   for { set i 0 } { $i < [expr { $nsIter * [llength $nodSequence] } ] } { incr i } {
      set index [expr $i % [llength $nodSequence]]
      lappend steplist2 [set step[lindex $nodSequence $index]]
      }

set stepobjlist $steplist
set steplist $steplist2

# Clean up.
   if { ![string is space $seqobj] } {
      #puts "SequenceNSloop cleanup $seqobj"
      itcl::delete object $seqobj
      set seqobj ""
      }
}

#------------------------------------------------------------------------------
# stepconfig
#------------------------------------------------------------------------------
itcl::body SequenceNSloop::stepconfig {i} {

# Get the name of the specified step.
   set step [lindex $steplist $i]
# If it exists, re-configure the step for the current index
   if { $step != "" } {
# Configure the step for the current index
   } else {
      error "No step $i in sequence"
   }
   
   set thisnod [lindex $nodSequence [expr {$i % [llength $nodSequence]}]]
   set step    ::Sequence::StepNames::$step
   set instobj [[$step cget -instobj] cget -instobj]
   set dhsobj  [$step cget -dhsobj ]
   set gcalobj [$step cget -gcalobj]
   set gpolobj [$step cget -gpolobj]
   set tcsobj  [$step cget -tcsobj ]

   $instobj configure -nsRows          [set NOD$thisnod\_nsRows]
   $instobj configure -exposureTime    [set NOD$thisnod\_exposureTime]
   $instobj configure -observeType     [set NOD$thisnod\_observeType]
   $tcsobj  configure -p               [set NOD$thisnod\_p]
   $tcsobj  configure -q               [set NOD$thisnod\_q]
   $tcsobj  configure -guideWithOIWFS  [set NOD$thisnod\_guideWithOIWFS]

   if { $i == 0 } {
      $instobj configure -nsState         NS_FIRST
      if {$gcalInUse} {
         foreach p { filter diffuser lamp shutter} {
            if { ![string is space [set gcal$p] ] } {
               $gcalobj configure -$p     [set gcal$p]
               }
            }
         }
      if {$gpolInUse} {
         foreach p { modulator calibrator angle } {
            if { ![string is space [set gpol$p] ] } {
               $gpolobj configure -$p     [set gpol$p]
               }
            }
         }
      $step   configure -headersbefore    1
      $step   configure -headersafter     0
      $step   configure -observeTcs       1
      $step   configure -endObserveTcs    0
      $step   configure -observeInst      1
      $step   configure -endObserveInst   0
      $step   configure -incDatalabel     0
      $dhsobj configure -useNS            1
      $dhsobj configure -nsPix            $nsPix
      $dhsobj configure -nsMode           $nsMode
      $dhsobj configure -nsCount          $nsCount
      $dhsobj configure -nsXoff           $nsXoff
      $dhsobj configure -nsYoff           $nsYoff
      }\
   elseif { $i == [expr [llength $steplist] - 1] } {
      $instobj configure -nsState         NS_LAST
      $dhsobj  configure -useNS           1
      $dhsobj  configure -nsCount         $nsCount
      $step    configure -headersbefore   0
      $step    configure -headersafter    1
      $step    configure -observeTcs      0
      $step    configure -endObserveTcs   1
      $step    configure -observeInst     1
      $step    configure -endObserveInst  1
      $step    configure -incDatalabel    1
      }\
   else {
      $instobj configure -nsState         NS_MIDDLE
      $step    configure -headersbefore   0
      $step    configure -headersafter    0
      $step    configure -observeTcs      0
      $step    configure -endObserveTcs   0
      $step    configure -observeInst     1
      $step    configure -endObserveInst  0
      $step    configure -incDatalabel    0
      }
   }

#------------------------------------------------------------------------------
# moveindex (override)
#------------------------------------------------------------------------------
itcl::body SequenceNSloop::moveindex {ind {system "all"}} {
   stepconfig $ind
   Sequence::moveindex $ind $system
}

#------------------------------------------------------------------------------
# obsindex (override)
#------------------------------------------------------------------------------
itcl::body SequenceNSloop::obsindex {ind} {
   stepconfig $ind
   Sequence::obsindex $ind
}

