#+
#  Sequence.itcl
#
#  A sequence is an ordered list of Step objects with methods for moving
#  the telescope and instrument to a Step and observing a Step. After 
#  performing an operation the sequence moves onto the next operation 
#  unless -pause is true. 
#
#  There are methods for moving and observing a specified step, pausing and
#  continuing an observe and executing the next operation in the sequence.
#
#  The common variable current contains the index of the current step and 
#  statemsg contains a text description of what the current state of the 
#  sequence is.
#
#  A sequence is created from an XML description using the seqparse functions
#  to convert the xml description into a tree of objects which can then be
#  interrogated to create the steps. One the sequence has been created these
#  objects are discarded.
#
#  D Terrett  29 October 2002
#
#  Copyright CCLRC 2002
#+

itcl::class Sequence {
   constructor {} {}
   destructor {}
   public {
      method parse {seqobject}
      common current 0
      common errormsg ""
      common errorproc
      common statemsg ""
      common site ""
      method stopobs {}
      method abortobs {}
      method continueobs {}
      method description {idx}
      method shortdescription {idx}
      method moveindex {ind {system "all"}}
      method next {} {$nextop}
      method offset {step}
      method obsindex {ind}
      method obstype {step}
      method pauseobs {}
      variable ignoretcs 0
      variable maxguidestep ""
      variable pause 0
      variable steplist {}
      common beep 1
  }
   protected {
      method postparse {}
      variable seqobj ""
      variable stepobjlist {}
   }
   private {
      method dhsconfig {dhsobj objlist}
      method gcalconfig {gcalobj objlist}
      method gpolconfig {gpolobj objlist}
      method instconfig {instobj objlist}
      method getinstname {objlist}
      method tcsconfig {tcsobj objlist}
      method movedone {status}
      method obsdone {status}
      variable nextop
   }
}

itcl::body Sequence::constructor {} {
# Create a namespace for the steps.
   namespace eval StepNames {}
   }
   
itcl::body Sequence::parse {seqobject} {

set seqobj $seqobject

# Convert the sequence object into step objects.
   foreach stepobj [$seqobj cget -subellist] {
      if { [$stepobj isa seqparse::step] } {

# Append the step object to the list of step objects.
         lappend objlist $stepobj

# Get the value of the step's name attribute to use as the name of the step.
         set name [$stepobj cget -name]
         if { [string equal $name <undefined>] } {
            set name anon#auto
         }

# Create the Step.
         set step [namespace eval StepNames [list Step $name]]

# Append the new step to the list of steps.
         
         lappend steplist $step
         lappend stepobjlist $step

# Set the dataset id from the current step.
         StepNames::$step configure -datalabel [lindex [split \
               [::seqparse::sequence::findpar $stepobj observe dataLabel] -] \
               end]

# Create the object that controls the tcs.
         set tcsobj [RealTcs #auto]
         StepNames::$step configure -tcsobj [namespace code $tcsobj]

# Find the name of the instrument.
         set instname [getinstname $objlist]

# Create the instrument and dhsinfo objects appropriate to the instrument.
         switch $instname {
            NIRI {
               set instobj [NiriInst #auto]
               set dhsobj [dhshdr::HdrNiri #auto NIRI mko-dc-data-niri]
            }
# GNIRS {
# set instobj [GNIRSInst #auto]
# set dhsobj [dhshdr::HdrGNIRS #auto GNIRS mko-dc-data-gnirs]
#}

            GMOS {
               set instobj [GmosInst #auto]
               switch $site {
                  MK - GN {
                     set dhsobj [dhshdr::HdrGmos #auto GMOS-N gmosdc]
                     }
                  CP - GS {
                     set dhsobj [dhshdr::HdrGmos #auto GMOS-S gmosdc]
                     }
                  default {
                     set errormsg "Error: invalid/undefined site for GMOS"
                     return
                  }
               }
            }
            "Acquisition Camera" {
               set instobj [AcqCamInst #auto]
               set dhsobj [dhshdr::HdrInfo #auto hrwfs hrwfs]
            }
            TRECS {
               set instobj [TrecsInst #auto]
               set dhsobj [SimHdrInfo #auto]
            }
            "" {

# No instrument specified so use simulated objects for both the instrument
# and the DHS.
               set instobj [SimInst #auto]
               set dhsobj [SimHdrInfo #auto]
            }
            default {
               set errormsg "Instrument name \"$instname\" not recognised"
               return
            }
         }
         StepNames::$step configure -instobj [namespace code $instobj] \
               -dhsobj [namespace code $dhsobj]

# Create the object that controls the gcal.
         set gcalobj [RealGcal #auto]
         StepNames::$step configure -gcalobj [namespace code $gcalobj]

# Create the object that controls the gpol.
         set gpolobj [RealGpol #auto]
         StepNames::$step configure -gpolobj [namespace code $gpolobj]

# Configure the tcs object.
         if { [catch {tcsconfig [namespace code $tcsobj] $objlist} msg] } {
            set errormsg "Error configuring step \"$step\": $msg"
            return
         }

# Configure the instrument object.
         if { ! [$instobj isa SimInst] } {
            instconfig [$instobj cget -instobj] $objlist
         }

# Configure the instrument object -object parameter from the observe system.
         $instobj configure -object \
            [seqparse::sequence::findpar [lindex $objlist end] observe object]

# Configure the dhs object.
         dhsconfig [namespace code $dhsobj] $objlist

# Configure the gpol object.
         gpolconfig [namespace code $gpolobj] $objlist

# configure the dhsobj for gpol
         $dhsobj configure -useGpol [$gpolobj cget -inUse]
      
# Configure the gcal object. If the observe type is not FLAT or ARC then the
# shutter must be closed and the lamps off.
# We check for the presence of a 'calibration' system to differentiate GCAL
# flats from Dome Flats

         set obstype [$tcsobj cget -observeType]
         if { $obstype != "FLAT" && $obstype != "ARC" } {
            $gcalobj configure -shutter CLOSE
            $gcalobj configure -lamp none
         } else {
            gcalconfig $gcalobj $objlist
         }
# this was seen as a possible way to send back the telescope to 0.0 at the begining of nodshuffle
# because the OIWFS probearm could be left anywhere from the last B position, and we start
# a new sequence on B where it is frozen ...
#       if { [string equal [[$instobj cget -instobj ] cget -observeType] "NONE"] } {
#          ::Sequence::StepNames::$step configure -headersbefore     0
#          ::Sequence::StepNames::$step configure -headersafter      0
#          ::Sequence::StepNames::$step configure -observeTcs        0
#          ::Sequence::StepNames::$step configure -endObserveTcs     0
#          ::Sequence::StepNames::$step configure -observeInst       0
#          ::Sequence::StepNames::$step configure -endObserveInst    0
#          ::Sequence::StepNames::$step configure -incDatalabel      0
#       }
      }
   }

# Set the program id and observation id from the first step in the sequence.
   set dhshdr::gemprgid [seqparse::sequence::findpar [lindex $objlist 0] \
         ocs programId]
   set dhshdr::obsid [lindex [split [::seqparse::sequence::findpar \
         [lindex $objlist 0] ocs observationId] -] end]

# configure the maxguidestep.
   set RealTcs::maxguidestep $maxguidestep

# Initialise nextop variable to be a command to move to the start of the 
# sequence and set the current variable to the index of the first step.
   set nextop [itcl::code $this moveindex 0]
# note the trigger associated with current will fail because we haven't attached
# the sequence to the sequenceWidget
   set current 0

# Set the current state to idle.
   set statemsg idle

# do some addtional work - used by derived class
   postparse
}


itcl::body Sequence::destructor {} {

# Delete all the steps in the sequence.
   foreach step $stepobjlist {
      itcl::delete object StepNames::$step
   }

# Clean up.
   if { ![string is space $seqobj] } {
      #puts "Sequence::destructor cleanup $seqobj"
      itcl::delete object $seqobj
      }

# Delete the namespace that contained them.
   namespace delete StepNames

# Set the class common variables back to their initial values.
   set statemsg ""
   set errormsg ""
}

itcl::body Sequence::postparse {} {

#puts "Sequence::postparse"

# Clean up.
   if { ![string is space $seqobj] } {
      #puts "Sequence::postparse cleanup"
      itcl::delete object $seqobj
      set seqobj ""
      }
}

itcl::body Sequence::moveindex {ind {system "all"}} {

# If we are in ocs mode and this is the first step then send sequence start
# to the queue
   if { $::OcsEnable && $ind == 0 } {
      ocssession seqStart ${::dhshdr::gemprgid}-${::dhshdr::obsid}
   }

# Get the name of the specified step.
   set step [lindex $steplist $ind]

# If it exists, record the new current step index and call its move method.
   if { $step != "" } {
      set current $ind
      set statemsg "configuring $system for step \"$step\""
      update idletasks
      if { ! [StepNames::$step move [itcl::code $this movedone] $system] } {
         set statemsg "Failed while configuring $system for step \"$step\""
         if { $::OcsEnable } {
            ocssession obsAbort ${::dhshdr::gemprgid}-${::dhshdr::obsid} \
                  $errormsg
         }
         $errorproc
      } else {
         if { $system == "all" } {
# Set the next operation to observe the step.
            set nextop [itcl::code $this obsindex $ind]
            } else {
# Set the next operation to (re)configure the step.
            set nextop [itcl::code $this moveindex $ind]
            }
      }
   } else {
      error "No step $ind in sequence"
   }
   return
}



itcl::body Sequence::obsindex {ind} {

# Get the name of the specified step.
   set step [lindex $steplist $ind]

# If it exists, record the new current step index and call its observe method.
   if { $step != "" } {
      set current $ind
      set statemsg "observing step \"$step\""
      update idletasks
      if { ! [StepNames::$step observe [itcl::code $this obsdone]] } {
         set statemsg "Failed while observing  step \"$step\""
         if { $::OcsEnable } {
            ocssession obsAbort ${::dhshdr::gemprgid}-${::dhshdr::obsid} \
                  $errormsg
         }
         $errorproc
      } else {

# Increment the index and set to zero if it is passed the 
# end of the list.
         incr ind
         if { $ind >= [llength $steplist] } {
            set ind 0
         }

# Get the name of the next step.
         set step [lindex $steplist $ind]

# Set the next op to be a move to that step.
         set nextop [itcl::code $this moveindex $ind]
      }
   } else {
      error "No step $ind in sequence"
   }
   return
}

itcl::body Sequence::movedone {status} {

   if { $status } {

# If pause is true then just change the state to something appropriate.
      if { $pause } {
         set statemsg "paused after configure of step \
               \"[lindex $steplist $current]\""
      } else {

# Execute the next operation.
         after idle $nextop
      }
   } else {

# Set the state to indicate what has failed and report the error.
      set statemsg "Error while configuring step"
      if { $::OcsEnable } {
         ocssession obsAbort ${::dhshdr::gemprgid}-${::dhshdr::obsid}  \
               $errormsg
      }
      $errorproc
   }
   return
}

itcl::body Sequence::obsdone {status} {

   if { $status } {
      if { $::OcsEnable } {
         ocssession datComplete ${::dhshdr::gemprgid}-${::dhshdr::obsid} \
               ${::dhshdr::gemprgid}-${::dhshdr::obsid}-${::dhshdr::datalabel}
      }

# report the sucessful observe to the ocs queue.

# If pause is true then just change the state to something appropriate.
      if { $pause } {
         set statemsg "paused after observe of step \
               \"[lindex $steplist $current]\""
      } else {

# Unless we have just observed the last step execute the next operation.
         if { $current + 1 ==  [llength $steplist] } {
            set statemsg "sequence finished"
            if { $beep } {
               bell
               }
            if { $::OcsEnable } {
               ocssession seqEnd ${::dhshdr::gemprgid}-${::dhshdr::obsid}
            }
         } else {
            after idle $nextop
         }
      }
   } else {

# Set the state to indicate what has failed and report the error.
      set state PAUSED
      set statemsg "Error while observing"
      if { $::OcsEnable } {
         ocssession obsAbort ${::dhshdr::gemprgid}-${::dhshdr::obsid} \
               $errormsg
      }
      $errorproc
   }
   return
}

itcl::body Sequence::stopobs {} {

# Pause the sequence.
   set pause 1

# Get the name of the current step and call its stop method.
   set step [lindex $steplist $current]
   if { [StepNames::$step stop] } {
      set statemsg "observe of \"$step\" stopping"
   } else {
      $errorproc
   }
   return
}

itcl::body Sequence::abortobs {} {

# Pause the sequence.
   set pause 1

# Get the name of the current step and call its abort method.
   set step [lindex $steplist $current]
   if { [StepNames::$step abort] } {
      set statemsg "observe of \"$step\" aborting"
   } else {
      if { $::OcsEnable } {
         ocssession obsAbort ${::dhshdr::gemprgid}-${::dhshdr::obsid} \
               "Observation aborted by operator"
      }
      $errorproc
   }
   return
}

itcl::body Sequence::continueobs {} {

# Get the name of the current step and call its continue method.
   set step [lindex $steplist $current]
   if { [StepNames::$step continue] } {
      set statemsg "observe of \"$step\" continuing"
      update idletasks
   } else {
      if { $::OcsEnable } {
         ocssession obsAbort ${::dhshdr::gemprgid}-${::dhshdr::obsid} \
               $errormsg
      }
      $errorproc
   }
   return
}

itcl::body Sequence::pauseobs {} {

# Get the name of the current step and call its pause method.
   set step [lindex $steplist $current]
   if { [StepNames::$step pause] } {
      set statemsg "observation of \"$step\" paused"
      update idletasks
   } else {
      $errorproc
   }
   return
}

itcl::body Sequence::getinstname {objlist} {

# This method handles creating an instrument object of the correct type;
# to do this it has to search for an instrument parameter in either an
# observe system or an instrument system.

# Search the list of steps starting with the last.
   set instname ""
   for {set i 0} {$i < [llength $objlist] && $instname == ""} {incr i} {

# Look in the observe system.
      set step [lindex $objlist end-$i]
      set instname [seqparse::sequence::findpar $step observe instrument]

# Then the instrument.
      if { $instname == "" } {
         set instname [seqparse::sequence::findpar $step instrument instrument]
      }
   }
   return $instname
}

itcl::body Sequence::tcsconfig {tcsobj objlist} {

# Configures a tcs object.
   foreach {param system} {
      p telescope \
      q telescope \
      guideWithPWFS1 telescope \
      guideWithPWFS2 telescope \
      guideWithOIWFS telescope \
      posAngle instrument \
      observeType observe
   } {

# Search the list of steps starting with the last.
      set value ""
      for {set i 0} {$i < [llength $objlist] && $value == ""} {incr i} {
         set value [seqparse::sequence::findpar [lindex $objlist end-$i] $system $param]
      }
      if { $value != "" } {
         $tcsobj configure -$param $value
      }
   }   
}

itcl::body Sequence::instconfig {instobj objlist} {

# Configures an instrument object by searching for parameters that match
# the instrument object parameters in the observe and instrument systems.

# Set a default observe type of ""
   $instobj configure -observeType ""

   foreach paramspec [$instobj configure] {

# Get the parameter name.
      set param [string trimleft [lindex $paramspec 0] -]

# Look in the observe system of the current step (i.e last step in the list).
      set value [seqparse::sequence::findpar [lindex $objlist end] observe $param]

# If not found there search the instrument configuration of all the steps 
# starting with the last.
      if { $value == "" } {
         for {set i 0} {$i < [llength $objlist] && $value == ""} {incr i} {
            set value [seqparse::sequence::findpar [lindex $objlist end-$i] instrument $param]
         }
      }
      if { $value != "" } {
         $instobj configure -$param $value
      }
   lappend instparams $param
   }

# If the observe type is FLAT or ARC we must redetermine the exposure time
# and coadds because they may be specified in a calibration block.
   set obstype [$instobj cget -observeType]
   if { $obstype == "FLAT" || $obstype == "ARC" } {
      set step [lindex $objlist end]
      foreach par {exposureTime coadds} {
         set value [seqparse::sequence::findpar $step observe $par]
         if { $value == "" } {
            set value [seqparse::sequence::findpar $step calibration $par]
         }
         if { $value != "" } {
            # ignore unrecognised parameters (eg. coadds for Gmos or AcqCam)
            if { [lsearch -exact $instparams $par] != -1 } {
               $instobj configure -$par $value
            } else {
               puts ">> ignoring $par (not recognised)"
            }
         }
      }
   }
}

itcl::body Sequence::gcalconfig {gcalobj objlist} {

# Configures a gcal object from parameters found in the list of steps.
   foreach {param system} {
      filter calibration \
      diffuser calibration \
      lamp calibration \
      shutter calibration \
   } {

# Search the list of steps starting with the last.
      set value ""
      for {set i 0} {$i < [llength $objlist] && $value == ""} {incr i} {
         set value [seqparse::sequence::findpar [lindex $objlist end-$i] $system $param]
      }
      if { $value != "" } {
         $gcalobj configure -$param $value
      }
   }
}

itcl::body Sequence::gpolconfig {gpolobj objlist} {

# for gpol, only look into the current step definition   
   foreach {param system} {
      modulator gpol \
      calibrator gpol\
      angle gpol\
   } {

# Search the list of steps starting with the last.
      set value ""
      set value [seqparse::sequence::findpar [lindex $objlist end] $system $param]
      if { $value != "" } {
         $gpolobj configure -$param $value
      }
   }
   
}

itcl::body Sequence::dhsconfig {dhsobj objlist} {

# Configures a dhs object. The only parameters of interest are -guideWithXXXX 
# from the telescope config and -observeType from the observe config

# guideWithXXXX
   set guidewith ""
   foreach wfs {PWFS1 PWFS2 OIWFS} {

# Search the list of steps starting with the last.
      set value ""
      for {set i 0} {$i < [llength $objlist] && $value == ""} {incr i} {
         set value [seqparse::sequence::findpar [lindex $objlist end-$i] telescope guideWith$wfs]
      }
      if { $value != "" && $value != "park" && $value != "freeze" } {
         lappend guidewith $wfs
      }
   }
   if { $guidewith != "" } {
      $dhsobj configure -guideWith $guidewith
   } else {
      $dhsobj configure -guideWith none
   }
   
# observeType
   set value [seqparse::sequence::findpar [lindex $objlist end] observe observeType]
# If not found there search the instrument configuration of all the steps 
# starting with the last.
   if { $value == "" } {
      for {set i 0} {$i < [llength $objlist] && $value == ""} {incr i} {
         set value [seqparse::sequence::findpar [lindex $objlist end-$i] instrument observeType]
      }
   }
   if { $value != "" } {
      $dhsobj configure -observeType $value
   }
   
}

itcl::body Sequence::offset {step} {

# Returns the p & q offsets for the specified step (for display by the user
# interface).
   set tcsobj [StepNames::$step cget -tcsobj]
   return [list [$tcsobj cget -p] [$tcsobj cget -q]]
}

itcl::body Sequence::obstype {step} {

# Returns the observe Type for the specified step (for display by the user
# interface).
   return [[StepNames::$step cget -tcsobj] cget -observeType]
}

itcl::body Sequence::description {idx} {

# Returns the short description of the specified step (for display by the user
# interface).
#   return [lindex $steplist $idx]
#
set step [lindex $steplist $idx]
set tcsobj [StepNames::$step cget -tcsobj]
set p [$tcsobj cget -p]
set q [$tcsobj cget -q]
set obstype [$tcsobj cget -observeType]

return [format "%-8s\t\t%s %s %s %s" \
                  $step $p $q $obstype [[StepNames::$step cget -instobj] description]]
}

itcl::body Sequence::shortdescription {idx} {

# Returns the description of the specified step (for display by the user
# interface).
   return [lindex $steplist $idx]
}


# These config procedures copy the value of the option to the tcs object
# class common variable (unless the simulated tcs is being used). These are
# used by the used interface to control global aspects of the sequence
# execution.

itcl::configbody Sequence::maxguidestep {
   set RealTcs::maxguidestep $maxguidestep
}

itcl::configbody Sequence::ignoretcs {
   set RealTcs::ignoretcs $ignoretcs
}
