#+
#  SimHdrInfo.itcl
#
#  A simulated dhs header info class
#
#  D Terrett 25 October 2002
#
#  Copyright CCLRC
#+

itcl::class SimHdrInfo {
   public {
      constructor {args} {eval configure $args}
      method sendbefore {} {puts "simulate before headers->dhs"}
      method sendafter {} {puts "simulate after headers->dhs"}
      method sendfinal {} {puts "simulate final headers->dhs"}
      variable guideWith
      variable observeType
      variable useGpol 0
   }
   private {
      variable label
   }
}

itcl::body SimHdrInfo::constructor {} {
   set label [format "%05d" [expr { int(100000.0 * rand()) }]]
}

itcl::body SimHdrInfo::sendbefore {} {
   puts "simulate before headers->dhs"

# Fake a new DHS data label.
   set ::dhshdr::dhslabel [incr label]
}
