#+
#  SimInst.itcl
#
#  A SimInst object simulates a real Instrument object in the absence of a 
#  real instrument.
#
#  See the method bodies for information on what a real instrument object
#  has to implement.
#
#  D Terrett 29 January 2002
#
#  Copyright CCLRC
#+

itcl::class SimInst {
   public {
      constructor {args} {eval configure $args}
      destructor {}
      method abort {}
      method stop {}
      method continue {{whendone ""}}
      method description {} {return ""}
      method endobserve {}
      method setup {whendone}
      method observe {label whendone}
      method pause {}
      variable description ""
      variable observeType ""
      variable object ""
      variable agname ""
      variable sfname ""
      variable dhsobj ""
      variable instobj "" 
   }
   private {
      variable afterid ""
      variable doneproc ""
   }
}

itcl::body SimInst::destructor {} {
   if { $afterid != "" } {
       after cancel $afterid
   }
}

itcl::body SimInst::stop {} {

# Sends a "stop" sequence command to the instrument.
    puts "simulate stop->instrument"

# Kill the timer.
   after cancel $afterid

# Invoke the done procedure with a failure status.
   if { $doneproc != "" } {
      lappend ::Sequence::errormsg "observation was stopped by user"
      after idle $doneproc 0
   }
   return 1
}

itcl::body SimInst::abort {} {

# Sends an "abort" sequence command to the instrument.
    puts "simulate abort->instrument"

# Kill the timer.
   after cancel $afterid

# Invoke the done procedure with a failure status.
   if { $doneproc != "" } {
      lappend ::Sequence::errormsg "observation was aborted by user"
      after idle $doneproc 0
   }
   return 1
}

itcl::body SimInst::continue {{whendone ""}} {

if {![string is space $whendone]} {
   set doneproc $whendone
   }
   
# Sends a "continue" sequence command to the instrument.
   puts "simulate continue->instrument"
   if { $doneproc != "" } {
      set afterid [after 10000 $doneproc 1]
   }
   return 1
}

itcl::body SimInst::endobserve {} {

# Sends an "endObserve" sequence command to the instrument.
   puts "simulate endObserve->instrument"
   return 1
}


itcl::body SimInst::observe {label whendone} {

# Sends an "observe" sequence command to the instrument with the DHS
# label set to $label and calls the $whendone script when the exposure 
# has finished.

# Execute the whendone script 2 seconds in the future.
puts "simulate observe->instrument"
   set doneproc $whendone
   set afterid [after 2000 $whendone 1]
   return 1
}

itcl::body SimInst::pause {} {

# Sends a "pause" sequence command to the instrument.

puts "simulate pause->instrument"

# Kill the timer.
   after cancel $afterid
   return 1
} 

itcl::body SimInst::setup {whendone} {

# Configures the instrument ready to take an exposure.

# Execute the whendone script 3 seconds in the future.
   puts "simulate configuring instrument"
   set afterid [after 3000 $whendone 1]
   return 1
}
