#+
#  SimTcs.itcl
#
#  A SimTcs object simulates a real Tcs object in the absence of a TCS.
#
#  D Terrett 10 October 2002
#
#  Copyright CCLRC
#+

itcl::class SimTcs {
   public {
      constructor {args} {eval configure $args}
      method endobserve {} {puts "simulate endObserve->tcs";return 1}
      method move {whendone} {
         puts "simulate moving telescope"
         after idle $whendone 1
         return 1
      }
      method continue {} {puts "simulate continue->tcs";return 1}
      method observe {} {puts "simulate observe->tcs";return 1}
      method pause {} {puts "simulate pause->tcs";return 1}
   }
}
