#+
#  TrecsInst.itcl
#
#  This is the TRECS specific version of the instrument class.
#
#  Matthieu Bec - 19 November 2002
#
#+

package require Trecs

itcl::class TrecsInst {
   inherit GenericInst
   public {
      constructor {} {}
      destructor {}
      method observe {label whendone}
      method continue {whendone}
      method setup {whendone}
      variable nodflag none  ;# one of none/first/middle/last
      }
   private {
      method obsoktest {}
      variable setupaction
   }
}

# Create the principle system objects for Trecs.

namespace eval TrecsInst {
   global Flags
   global env
   seq::PrincipalSystem TRECS trecs::apply -debug $Flags(traceinst)  \
         -simulate 0 -delay 100
}

itcl::body TrecsInst::constructor {} {

# Set the public variables used to determine the science fold position.
   set agname TRECS
   set sfname trecs

# Set the protected variables used by the generic instrument methods to the
# name of the principle system used by the observe action and the prefix
# for the sequence commands.
   set psys TrecsInst::TRECS
   set prefix trecs

# Create the instrument configuration object. The fully qualified namespace 
# has to be used so that the object is accessible outside this class. The
# Trecs object is configured from the parameter settings in the sequence
# file by the Sequence object as it is created.
   set instobj [namespace current]::[Trecs::Trecs #auto]

# Create the actions for configuring the instrument.
   set setupaction [seq::Action #auto TrecsInst::TRECS]
   $setupaction configure\
         -onerror [itcl::code $this setuperror] \
         -ontimeout [itcl::code $this setuptimeout] \
         -onok [itcl::code $this setupok] \
         -timeout 600
   $setupaction connect trecs::config

$instobj configDCaction [namespace current]::$setupaction

# Create the actions for observing and continuing. This actions needs to be 
# accessible to GenericInst so that it can restart an observation after a
# pause.
   set obsaction [namespace current]::[seq::Action #auto TrecsInst::TRECS]
   $obsaction configure -onerror [itcl::code $this obserror] \
         -ontimeout [itcl::code $this obstimeout] \
         -onok [itcl::code $this obsok] \
         -oktest [itcl::code $this obsoktest] \
         -waitvar trecs::observeStatus

# The timeout on the continue action is set by GenericInst.
   set contaction [namespace current]::[seq::Action #auto TrecsInst::TRECS]
   $contaction configure -onerror [itcl::code $this obserror] \
         -onok [itcl::code $this obsok] \
         -oktest [itcl::code $this obsoktest] \
         -waitvar trecs::observeStatus
   $contaction set trecs::continue dummy MARK
}

itcl::body TrecsInst::destructor {} {
   itcl::delete object $obsaction
   itcl::delete object $contaction
   itcl::delete object $setupaction
   itcl::delete object $instobj
}

itcl::body TrecsInst::observe {label whendone} {

#  Only proceed if an observe is not already in progress.
   if { $GenericInst::observing } {
      lappend Sequence::errormsg "Error sending observe: observe already in\
            progress"
      return 0
   }

# Save the done proc.
   set doneproc $whendone
      
# normal mode or first nod
   if {[string equal $nodflag none] || [string equal $nodflag first]} {
# Sends an "observe" sequence command to the instrument with the DHS
# label set to $label and calls the $whendone script when the exposure 
# has finished.

# Set the data label.
         $obsaction set ${prefix}::observe label $label

# Set the action timeout to the exposure time plus 5 minutes.
         $obsaction configure -timeout [$instobj calcTimeout]

# Post the observe command.
         $obsaction start

# Record that an observe is in progress and the time that it was started.
         set GenericInst::observing 1
         set GenericInst::starttime [clock seconds]
         return 1
   } else {
# Sends a "continue" sequence command to the instrument
   
# Set the action timeout to the exposure time plus 5 minutes.
         $contaction configure -timeout [$instobj calcTimeout]

# Post the observe command.
         $contaction set trecs::continue dummy MARK
         $contaction start

# Record that an observe is in progress and the time that it was started.
         set GenericInst::observing 1
         set GenericInst::starttime [clock seconds]
         return 1   
      }
   }

itcl::body TrecsInst::obsoktest {} {
   puts "obsoktest -> [sa trecs::status get observe]"
   if {[string equal $nodflag none] || [string equal $nodflag last]} {
      return [string equal IDLE [sa trecs::status get observe]]
   } else {
      return [string equal PAUSED [sa trecs::status get observe]]
   }
}

itcl::body TrecsInst::setup {whendone} {

# Configures the instrument ready to take an exposure.

#  Only proceed if an observe is not in progress.
   if { $GenericInst::observing } {
      lappend Sequence::errormsg "Error configuring instrument: observe\
            already in progress"
      return 0
   } else {

# Save the done proc.
      set doneproc $whendone

# Start the instrument sequencer setup action.
      $instobj apply detector
      return 1
   }
}
