int mod_scb_reg(int on, int off);
int write_dbus(int cen,int data);
int safe_devs(void);
int strobe_a2d();
int read_dbus(int scb);
int write_a2daddr(int addr);
int me_servo_cmd(int cmd, int srvonum, int *fval, int dir);
void mem_init(void);
int init_inst(void);
void control(void);
int strobe_a2d();
int arr_power(int anum, int state, char stdbuf[]);
int me_servo_cmd(int cmd, int srvonum, int *fval, int dir);
int sol_servo_cmd(int cmd, int srvonum, int *fval);
void *mem_alloc(int size);
int updpos(void);
int servo_delay(struct srvo_desc *sr, int srvonum, int *data, int *tout);
int init_inst(void);
int INSTcmndctrl(void);
void send_debug(char *format, ...);
