#+
#  Gmos::CC
#
#  Implements the GMOS components controller class. 
#
#  Options:
#
#  Methods:
#          apply args    Applies the configuration to the Acquisition 
#                        camera by setting the values of the command
#                        parameters. Any arguments are ignored.
#
#          init          Returns the object to its initial state.
#
#          save file     Writes the values of the configuration
#                        to the channel identifier "file".
#
#  D Terrett 24 July 2001
#+

itcl::class Gmos::CC {
   public {
      variable posAngle ""
      variable posAngleMode ""
      variable filter ""
      variable disperser ""
      variable disperserOrder ""
      variable disperserLambda ""
      variable fpuMode ""
      variable fpu ""
      variable fpuCustomMask ""
      variable stageMode ""
      variable adc ""
   }
   public {
      method apply args
      method init
      method save chan
      method configCCaction { action } { set ccaction $action }
      method configCClogcommand { logcommand } { set cclogcommand $logcommand }
   }
   private {
      method log {cs}
      variable disperserMode ""
      variable filter1 ""
      variable filter2 ""
      variable inbeam ""
      
      variable cclogcommand ""
      variable ccaction
   }
}

itcl::body Gmos::CC::apply args {

   set marked 0
   
   $ccaction unset gmos::config filter1
   $ccaction unset gmos::config filter2
   $ccaction unset gmos::config disperser
   $ccaction unset gmos::config disperserMode
   $ccaction unset gmos::config disperserOrder
   $ccaction unset gmos::config disperserLambda
   $ccaction unset gmos::config inbeam
   $ccaction unset gmos::config fpu
   $ccaction unset gmos::config stageMode

   set disperserModeIsSet 0
   
#    if { ![string is space $filter1] } {
#       set _filter1 [sa gmos::status get filter1 value]
#       if { ![string equal [string toupper $filter1] $_filter1] } {
#          puts stdout "filter1 $filter1"
#          $ccaction set gmos::config filter1 "$filter1"
#          set marked 1
#          }\
#       else {
#          puts stdout "filter1 already in place, skipping that config"
#          }
#       }
   
   
   if { ![string is space $filter2] } {
      set _filter2 [sa gmos::status get filter2 value]
      if { ![string equal $filter2 $_filter2] } {
         puts stdout "filter2 $filter2"
         $ccaction set gmos::config filter2 "$filter2"
         set marked 1
         }\
      else {
         puts stdout "filter2 already in place, skipping that config"
         }
      }
   
   
   if { ![string is space $disperser] } {
      set _disperser [sa gmos::status get disperser value]
      if { ![string equal [string toupper $disperser] $_disperser] } {
         puts stdout "disperser $disperser"
         $ccaction set gmos::config disperser "$disperser"
         set marked 1
         if { ![string is space $disperserMode] } {
            puts stdout "disperserMode $disperserMode"
            $ccaction set gmos::config disperserMode "$disperserMode"
            set marked 1
            set disperserModeIsSet 1
            }
         }\
      else {
         puts stdout "disperser already in place, skipping that config"
         }
      }
      
   if { ![string is space $disperserOrder] } {
      set _disperserOrder [sa gmos::status get disperserOrder value]
      if { ![string equal $disperserOrder $_disperserOrder] } {
         puts stdout "disperserOrder $disperserOrder"
         $ccaction set gmos::config disperserOrder "$disperserOrder"
         set marked 1
         if { ![string is space $disperserMode] && ! $disperserModeIsSet} {
            puts stdout "disperserMode $disperserMode"
            $ccaction set gmos::config disperserMode "$disperserMode"
            set marked 1
            set disperserModeIsSet 1
            }
         }\
      else {
         puts stdout "disperserOrder already in place, skipping that config"
         }
      }
   if { ![string is space $disperserLambda] } {
      set _disperserLambda [sa gmos::status get disperserLambda value]
      if { ![expr $disperserLambda == $_disperserLambda] } {
         puts stdout "disperserLambda $disperserLambda"
         $ccaction set gmos::config disperserLambda "$disperserLambda"
         set marked 1
         if { ![string is space $disperserMode] && ! $disperserModeIsSet} {
            puts stdout "disperserMode $disperserMode"
            $ccaction set gmos::config disperserMode "$disperserMode"
            set marked 1
            set disperserModeIsSet 1
            }
         }\
      else {
         puts stdout "disperserLambda already in place, skipping that config"
         }
      }
      
           
   if { ![string is space $inbeam] } {
      set _inbeam [sa gmos::status get inbeam value]
      if { $_inbeam == 0 } {
         set _inbeam IN-BEAM
         }\
      elseif { $_inbeam == -1 } {
         set _inbeam OUT-OF-BEAM
         puts "really out of the beam (readding -1)"
         }\
      elseif { $_inbeam == 1 } {
         set _inbeam OUT-OF-BEAM
         }
         
      if { ![string equal $inbeam $_inbeam ] } {
         puts stdout "inbeam $inbeam"
         $ccaction set gmos::config inbeam "$inbeam"
         set marked 1
         }\
      else {
         puts stdout "inbeam already in place, skipping that config"
         }
      }
      

   if { ![string is space $fpu] } {
      set _fpu [sa gmos::status get fpu value]
      if { ![string equal $fpu $_fpu] } {
         puts stdout "fpu $fpu"
         $ccaction set gmos::config fpu "$fpu"
         set marked 1
         }\
      else {
         puts stdout "fpu already in place, skipping that config"
         }
      }
      
      
   if { ![string is space $stageMode] } {
      set _stageMode [sa gmos::status get stageMode value]
      if { ![string equal $stageMode $_stageMode] } {
         puts stdout "stageMode $stageMode"
         $ccaction set gmos::config stageMode "$stageMode"
         set marked 1
         }\
      else {
         puts stdout "stageMode already in place, skipping that config"
         }
      }
   
   
   if { $marked } {
      $ccaction start
      }\
   else {
      after idle [$ccaction cget -onok]
      }
   
      
}

itcl::body Gmos::CC::save file {
}

itcl::body Gmos::CC::init {} {
}

itcl::body Gmos::CC::log {cs} {
   if { ![string is space $cclogcommand] } {
      uplevel #0 $cclogcommand $cs
   }
}


#==============================================================================
# posAngle
#==============================================================================
itcl::configbody Gmos::CC::posAngle {
   # Not used - probably sent over to tcs/agSeq
   puts stdout "ocssupport/gmos/scripts/CC.itcl >> posAngle ignored"
   }
#==============================================================================
# posAngleMode
#==============================================================================
itcl::configbody Gmos::CC::posAngleMode {
   # Not used - probably sent over to tcs/agSeq
   puts stdout "ocssupport/gmos/scripts/CC.itcl >> posAngleMode ignored"
   switch $posAngleMode {
      "Set Value" {
         
         }
      "Average Parallactic" {
         
         }
      "Follow Parallactic" {
         
         }
      default {
         set posAngleMode ""
         puts stdout "cannot set posAngleMode to $posAngleMode"
         }
      }
   }
#==============================================================================
# filter
#==============================================================================
itcl::configbody Gmos::CC::filter {
   switch $filter {
      "None" {
         #set filter1 open1-6
         set filter2 open2-8
         }
      default {
         #set  filter1 ""
         set  filter2 $filter
         }
      }
   }

#==============================================================================
# disperser
#==============================================================================
itcl::configbody Gmos::CC::disperser {

   switch $disperser {
      "Mirror" {
         set disperser "mirror"
         set disperserMode "Select Grating and Tilt"
         }
      "B600_G5303" {
         set disperser "B600+_G5303"
         set disperserMode "Select Grating and Tilt"
         }
      "B1200_G5301" {
         set disperser "B1200+_G5301"
         set disperserMode "Select Grating and Tilt"
         }
      "R831_G5302" {
         set disperser "R831+_G5302"
         set disperserMode "Select Grating and Tilt"
         }
      "R600_G5304" {
         set disperser "R600+_G5304"
         set disperserMode "Select Grating and Tilt"
         }
      "R400_G5305" {
         set disperser "R400+_G5305"
         set disperserMode "Select Grating and Tilt"
         }
      "R150_G5306" {
         set disperser "R150+_G5306"
         set disperserMode "Select Grating and Tilt"
         }
      default {
         set disperser ""
         set disperserMode ""
         puts stdout "cannot set disperser to $disperser"
         }
      }
   }
#==============================================================================
# 
#==============================================================================
itcl::configbody Gmos::CC::disperserOrder {
   switch $disperserOrder {
      "1"
         -
      "2" {
         set disperserMode "Select Grating and Tilt"
         }
      default {
         set disperserOrder ""
         puts stdout "cannot set disperserOrder to $disperserOrder"
         }
      }
   }
#==============================================================================
# 
#==============================================================================
itcl::configbody Gmos::CC::disperserLambda {
   # check for double
   if { ! [ string is double $disperserLambda] } {
      puts stdout "cannot set disperserLambda to $disperserLambda"
      set disperserLambda ""
      }\
   else {
      set disperserMode "Select Grating and Tilt"
      }
   }
#==============================================================================
# fpuMode
#==============================================================================
itcl::configbody Gmos::CC::fpuMode {
   # not usefull for seqexec ..
   switch $fpuMode {
      "Builtin" {
         }
      "Custom Mask" {
         }
      default {
         set fpuMode ""
         puts stdout "cannot set fpuMode to $fpuMode"
         }
      }
   }
#==============================================================================
# fpuCustomMask
#==============================================================================
itcl::configbody Gmos::CC::fpuCustomMask {
   if { ![string equal $fpuCustomMask None"] } {
      set inbeam "IN-BEAM"
      set fpu $fpuCustomMask
      }
   }
#==============================================================================
# fpu
#==============================================================================
itcl::configbody Gmos::CC::fpu {
   switch $fpu {
      "None" {
         set inbeam "OUT-OF-BEAM"
         }
      "Longslit 0.25 arcsec" {
         set inbeam "IN-BEAM"
         set fpu 0.25arcsec
         }
      "Longslit 0.50 arcsec" {
         set inbeam "IN-BEAM"
         set fpu 0.5arcsec
         }
      "Longslit 0.75 arcsec" {
         set inbeam "IN-BEAM"
         set fpu 0.75arcsec
         }
      "Longslit 1.00 arcsec" {
         set inbeam "IN-BEAM"
         set fpu 1.0arcsec
         }
      "Longslit 1.50 arcsec" {
         set inbeam "IN-BEAM"
         set fpu 1.5arcsec
         }
      "Longslit 2.00 arcsec" {
         set inbeam "IN-BEAM"
         set fpu 2.0arcsec
         }
      "Longslit 5.00 arcsec" {
         set inbeam "IN-BEAM"
         set fpu 5.0arcsec
         }
      "IFU 2 Slits" {
         set inbeam "IN-BEAM"
         set fpu IFU
         }
      "IFU Left Slit" {
         set inbeam "IN-BEAM"
         set fpu IFU
         }
      "IFU Left Slit (blue)" {
         set inbeam "IN-BEAM"
         set fpu IFU
         }
      "IFU Right Slit" {
        set inbeam "IN-BEAM"
        set fpu IFU
        }
      "IFU Right Slit (red)" {
         set inbeam "IN-BEAM"
         set fpu IFU
         }
      default {
        set inbeam ""
        set fpu ""
        puts stdout "cannot set fpu to $fpu"
        }
     }
   }
#==============================================================================
# stageMode
#==============================================================================
itcl::configbody Gmos::CC::stageMode {
   switch $stageMode {
      "Do Not Follow" {
         set stageMode MOVE
         }
      "Follow in XYZ(focus)" {
         set stageMode FOLLOW
         }
      "Follow in XY" {
         set stageMode FOLLOW-XY
         }
      default {
         set stageMode ""
         puts stdout "cannot set stageMode to $stageMode"
         }
      }
   }
#==============================================================================
# adc
#==============================================================================
itcl::configbody Gmos::CC::adc {
   puts stdout "ocssupport/gmos/scripts/CC.itcl >> adc ignored in current release"
   switch $adc {
      "No Correction" {
         
         }
      "Best Static Correction" {
         
         }
      "Follow During Exposure" {
         
         }
      default {
         set adc ""
         puts stdout "cannot set adc to $adc"
         }
      }
   }
   
