#+
#  Gmos::DC
#
#  Implements the Acquisition camera detector controller class. 
#
#  Options:
#
#  Methods:
#          apply args    Applies the configuration to the Acquisition 
#                        camera by setting the values of the command
#                        parameters. Any arguments are ignored.
#
#          init          Returns the object to its initial state.
#
#          save file     Writes the values of the configuration
#                        to the channel identifier "file".
#
#  D Terrett 24 July 2001
#+

itcl::class Gmos::DC {
   public {
      variable exposureTime ""
      variable ampReadMode ""
      variable gainChoice ""
      variable ampCount ""
      variable gainSetting ""
      variable ccdXBinning ""
      variable ccdYBinning "" 
      variable builtinROI ""
      variable observeType ""
      variable nsState ""
      variable nsRows ""
      method calcTimeout {}
   }
   public {
      method apply args
      method init
      method save chan
      method configDCaction { action } { set dcaction $action }
      method configDClogcommand { logcommand } { set dclogcommand $logcommand }
   }
   private {
      method log {cs}
      variable gainSettingIsSet 0
      variable ccdXstart "" 
      variable ccdXsize "" 
      variable ccdYstart "" 
      variable ccdYsize "" 
      variable shutterState ""
      variable biasTime ""

      variable dclogcommand ""
      variable dcaction
   }
}

itcl::body Gmos::DC::apply args {

   set marked 0
   
   $dcaction unset gmos::dcconfig nsState
   $dcaction unset gmos::dcconfig nsRows
   $dcaction unset gmos::dcconfig exposureTime
   $dcaction unset gmos::dcconfig shutterState
   $dcaction unset gmos::dcconfig ampReadMode
   $dcaction unset gmos::dcconfig gainSetting
   $dcaction unset gmos::dcconfig ampCount
   $dcaction unset gmos::dcconfig ccdXstart
   $dcaction unset gmos::dcconfig ccdXsize
   $dcaction unset gmos::dcconfig ccdXBinning
   $dcaction unset gmos::dcconfig ccdYstart
   $dcaction unset gmos::dcconfig ccdYsize
   $dcaction unset gmos::dcconfig ccdYBinning

   if { [string is space $observeType] } {
      # try and get it from the display
      if [info exists dhshdr::obstype] {
         $this configure -observeType $dhshdr::obstype
         }
      }

   #--- nsState
   if { ![string is space $nsState] } {
      set _nsState [sa gmos::dcstatus get nsState value]
      if { ![string equal $nsState $_nsState] } {
         puts stdout "nsState $nsState"
         $dcaction set gmos::dcconfig nsState "$nsState"
         set marked 1
         }\
      else {
         puts stdout "nsState already in place, skipping that config"
         }
      }


   #--- nsRows
   if { ![string is space $nsRows] } {
      set _nsRows [sa gmos::dcstatus get nsRows value]
      if { ![string equal $nsRows $_nsRows] } {
         puts stdout "nsRows $nsRows"
         $dcaction set gmos::dcconfig nsRows "$nsRows"
         set marked 1
         }\
      else {
         puts stdout "nsRows already in place, skipping that config"
         }
      }

   #--- exposureTime
   if { ![string is space $exposureTime] } {
      set _exposureTime [sa gmos::dcstatus get exposureTime value]
      if { $exposureTime != $_exposureTime } {
         puts stdout "exposureTime $exposureTime"
         $dcaction set gmos::dcconfig exposureTime "$exposureTime"
         set marked 1
         }\
      else {
         puts stdout "exposureTime already in place, skipping that config"
         }
      }

   #---  bias override ?
   if { ![string is space $biasTime] } {
      set _exposureTime [sa gmos::dcstatus get exposureTime value]
      if { ![string equal $biasTime $_exposureTime] } {
         puts stdout "using biasTime $biasTime"
         $dcaction set gmos::dcconfig exposureTime "$biasTime"
         set marked 1
         }\
      else {
         puts stdout "using biasTime already in place, skipping that config"
         }
      }

   #--- shutterState
   if { ![string is space $shutterState] } {
      set _shutterState [sa gmos::dcstatus get shutterState value]
      if { ![string equal $shutterState $_shutterState] } {
         puts stdout "shutterState $shutterState"
         $dcaction set gmos::dcconfig shutterState "$shutterState"
         set marked 1
         }\
      else {
         puts stdout "shutterState already in place, skipping that config"
         }
      }

      
   #--- ampReadMode
   if { ![string is space $ampReadMode] } {
      set _ampReadMode [sa gmos::dcstatus get ampReadMode value]
      if { ![string equal $ampReadMode $_ampReadMode] } {
         puts stdout "ampReadMode $ampReadMode"
         $dcaction set gmos::dcconfig ampReadMode "$ampReadMode"
         set marked 1
         }\
      else {
         puts stdout "ampReadMode already in place, skipping that config"
         }
      }
      
   #--- gainSetting
   set newgainSetting ""
   
   if { $gainSettingIsSet } {
      set newgainSetting $gainSetting
      }\
   else {
      if { [string equal $ampReadMode SLOW] &&  [string equal $gainChoice Low ] } {
         set newgainSetting 2
         }\
      elseif { [string equal $ampReadMode SLOW] &&  [string equal $gainChoice High ] } {
         set newgainSetting 1
         }\
      elseif { [string equal $ampReadMode FAST] &&  [string equal $gainChoice Low ] } {
         set newgainSetting 6
         }\
      elseif { [string equal $ampReadMode FAST] &&  [string equal $gainChoice High ] } {
         set newgainSetting 5
         }
      }
      
   if { ![string is space $newgainSetting] } {
      set _gainSetting [sa gmos::dcstatus get gainSetting value]
      if { ![string equal $newgainSetting $_gainSetting] } {
         puts stdout "gainSetting $newgainSetting"
         $dcaction set gmos::dcconfig gainSetting "$newgainSetting"
         set marked 1
         }\
      else {
         puts stdout "gainSetting already in place, skipping that config"
         }
      }
      
      
   #--- ampCount
   if { ![string is space $ampCount] } {
      set _ampCount [sa gmos::dcstatus get ampCount value]
      if { ![string equal $ampCount $_ampCount] } {
         puts stdout "ampCount $ampCount"
         $dcaction set gmos::dcconfig ampCount "$ampCount"
         set marked 1
         }\
      else {
         puts stdout "ampCount already in place, skipping that config"
         }
      }
      
   #--- binning

   if { ![string is space $ccdXBinning] } {
      if { [string is space $ccdXsize] } {
         set _ccdXBinning [sa gmos::dcstatus get ccdXBinning value]
         set ccdXsize [sa gmos::dcstatus get ccdXsize value]
         set ccdXsize [expr $ccdXsize * $_ccdXBinning]
         }
      set ccdXsize_out [ expr $ccdXsize / $ccdXBinning]
	   }\
   else {
      set ccdXsize_out $ccdXsize
      }

   if { ![string is space $ccdYBinning] } {
      if { [string is space $ccdYsize] } {
         set _ccdYBinning [sa gmos::dcstatus get ccdYBinning value]
         set ccdYsize [sa gmos::dcstatus get ccdYsize value]
         set ccdYsize [expr $ccdYsize * $_ccdYBinning]
         }
      set ccdYsize_out [ expr $ccdYsize / $ccdYBinning]
	   }\
   else {
      set ccdYsize_out $ccdYsize
      }
      

   #--- ccdXstart
   if { ![string is space $ccdXstart] } {
      set _ccdXstart [sa gmos::dcstatus get ccdXstart value]
      if { ![string equal $ccdXstart $_ccdXstart] } {
         puts stdout "ccdXstart $ccdXstart"
         $dcaction set gmos::dcconfig ccdXstart "$ccdXstart"
         set marked 1
         }\
      else {
         puts stdout "ccdXstart already in place, skipping that config"
         }
      }
   #--- ccdXsize
   if { ![string is space $ccdXsize_out] } {
      set _ccdXsize [sa gmos::dcstatus get ccdXsize value]
      if { ![string equal $ccdXsize_out $_ccdXsize] } {
         puts stdout "ccdXsize $ccdXsize_out"
         $dcaction set gmos::dcconfig ccdXsize "$ccdXsize_out"
         set marked 1
         }\
      else {
         puts stdout "ccdXsize already in place, skipping that config"
         }
      }
   #--- ccdXBinning
   if { ![string is space $ccdXBinning] } {
      set _ccdXBinning [sa gmos::dcstatus get ccdXBinning value]
      if { ![string equal $ccdXBinning $_ccdXBinning] } {
         puts stdout "ccdXBinning $ccdXBinning"
         $dcaction set gmos::dcconfig ccdXBinning "$ccdXBinning"
         set marked 1
         }\
      else {
         puts stdout "ccdXBinning already in place, skipping that config"
         }
      }
   #--- ccdYstart
   if { ![string is space $ccdYstart] } {
      set _ccdYstart [sa gmos::dcstatus get ccdYstart value]
      if { ![string equal $ccdYstart $_ccdYstart] } {
         puts stdout "ccdYstart $ccdYstart"
         $dcaction set gmos::dcconfig ccdYstart "$ccdYstart"
         set marked 1
         }\
      else {
         puts stdout "ccdYstart already in place, skipping that config"
         }
      }
   #--- ccdYsize
   if { ![string is space $ccdYsize_out] } {
      set _ccdYsize [sa gmos::dcstatus get ccdYsize value]
      if { ![string equal $ccdYsize_out $_ccdYsize] } {
         puts stdout "ccdYsize $ccdYsize_out"
         $dcaction set gmos::dcconfig ccdYsize "$ccdYsize_out"
         set marked 1
         }\
      else {
         puts stdout "ccdYsize already in place, skipping that config"
         }
      }
   #--- ccdYBinning
   if { ![string is space $ccdYBinning] } {
      set _ccdYBinning [sa gmos::dcstatus get ccdYBinning value]
      if { ![string equal $ccdYBinning $_ccdYBinning] } {
         puts stdout "ccdYBinning $ccdYBinning"
         $dcaction set gmos::dcconfig ccdYBinning "$ccdYBinning"
         set marked 1
         }\
      else {
         puts stdout "ccdYBinning already in place, skipping that config"
         }
      }

   if { $marked } {
      $dcaction start
      }\
   else {
      after idle [$dcaction cget -onok]
      }
   
}

itcl::body Gmos::DC::save file {
}

itcl::body Gmos::DC::init {} {
}

itcl::body Gmos::DC::log {cs} {
   if { ![string is space $dclogcommand] } {
      uplevel #0 $dclogcommand $cs
   }
}
#=============================================================================
#builtinROI
#=============================================================================
itcl::configbody Gmos::DC::builtinROI {
   switch $builtinROI {
      "Full Frame Readout" {
		     set ccdXstart 1
		     set ccdXsize 6144
		     set ccdYstart 1
		     set ccdYsize 4608
        }
      "CCD 2" {
                     set ccdXstart 2049
                     set ccdXsize 2048
                     set ccdYstart 1
                     set ccdYsize 4608
         }
      "Central Spectrum" {
                     set ccdXstart 1
                     set ccdXsize 6144
                     set ccdYstart 1792
                     set ccdYsize 1024
         }
      "Central Stamp" {
                     set ccdXstart 2922
                     set ccdXsize 300
                     set ccdYstart 2154
                     set ccdYsize 300
         }
      "Top Spectrum" {
                     set ccdXstart 1
                     set ccdXsize 6144
                     set ccdYstart 3328
                     set ccdYsize 1024
         }
      "Bottom Spectrum" {
                     set ccdXstart 1
                     set ccdXsize 6144
                     set ccdYstart 256
                     set ccdYsize 1024
         }
      default {
         puts stdout "cannot set builtinROI to $builtinROI"
         set builtinROI ""
	 }
	}
  }    
#==============================================================================
# exposureTime
#==============================================================================
itcl::configbody Gmos::DC::exposureTime {
   # check for double, will truncate to int
   if { ! [ string is double $exposureTime] } {
      puts stdout "cannot set exposureTime to $exposureTime"
      set exposureTime ""
      }
   }

#==============================================================================
# nsState
#==============================================================================
itcl::configbody Gmos::DC::nsState {
   puts stdout "Gmos::DC::nsState $nsState"
   switch $nsState {
      CLASSICAL -
      NS_FIRST -
      NS_MIDDLE -
      NS_LAST {}
      default {
         puts stdout "cannot set nsState to $nsState"
         set nsState ""
         }
      }
   }

#==============================================================================
# nsRows
#==============================================================================
itcl::configbody Gmos::DC::nsRows {
   # check for double, will truncate to int
   if { ! [ string is int $nsRows] } {
      puts stdout "cannot set nsRows to $nsRows"
      set nsRows ""
      }
   }

#==============================================================================
# ampReadMode
#==============================================================================
itcl::configbody Gmos::DC::ampReadMode {
   switch $ampReadMode {
      "Slow" {
         set ampReadMode SLOW
         }
      "Fast" {
         set ampReadMode FAST
         }
      default {
         puts stdout "cannot set ampReadMode to $ampReadMode"
         set ampReadMode ""
	 }
      }
   }
#==============================================================================
# gainChoice
#==============================================================================
itcl::configbody Gmos::DC::gainChoice {
   switch $gainChoice {
      "Low"
         -
      "High" {
         
         }
      default {
         puts stdout "cannot set gainChoice to $gainChoice"
         set gainChoice ""
	 }
      }
   }

#==============================================================================
# ampCount
#==============================================================================
itcl::configbody Gmos::DC::ampCount {
   switch $ampCount {
      "Three" {
         set ampCount BEST
         }
      "Six" {
         set ampCount ALL
         }
      default {
         puts stdout "cannot set ampCount to $ampCount"
         set ampCount ""
	 }
      }
   }
#==============================================================================
# gainSetting
#==============================================================================
itcl::configbody Gmos::DC::gainSetting {
   switch $gainSetting {
      "1"
         -
      "2"
         -
      "5"
         -
      "6" {
         set gainSettingIsSet 1
         }
      default {
         puts stdout "cannot set gainSetting to $gainSetting"
         set gainSettingIsSet 0
         }
      }
  }
#==============================================================================
# ccdXBinning
#==============================================================================
itcl::configbody Gmos::DC::ccdXBinning {
   switch $ccdXBinning {
      "1"
         -
      "2"
         -
      "4" {
         }
      default {
         puts stdout "cannot set ccdXBinning to $ccdXBinning"
         set ccdXBinning ""
         }
      }
   }
#==============================================================================
# ccdYBinning
#==============================================================================
itcl::configbody Gmos::DC::ccdYBinning {
   switch $ccdYBinning {
      "1"
         -
      "2"
         -
      "4" {
         }
      default {
         puts stdout "cannot set ccdYBinning to $ccdYBinning"
         set ccdYBinning ""
         }
      }
   }
#==============================================================================
# observeType
#==============================================================================
itcl::configbody Gmos::DC::observeType {
   switch $observeType {
      "OBJECT"
         -
      "FLAT"
         -
      "ARC" {
         set shutterState OPEN
         set biasTime ""
         }
      "DARK" {
         set shutterState CLOSED
         set biasTime ""
         }
      "BIAS" {
         set shutterState CLOSED
         set biasTime 1
         }
      default {
         set biasTime ""
         set shutterState ""
         }
	   }
   }
      
#==============================================================================
# calcTimeout
#==============================================================================
itcl::body Gmos::DC::calcTimeout {} {
   # always get timeout from the DC (ie. when people press OBSERVE on a dm configured system)
   set timeout [expr int( $gmos::exposureTime + 300 )]
   return $timeout
   }
