#+
#  Observe
#
#  An observe object controls a GMOS observation
#
#  Options:
#           -gmos              The name of an Gmos object for configuring
#                              the camera.
#
#  Methods:
#           start               Starts an observation
#
#           stop                Stops an observation
#
#           abort               Aborts an observation
#
#  D Terrett 24 July 2001
#
#  Copyright CCLRC
#+

itcl::class Gmos::Observe {
   public {
      constructor {args} {eval configure $args}
      method start {dhslabel}
      method stop {}
      method abort {}
      method end {}
      variable gmos ""
   }
}

itcl::body Gmos::Observe::start {dhslabel} {
   cs gmos::observe set label  $dhslabel
   if { ![string is space $gmos] } {
      $gmos apply
      cs gmos::apply postWait
   }
}

itcl::body Gmos::Observe::stop {} {
   cs gmos::stop set dummy value 1
   cs gmos::apply post
}

itcl::body Gmos::Observe::abort {} {
   cs gmos::abort set dummy value 1
   cs gmos::apply post
}

itcl::body Gmos::Observe::end {} {
   cs gmos::endObserve set dummy value mark
   cs gmos::apply postWait
}

