# $Id: Makefile.Unix,v 1.2 2009/05/27 19:34:08 fkraemer Exp $

# Include file identifying the target architecture (defines the T_A
# macro) and application configuration definitions
#
# NOTE:  This Makefile does not include the standard EPICS rules for
# installing files, because the standard rules strip off paths from
# file names, which makes it impossible to install data in
# subdirectories.
#

include Target.include
include .applTop/config/CONFIG

# DATA are installed in INSTALL_DATA
DATA = \
	$(wildcard ../*.pv ../*.lut ../*.ste) \
	$(wildcard ../cold/*.pv ../cold/*.lut) \
	$(wildcard ../null/*.pv ../null/*.lut) \
	$(wildcard ../sim/*.pv ../sim/*.lut) \
	$(wildcard ../warm/*.pv ../warm/*.lut) \

$(INSTALL_DATA)/cold/STAMP:
	@test -d $(INSTALL_DATA)/cold || { \
		echo Creating $(INSTALL_DATA)/cold; \
		mkdir -p $(INSTALL_DATA)/cold; \
	}
	@touch $@

$(INSTALL_DATA)/warm/STAMP:
	@test -d $(INSTALL_DATA)/warm || { \
		echo Creating $(INSTALL_DATA)/warm; \
		mkdir -p $(INSTALL_DATA)/warm; \
	}
	@touch $@

$(INSTALL_DATA)/sim/STAMP:
	@test -d $(INSTALL_DATA)/sim || { \
		echo Creating $(INSTALL_DATA)/sim; \
		mkdir -p $(INSTALL_DATA)/sim; \
	}
	@touch $@

$(INSTALL_DATA)/null/STAMP:
	@test -d $(INSTALL_DATA)/null || { \
		echo Creating $(INSTALL_DATA)/null; \
		mkdir -p $(INSTALL_DATA)/null; \
	}
	@touch $@

$(INSTALL_DATA)/cold/%: ../cold/% $(INSTALL_DATA)/cold/STAMP
	@cp ../cold/$* $@
	@echo Installing $@

$(INSTALL_DATA)/warm/%: ../warm/% $(INSTALL_DATA)/warm/STAMP
	@cp ../warm/$* $@
	@echo Installing $@

$(INSTALL_DATA)/sim/%: ../sim/% $(INSTALL_DATA)/sim/STAMP
	@cp ../sim/$* $@
	@echo Installing $@

$(INSTALL_DATA)/null/%: ../null/% $(INSTALL_DATA)/null/STAMP
	@cp ../null/$* $@
	@echo Installing $@

$(INSTALL_DATA)/%: ../%
	@cp ../$* $@
	@echo Installing $@

# Any extra targets can be placed in a TARGETS macro (the build target
# builds only pre_build, LIBNAME, TARGETS and PROD, not SCRIPTS, INC etc)

TARGETS	= $(patsubst ../%, $(INSTALL_DATA)/%, $(DATA))

install: $(TARGETS)

clean:
	rm -f $(TARGETS)
