#! /bin/sh

#
# This script is used by the Makefiles to make the following substitutions
# to a text file:
#
#     @(prefix) is replaced by the shell variable ${prefix}
#     @(name) is replaced by the shell variable ${name}
#

. .applTop/config.par

sed \
	-e "s/@(prefix)/${prefix}/g" \
	-e "s/@(name)/${name}/g"
