#! /bin/csh -f
#
#   Script checkVal
#
#  Returns 1 if an error and the string ${GMOS_ERRSTRING} 
#  was found in current apply.MESS
#  Returns 0 if no error, or error with string not ${GMOS_ERRSTRING}
#
if ($GMOS_PREFIX == "") then
  echo 'Error: environment variable GMOS_PREFIX undefined'
  exit 1
endif

# First wait for apply.VAL to change
set oval = `caget -n ${GMOS_PREFIX}apply.VAL`; shift oval
set val = $oval
set count = 0
while (($val == $oval) && ($count < 5))
  set val = `caget -n ${GMOS_PREFIX}apply.VAL`; shift val
  @ count++
  sleep 1
end
echo "apply.VAL = $val"
#
# Check if apply VAL OK. 
#
if ($val >= 0) then
  exit 0
endif
#
# Exit now if ${GMOS_ERRSTRING} undefined
#
if (!($?GMOS_ERRSTRING)) then
  exit 1
endif
#
# If failed, see if the string is the one expected
# Return 1 if it is the expected error string, zero if
# some other error
#
set mess = `caget ${GMOS_PREFIX}apply.MESS`
shift mess
echo $mess
set x = `echo $mess | grep "${GMOS_ERRSTRING}" | wc -l`
if ($x > 0) then
  exit 1
else
  exit 0
endif
exit
