#! /bin/csh -f
#
alias caput "caput -ts"
if ($1 == "") then
  echo "Usage : doCadWait cadname timeout <p1 p2 p3 p4 p5 p6>"
  echo '   (Assumes environment variable $GMOS_PREFIX defined)'
  exit 1
endif
if ($GMOS_PREFIX == "") then
  echo 'Error: environment variable GMOS_PREFIX undefined'
  exit 1
endif
caput ${GMOS_PREFIX}apply.DIR CLEAR
sleep 1
caput ${GMOS_PREFIX}$1.DIR MARK 
set timeout = $2
if ($3 != "") then
  caput ${GMOS_PREFIX}$1.A $3
endif
if ($4 != "") then
  caput ${GMOS_PREFIX}$1.B $4
endif
if ($5 != "") then
  caput ${GMOS_PREFIX}$1.C $5
endif
if ($6 != "") then 
  caput ${GMOS_PREFIX}$1.D $6
endif
if ($7 != "") then 
  caput ${GMOS_PREFIX}$1.E $7
endif
if ($8 != "") then 
  caput ${GMOS_PREFIX}$1.F $8
endif
echo "Issuing START for CAD $1"
caput ${GMOS_PREFIX}apply.DIR START
checkVal
set retval = $status
# Wait for applyC to go BUSY
#
set count = 0
set carval = `caget -n ${GMOS_PREFIX}applyC`
shift carval
#
# Wait a second if not yet BUSY, then give up
#
if ($carval != 2) then
  sleep 1
endif
set carval = `caget -n ${GMOS_PREFIX}applyC`
shift carval
if ($carval != 2) then
  echo "doCadWait: applyC not BUSY"
  exit 0
endif
# Is BUSY, now loop until not BUSY
while (($carval == 2) && ($count < $timeout)) 
  set carval = `caget -n ${GMOS_PREFIX}applyC`
  shift carval
  @ count++
end
echo "Loop count: $count "
# Check for timeout or error in applyC CAR value
if ($count == $timeout) then
  echo "CAD $1 timed out ($timeout)"
  set retval = 1
else if ($carval == 3) then
  set omss = `caget -n ${GMOS_PREFIX}applyC.OMSS`; shift omss
  echo "CAD $1. applyC ERROR: $omss "
  set retval = 1
endif
#
exit $retval
