#! /bin/csh -f
#
#     waitApply 
#
#     Wait for applyC to go not BUSY
#
alias caput "caput -ts"
if ($GMOS_PREFIX == "") then
  echo 'Error: environment variable GMOS_PREFIX undefined'
  exit 1
endif
set retval = 0
# Wait for applyC to go BUSY
#
set count = 0
set carval = `caget -n ${GMOS_PREFIX}applyC`
shift carval
#
# Wait a second if not yet BUSY, then give up
#
if ($carval != 2) then
  sleep 1
endif
set carval = `caget -n ${GMOS_PREFIX}applyC`
shift carval
if ($carval != 2) then
  echo "waitApply: applyC not BUSY"
  exit 0
endif
# Is BUSY, now loop until not BUSY
while (($carval == 2) && ($count < 10000)) 
  set carval = `caget -n ${GMOS_PREFIX}applyC`
  shift carval
  @ count++
end
echo "Loop count: $count "
# Check for timeout or error in applyC CAR value
if ($count == 10000) then
  echo "waitApply timed out "
  set retval = 1
else if ($carval == 3) then
  set omss = `caget -n ${GMOS_PREFIX}applyC.OMSS`; shift omss
  echo "applyC ERROR: $omss "
  set retval = 1
endif
#
exit $retval
