#!/bin/csh -f
  set files = "$*"
   if ( "$files" != "" ) then

               foreach file ( $files )

                  set base = `basename $file .sch`
                  echo "Converting $base.sch into $base.ps"
                  schplot -t $base.sch | schps -d -wi 10.5 | lpr -Plw35
               end
   else
      echo Usage - update_ps file1 file2 file3...
   endif





# Type "source prScc" to execute
#alias sch2lp   "schplot -t  \!* | schps -d -wi 10.5 | lpr -Plw10"


#sch2lp abortCad.sch
#sch2lp continueCad.sch
#sch2lp	dcSetupCad.sch
#sch2lp dcTop.sch
#sch2lp debugCad.sch
#sch2lp initCad.sch
#sch2lp	initWcsCad.sch
#sch2lp noOpApply.sch
#sch2lp noOpCmd.sch
#sch2lp observeCad.sch
#sch2lp parkCad.sch
#sch2lp pauseCad.sch
#sch2lp rebootCad.sch
#sch2lp	 roiCad.sch
#sch2lp sadIntrfc.sch
#sch2lp sccdTop.sch
#sch2lp setDhsInfoCad.sch
#sch2lp setupApply.sch
#sch2lp setWcsCad.sch
#sch2lp stateApply.sch
#sch2lp stopCad.sch
#sch2lp sysCar.sch
#sch2lp sysApply.sch
#sch2lp testCad.sch
