
static struct {
        void *v;
        char *c;
} rcsid = {
        &rcsid,
        "$Id: gnRpcClient.c,v 1.2 2009/05/27 19:32:25 fkraemer Exp $"
};




/* @(#)epdq_func.c	2.1 88/08/11 4.0 RPCSRC */
/*
 * gnRpcClient.c: remote (client) versions of DQ RPC functions
 * These run on the EPICS IOC and call functions on the Data coadder 68040
 * 
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <vxWorks.h>
#include <rpcLib.h>
#include <rpc/rpc.h>	       /* always need this */
#include <epdq.h>	       /* need this too: will be generated by rpcgen*/
#include <cicsLib.h>

#include <semLib.h>
/* #define DEBUG */
#include "debug.h"
#define DQSERVERNAMELEN 256
char *rpcServer;
static char dqServer[DQSERVERNAMELEN];  /* Name of machine with Data coadder RPC 
                                           routines */

/* static CLIENT *cl = NULL; */
static SEM_ID rpcSem = NULL;
char tmp[80];

void setRPCServer(char *server)
{
    rpcServer = malloc(strlen(server));
    strcpy(rpcServer,server);
}
int dqRpcInit(char *server) 
{
    char tmp[80];
    int status = OK;

    if(rpcSem == NULL)
	rpcSem = semBCreate( SEM_Q_FIFO, SEM_FULL  ) ;

    if (server == NULL)
    {
	sprintf(tmp, "usage: dqRpcInit \"DQ RPC Server Name\"\n");
	cicsLogMessage(0,tmp);
	DPRINT(1,tmp);
	status = ERROR;
    }
    else
    {
	strncpy(dqServer, server, DQSERVERNAMELEN);
	if (rpcTaskInit() != OK)

	{
	    /*  dqRpcInitialized = FALSE;  */
	    sprintf(tmp,"dqRpcInit taskInit FAILED\n");
	    cicsLogMessage(0,tmp );
	DPRINT(1,tmp);
	    status = ERROR;
	}
    }

    return status;
}

int dqRpcGetClient(CLIENT **cl) 
{
    int status = OK;

 
	/* Create client "handle" used for calling routine on the
	 * server designated on the command line. We tell the rpc package
	 * to use the "tcp" protocol when contacting the server.
	 */
	if(*cl == NULL)  
	{
	
	    *cl = clnt_create(dqServer, EPDQPROG, EPDQVERS, "tcp");
	    if (*cl == (CLIENT *) NULL)
	    {
	      printf("error in clnt_create\n");
		/* Couldn't establish connection with server.
		 * Print error message and die.
		 */
		clnt_pcreateerror(dqServer);
		status = ERROR;
	    }
	}
/*     cicsLogMessage(3,"exit getClient\n"); */
    return status;
}

/* start an observation on the Data coadder */
int dqObserveRPC()
{
  
     CLIENT *cl = NULL;     
    int *result, retval = OK;
    int i = 0;
  
    semTake (rpcSem,WAIT_FOREVER);
  
    /* get RPC client handle & perform call */ 
    if ((dqRpcGetClient(&cl) == ERROR) || (cl == (CLIENT *) NULL)) 
  
    {
	sprintf(tmp, "ERROR %s: unable to connect to RPC server %s\n",
		"dqObserve", dqServer);

	cicsLogMessage(0,tmp);
	DPRINT(1,tmp);
	perror("dqObserveRpc");
	retval = ERROR;
    }
    else
    {

  
	/* Call the remote procedure on the server */
	result = dqobserverpc_1(&i, cl);
	if (result == (int *) NULL)
	{
	    clnt_destroy(cl);  
	    cl = NULL;
	    if ((dqRpcGetClient(&cl) == ERROR) || (cl == (CLIENT *) NULL)) 
	    { 
             /* An error occurred while calling the server. 
	     * Print error message and die.
	     */
/* 		cicsLogMessage(3," observe "); */
		clnt_perror(cl, dqServer );
		retval =  ERROR;
	    }
	    else
		result = dqobserverpc_1(&i, cl);
	    if (result == (int *) NULL)
	    {
/* 		cicsLogMessage(3," observe "); */
		clnt_perror(cl, dqServer );
		retval =  ERROR;
	    }
	
	}
	/* Okay, we successfully called the remote procedure, handle result. */
	else if (*result == 0)   /* server routine failed */
	{
	    sprintf(tmp, "%s: sorry, %s couldn't handle your message\n", 
		    "dqObserve", dqServer);	
	    cicsLogMessage(0,tmp);
	DPRINT(1,tmp);
	    retval = ERROR;
	} 
	else  /* server routine successful */
	{
	    sprintf(tmp, "%s: successful at running remote routine\n",
		    "dqObserve");
	    printf("%s",tmp);
	}  

	clnt_destroy(cl);  
	
    } 
    semGive(rpcSem);
   
    return retval;
}

int dqObsSetupRPC( )
{
    CLIENT *cl = NULL;    
    int *result, retval = OK;
    int i = 0;
  
     semTake (rpcSem,WAIT_FOREVER);
    if ((dqRpcGetClient(&cl) == ERROR) || (cl == (CLIENT *) NULL)) 
 
    {
	sprintf(tmp, "ERROR %s: unable to connect to RPC server %s\n",
		"dqObsSetup", dqServer);

	cicsLogMessage(0,tmp);
   
	retval = ERROR;
    }
    else
    {
      
	/* Call the remote procedure on the server */
      /*printf("call dqobssetuprpc_1\n"); */
	result = dqobssetuprpc_1(&i, cl);
	/*printf("returned\n"); */
	if (result == (int *) NULL) 
       	{
	    printf("obssetuprpc failed once\n");
	    clnt_destroy(cl);  
	    cl = NULL;
	    if ((dqRpcGetClient(&cl) == ERROR) || (cl == (CLIENT *) NULL)) 
	    { 
		/* An error occurred while calling the server. 
		 * Print error message and die.
	     */
/* 		cicsLogMessage(3," observe "); */
		clnt_perror(cl, dqServer );
		retval =   ERROR;
	    }
	    else
		result = dqobssetuprpc_1(&i, cl);
	    if (result == (int *) NULL)
	    {
		/* An error occurred while calling the server. 
	         * Print error message and die.
	         */
		clnt_perror(cl, dqServer);
		retval =  ERROR;
	    }
	}
	/* Okay, we successfully called the remote procedure, handle result. */
	else if (*result == 0)   /* server routine failed */
	{
	    sprintf(tmp, "%s: sorry, %s couldn't handle your message\n", 
		    "dqObsSetup", dqServer);
	    cicsLogMessage(0,tmp);
	DPRINT(1,tmp);	
	    retval = ERROR;
	} 
	else  /* server routine successful */
	{
	    printf("dqObsSetup: successful at running remote routine\n");

	} 
	clnt_destroy(cl);    
    }

   

     semGive(rpcSem);
    return retval;
}


int dqObsStatusRPC( )
{
    CLIENT *cl = NULL;   
    int *result, retval = OK;
    int i = 0;
  
    semTake (rpcSem,WAIT_FOREVER);
    /* get RPC client handle & perform call */
    if ((dqRpcGetClient(&cl) == ERROR) || (cl == NULL)) 
   
    {
	sprintf(tmp, "ERROR %s: unable to connect to RPC server %s\n",
		"dqObsStatus", dqServer);
	cicsLogMessage(0,tmp);
	DPRINT(1,tmp);
	retval = ERROR;
    }
    else
    {
	/* Call the remote procedure on the server */
	result = dqobsstatusrpc_1(&i, cl);
	if (result == NULL) 
	{clnt_destroy(cl);  
	    cl = NULL;
	    if ((dqRpcGetClient(&cl) == ERROR) || (cl == (CLIENT *) NULL)) 
	    { 
                /* An error occurred while calling the server. 
	         * Print error message and die.
	         */
/* 		cicsLogMessage(3," observe "); */
		clnt_perror(cl, dqServer );
		retval =  ERROR;
	    }
	    else
		result = dqobsstatusrpc_1(&i, cl);
	    if (result == (int *) NULL)
	    {
	    
		/* An error occurred while calling the server. 
		 * Print error message and die.
		 */
/* 		cicsLogMessage(3," observe status "); */
		clnt_perror(cl, dqServer );
		retval =  ERROR;
	    }
	}
	/* Okay, we successfully called the remote procedure, handle result. */
	else if (*result == 0)   /* server routine failed */
	{
	    sprintf(tmp, "%s: sorry, %s couldn't handle your message\n", 
		    "dqObsStatus", dqServer);	
	    cicsLogMessage(0,tmp);
	DPRINT(1,tmp);
	    retval = ERROR;
	} 
	else  /* server routine successful */
	{
/* 	    cicsLogMessage(3, "dqObsStatus: successful at running remote routine\n");	 */
	}  
    clnt_destroy(cl);  
    }

 
    semGive(rpcSem);
    return retval;
}


int dqObsAbortRPC(  )
{
    CLIENT *cl = NULL;   
    int *result, retval = OK;
    int i = 0;
    printf("dqObsAbortRPC start\n");
    semTake (rpcSem,WAIT_FOREVER);
    printf("dqObsAbortRPC got sem\n");	
    /* check any parameters here */

  
    /* get RPC client handle & perform call */
    printf("call dqrpcgetclient\n");
    if ((dqRpcGetClient(&cl) == ERROR) || (cl ==(CLIENT *) NULL)) 
   
    {
    printf(" dqrpcgetclient error\n");
	sprintf(tmp, "obsabort %s: unable to connect to RPC server %s\n",
		"dqObsAbort", dqServer);
	cicsLogMessage(0,tmp);
	DPRINT(1,tmp);
	retval = ERROR;
    }
    else
    {
    printf(" dqrpcgetclient ok\n");
	/* Call the remote procedure on the server */
      printf("call abort rpc on dq\n");
	result = dqobsabortrpc_1(&i, cl);
	if (result == NULL)
	{
	    clnt_destroy(cl);  
	    cl = NULL;
	    if ((dqRpcGetClient(&cl) == ERROR) || (cl == (CLIENT *) NULL)) 
	    { 
		/* An error occurred while calling the server. 
		 * Print error message and die.
	     */
/* 		cicsLogMessage(3," observe "); */
		clnt_perror(cl, dqServer );
		retval =  ERROR;
	    }
	    else
	      {
		printf("run abort remote routine\n");
		result = dqobsabortrpc_1(&i, cl);
	      }
	    if (result == (int *) NULL)
	    {
		/* An error occurred while calling the server. 
		 * Print error message and die.
	     */
/* 		cicsLogMessage(3," observe abort from dq"); */
		clnt_perror(cl, dqServer);
		retval =  ERROR;
	    }
	}
	/* Okay, we successfully called the remote procedure, handle result. */
	else if (*result == 0)   /* server routine failed */
	{
	    sprintf(tmp, "obsAbort %s: sorry, %s couldn't handle your message\n", 
		    "dqObsAbort", dqServer);
	    cicsLogMessage(0,tmp);
	DPRINT(1,tmp);	
	    retval = ERROR;
	} 
	else  /* server routine successful */
	{
	    sprintf(tmp,"dqObsAbort: successful at running remote routine\n");
 	    cicsLogMessage(0, tmp);	 
	DPRINT(1,tmp);
	}  
    clnt_destroy(cl); 
    }
 
 
    semGive(rpcSem);
    return retval;
}


int dqObsStopRPC( )
{
    CLIENT *cl = NULL;   
    int *result, retval = OK;
    int i = 0;

    semTake (rpcSem,WAIT_FOREVER);
    /* check any parameters here */
 
    /* get RPC client handle & perform call */

    if ((dqRpcGetClient(&cl) == ERROR) || (cl == NULL)) 
  
    {
	sprintf(tmp, "obsstoprpc %s: unable to connect to RPC server %s\n",
		"dqObsStop", dqServer);
	cicsLogMessage(0,tmp);
	DPRINT(1,tmp);
	retval = ERROR;
    }
    else
    {
	/* Call the remote procedure on the server */
	*result = 1;
     	result = dqobsstoprpc_1(&i, cl); 
	if (result == NULL)
	{clnt_destroy(cl);  
	    cl = NULL;
	    if ((dqRpcGetClient(&cl) == ERROR) || (cl == (CLIENT *) NULL)) 
	    { 
		/* An error occurred while calling the server. 
		 * Print error message and die.
	     */
		clnt_perror(cl, dqServer );
		retval =  ERROR;
	    }
	    else
		result = dqobsstoprpc_1(&i, cl);
	    if (result == (int *) NULL)
	    {
		/* An error occurred while calling the server. 
		 * Print error message and die.
		 */
		clnt_perror(cl, dqServer);
		retval =  ERROR;
	    }
	}
	/* Okay, we successfully called the remote procedure, handle result. */
	else if (*result == 0)   /* server routine failed */
	{
	    sprintf(tmp, "%s: sorry, %s couldn't handle your message\n", 
		    "dqObsStop", dqServer);
	    cicsLogMessage(0,tmp);
	DPRINT(1,tmp);	
	    retval = ERROR;
	} 
	else  /* server routine successful */
	{
	    sprintf(tmp,"dqObsStop: successful at running remote routine\n");
 	    cicsLogMessage(3,tmp );
	DPRINT(1,tmp);	 
	}  
    clnt_destroy(cl);  
    }

  
    semGive(rpcSem);
    return retval;
}

int dqRebootRPC( )
{
    CLIENT *cl = NULL;    
    int *result, retval = OK;
    int i = 0;
  

     semTake (rpcSem,WAIT_FOREVER);
     printf("getting client\n");
    if ((dqRpcGetClient(&cl) == ERROR) || (cl == (CLIENT *) NULL)) 
 
    {
	sprintf(tmp, "ERROR %s: unable to connect to RPC server %s\n",
		"dqReboot", dqServer);

	cicsLogMessage(0,tmp);
   
	retval = ERROR;
    }
    else
    {
      
	/* Call the remote procedure on the server */
	result = dqrebootrpc_1(&i, cl);
	if (result == (int *) NULL) 
       	{
	    printf("rebootrpc failed once\n");
	    clnt_destroy(cl);  
	    cl = NULL;
	    if ((dqRpcGetClient(&cl) == ERROR) || (cl == (CLIENT *) NULL)) 
	    { 
		/* An error occurred while calling the server. 
		 * Print error message and die.
	     */
/* 		cicsLogMessage(3," observe "); */
		clnt_perror(cl, dqServer );
		retval =  ERROR;
	    }
	    else
		result = dqrebootrpc_1(&i, cl);
	    if (result == (int *) NULL)
	    {
		/* An error occurred while calling the server. 
	         * Print error message and die.
	         */
/* 		cicsLogMessage(3," observe setup "); */
		clnt_perror(cl, dqServer);
		retval =  ERROR;
	    }
	}
	/* Okay, we successfully called the remote procedure, handle result. */
	else if (*result == 0)   /* server routine failed */
	{
	    sprintf(tmp, "%s: sorry, %s couldn't handle your message\n", 
		    "dqReboot", dqServer);
	    cicsLogMessage(0,tmp);
	DPRINT(1,tmp);	
	    retval = ERROR;
	} 
	else  /* server routine successful */
	{
	    printf("dqReboot: successful at running remote routine\n");
/* 	    cicsLogMessage(3, "dqReboot: successful at running remote routine\n");	 */
	} 
	clnt_destroy(cl);    
    }

   

     semGive(rpcSem);
    return retval;
}

/* connect/disconnect from dhs */
int dqDhsConnectionRPC(int request)
{

     CLIENT *cl = NULL;
    int *result, retval = OK;
    int i = 0;

    semTake (rpcSem,WAIT_FOREVER);

    /* get RPC client handle & perform call */
    if ((dqRpcGetClient(&cl) == ERROR) || (cl == (CLIENT *) NULL))

    {


        sprintf(tmp, "ERROR %s: unable to connect to RPC server %s\n",
                "dqDhsConnection", dqServer);

        cicsLogMessage(0,tmp);
        DPRINT(1,tmp);
        perror("dqDhsConnectionRpc");
        retval = ERROR;
    }
    else
    {

   i=request;

        /* Call the remote procedure on the server */
        result = dqdhsconnectionrpc_1(&i, cl);
        if (result == (int *) NULL)
        {
                 clnt_perror(cl, dqServer );
            clnt_destroy(cl);
            cl = NULL;
                 retval =  ERROR;
        }

        /* Okay, we successfully called the remote procedure, handle resul
t. */
        else if (*result == 0)   /* server routine failed */
        {
            sprintf(tmp, "%s: sorry, %s couldn't handle your message\n",
                    "dqdhsconnection", dqServer);
            cicsLogMessage(0,tmp);
        DPRINT(1,tmp);
            retval = ERROR;
        }
        else  /* server routine successful */
        {
            sprintf(tmp, "%s: successful at running remote routine\n",
                    "dqdhsconnection");
            printf("%s",tmp);
        }

        clnt_destroy(cl);

    }
    semGive(rpcSem);

    return retval;
}

