static char rcid[]="$Id: gnRpcDHServer.c,v 1.2 2009/05/27 19:32:25 fkraemer Exp $";
int rpcdebug;
int rundebug;

/*****************************************************************************
 * Copyright 1997 Association of Universities for Research in Astronomy, Inc. 
 * See the file COPYRIGHT for more details.
 *
 * Filename: 	
 * 	gnRpcServer.c
 *
 * Description:
 * 	This file contains the routines in the Data Coadder IOC which respond to
 *	    the RPC calls from the EPICS IOC.  These routines control the
 *	    gnaac data coadder program to setup the pipes and PATs and various data
 *	    system components
 *
 * Function name(s)
 * 	gnObsSetup() - uses Channel access to get the appropriate observation 
 *		parameters from the EPICS IOC into the Data Coadder processor and
 *		setup the pipes and PATS required
 *
 * Dependencies
 * 
 *
 * Orginial Author:
 *	Nick C. Buchholz
 *
 * History:
 *	11-Jun-1997: Created original version - ncb
 *
 ***************************************************************************/
#include <stdio.h>
#include <usrLib.h>
#include <sysLib.h>
#include <rpcLib.h>
#include <rpc/rpc.h>	/* always need this here */
#include <epdq.h>	/* need this too: epdq.h will be generated by rpcgen */
#include <car.h>
#include <dataHandling.h>

#include <gnerrno.h>
#define NEWDEBUG
#include <gnIpsDefs.h>

#define TASKINIT
#undef MAIN
#include <gnDQVars.h>

#include <epCommon.h>

#include "noaoDCA.h"
#include "gnDQSocket.h"

#define SDEBUG

extern int setObsFlags(int prep, int acq, int rdout); 
extern void sleep (int a, int b);

/*****************************************************************************
 * Function name:
 * 	gnObsSetup
 *
 * Invocation:
 * 	invoked by RPC call from other IOC
 *		status = gnObsSetup(  );
 *
 * PARAMETERS:
 *	None
 *
 * FUNCTION VALUE:
 * 	int - Status value returned by function 
 *
 * PURPOSE:
 * 	obtains a full set of parameters needed by the Data coadder program from
 *		the EPICS IOC.
 *
 * DESCRIPTION:
 * 	Uses channel access to obtain the values of the important data coadder
 *		variables stored in the EPICS IOC. This includes ucode
 *		description, operation modes, header data, ROI descriptions, 
 *		etc.  These values are stored in 'C' and PAT variables for
 *		use in controlling the Data coadder PAT's and Pipes.
 *
 * EXTERNAL VARIABLES:
 * 	Lots - see gnaaDQVars.h
 *
 * PRIOR REQUIREMENTS:
 *
 *
 * DEFICIENCIES:
 * 	None known
 *
 * HISTORY:
 * 	11-June-1997  Original version  N Buchholz
 *
 *****************************************************************************/
extern int dq_debug;
int *dqobssetuprpc_1(int i)
{
    static int result; /* must be static! */
    int status = (OK), error;
    static int setupNeeded = TRUE,acqSetupNeeded = TRUE;
    char errString[MAX_STRING_SIZE];
    char tempbuf[80], taskName[80];

    DQ_Abort = FALSE;
    DQ_Save = TRUE;
    disposition = SAVE;
    result = RPC_OK;
    cicsLogMessage(0, "dqObsSetup running.\n");
    PRT_DEBUG(rpcdebug, 10, "DH dqObsSetup running.\n");
    /* get parameters from EPICS IOC */
    status = gnGetGNAACParams(&setupNeeded,&acqSetupNeeded);
    PRT_DEBUG(rpcdebug, 30, ("got params\n");
    if (status != (OK))
    {
	cicsLogMessage(0,"gnObsSetup error: Data Coadder Parameters not set \n");
	sprintf(errString, "gnObsSetup error: Data Coadder Params not set");
	result = DQ_GETPARAM_ERR;
	error = CAR_ERROR;	
	gnPutEpics(TOP OBSERVE_CAR ".IERR", DQLONG,   &result); 
	gnPutEpics(TOP OBSERVE_CAR ".IMSS", DQSTRING, errString); 
	gnPutEpics(TOP OBSERVE_CAR ".IVAL", DQLONG, &error); 
	PRT_DEBUG(rpcdebug, 10, "obs setup rpc error 1\n");
	return (&result);
    } 
 
    if (setupNeeded == FALSE)
    {
	result = RPC_OK; 
	PRT_DEBUG(rpcdebug, 10,"obs setup rpc done\n");
	return (&result);
    }

    /* set setupDone to false so if we don't get through all of this we can
     * signal other parts of the system not to start taking data */
    rddSetupDone = FALSE;
    rrdSetupDone = FALSE;
    testSetupDone = FALSE;
    sepSetupDone = FALSE;
  
    /* Setup Processing Pipes of correct type */

    PRT_DEBUG(rpcdebug, 10,"obs setup rpc procmode\n");
    switch (procMode)
    {
    case TEST:   /* Test mode captures data and without further processing
		    * displays it scaled by taking the SqRoot of the data.
		    * This is a fast method to check the integrity of the 
		    * data processing chain */
      sprintf(tempbuf,"Setting up Test Mode\n");
      /* 	  cicsLogMessage(3,tempbuf); */
      PRT_DEBUG(rpcdebug, 10,"obs setup rpc procmode test\n");
      semGive(semSetupTEST);
      if ((status = semTake(semSetup, 90000000)) == ERROR)
	{
	  cicsLogMessage(0,"rpc error: Test Mode Failed\n");
	  sprintf(errString, "rpc error: Test Mode Failed");
	  result = TEST_NOT_SETUP;
	  error = CAR_ERROR;
	  gnPutEpics(TOP OBSERVE_CAR ".IERR", DQLONG,   &result); 
	  gnPutEpics(TOP OBSERVE_CAR ".IMSS", DQSTRING, errString); 
	  gnPutEpics(TOP OBSERVE_CAR ".IVAL", DQLONG, &error); 
	  return (&result);
	}
      break;

    case SEP:	   /* SEP mode captures data and attempts to send each frame
		    * to the saver to be stored on disk. The Data is converted
		    * to a float before it is sent. */

      PRT_DEBUG(rpcdebug, 10,"obs setup rpc procmode sep\n");
      sprintf(tempbuf,"Setting up Sep Mode\n");
      /* 	  cicsLogMessage(3,tempbuf); */
      semGive(semSetupSEP);
      if ((status = semTake(semSetup, 90000000)) == ERROR)
	{
	  cicsLogMessage(0,"rpc error: SEP Mode Failed\n");
	  sprintf(errString, "rpc error: SEP Mode Failed");
	  result = SEP_NOT_SETUP;
	  error = CAR_ERROR;
	  gnPutEpics(TOP OBSERVE_CAR ".IERR", DQLONG,   &result); 
	  gnPutEpics(TOP OBSERVE_CAR ".IMSS", DQSTRING, errString); 
	  gnPutEpics(TOP OBSERVE_CAR ".IVAL", DQLONG, &error); 
	  return (&result);
	}
      break;

    case STARE:   /* Stare mode is the normal data taking mode for the
		     * controller. two uCodeTypes will be supported:
		     * RDD - Global Reset double correlated sampling. This 
		     *	     mode includes the ability to do Low Noise Reads
		     *	     (LNRs) and coadding
		     * RRD - Row Reset single correlated sampling. This mode
		     *	     does not support LNRs but does do coAdding as
		     *       required. (ucode for this has yet to be developed
		     */
    PRT_DEBUG(rpcdebug, 10,"obs setup rpc procmode stare\n");
	  sprintf(tempbuf, "Setting up Stare Mode\n");
  
/* 	  cicsLogMessage(3,tempbuf); */
	  if (uCodeType == RDD)
	  {
	      sprintf(taskName, "%s", "RDD");
	      semGive(semSetupRDD);
	  }
	  else
	  {
	      sprintf(taskName, "%s", "RRD");
	      semGive(semSetupRRD);
	  }

	  if ((status = semTake(semSetup, 90000000)) == ERROR)
	  {
	      sprintf(errString, "rpc error: %s Mode Failed", taskName);
	      result = STARE_NOT_SETUP;
	      error = CAR_ERROR;
	      gnPutEpics(TOP OBSERVE_CAR ".IERR", DQLONG,   &result); 
	      gnPutEpics(TOP OBSERVE_CAR ".IMSS", DQSTRING, errString); 
	      gnPutEpics(TOP OBSERVE_CAR ".IVAL",DQLONG, &error); 
	      return (&result);
	  }
	  break;

      default: 
    PRT_DEBUG(rpcdebug, 10,"obs setup rpc procmode default\n");
	  cicsLogMessage(0,"Error: Bad Mode selected\n");
	  sprintf(errString, "rpc error: Bad Mode selected\n");
	  result = STARE_NOT_SETUP;
	  error = CAR_ERROR;
	  gnPutEpics(TOP OBSERVE_CAR ".IERR", DQLONG,   &result); 
	  gnPutEpics(TOP OBSERVE_CAR ".IMSS", DQSTRING, errString); 
	  gnPutEpics(TOP OBSERVE_CAR ".IVAL", DQLONG, &error); 
	  return (&result);

    } /* end of the switch on processing mode */
/*     cicsLogMessage(1,"rpc done"); */
    PRT_DEBUG(rpcdebug, 10,"obs setup rpc done\n");
    result = RPC_OK; 
    setupNeeded = FALSE; /* pr 6-22*/
    return (&result);
}


/*****************************************************************************
 * Function name:
 * 	gnObserve
 *
 * Invocation:
 * 	invoked by RPC call from other IOC
 *		status = gnObserve(  );
 *
 * PARAMETERS:
 *	None
 *
 * FUNCTION VALUE:
 * 	int - Status value returned by function 
 *
 * PURPOSE:
 * 	uses parameters setup by ObsSetup call 
 *
 * DESCRIPTION:
 * 	starts up the observing routines and pipelines
 *
 * EXTERNAL VARIABLES:
 * 	Lots - see gnDQVars.h
 *
 * PRIOR REQUIREMENTS:
 *
 *
 * DEFICIENCIES:
 * 	None known
 *
 * HISTORY:
 * 	11-Sep-1997  Original version  N Buchholz
 *
 *****************************************************************************/
extern int dq_debug;
int *dqobserverpc_1(int i)
{
   
    static int result; /* must be static! */
    char errString[80];
    int error;

    DQ_Abort = FALSE;
    DQ_Save = TRUE;
    disposition = SAVE;
    PRT_DEBUG(rpcdebug, 10,"gnRpcServer:  observe rpc\n");
    if ((procMode == STARE) && 
	(((uCodeType == RDD) && (rddSetupDone == FALSE)) ||
	 ((uCodeType == RRD) && (rrdSetupDone == FALSE)) ))
      {
	cicsLogMessage(0,"gnObserve error: DQ Setup not complete. Observe Failed\n");
	sprintf(errString, "Error GOBS: DQ Oberve Setup not complete");
	result = OBS_OUTOFORDER;

	error = CAR_ERROR;
	gnPutEpics(TOP OBSERVE_CAR ".IERR", DQLONG,   &result); 
	gnPutEpics(TOP OBSERVE_CAR ".IMSS", DQSTRING, errString); 
	gnPutEpics(TOP OBSERVE_CAR ".IVAL", DQLONG, &error); 
	return (&result);
      } 
    else if (((procMode == TEST) || (procMode == SEP)) &&
	     (((procMode == TEST) && (testSetupDone == FALSE)) ||
	      ((procMode == SEP) && (sepSetupDone == FALSE)) ))
      {
	cicsLogMessage(0,"gnObserve error: DQ Setup not complete. Observe Failed\n");
	sprintf(errString, "Error GOBS: DQ Oberve Setup not complete");
	result = OBS_OUTOFORDER;

	error = CAR_ERROR;
	gnPutEpics(TOP OBSERVE_CAR ".IERR", DQLONG,   &result); 
	gnPutEpics(TOP OBSERVE_CAR ".IMSS", DQSTRING, errString); 
	gnPutEpics(TOP OBSERVE_CAR ".IVAL", DQLONG, &error); 
	return (&result);
      }
    PRT_DEBUG(rpcdebug, 10,"gnRpcServer:  observe rpc clear\n");
/*     cicsLogMessage(3,"rpcServer:  observe 1"); */
    gsClearView(oRes1UwHb, 0);
    gsClearView(oRes1UwLb, 0);
    gsClearView(oRes1LwHb, 0);
    gsClearView(oRes1LwLb, 0);
	
    if (procMode == TEST)
      {
	/* start the test task which does all the real work and return */
	semGive(semTEST);
      }
    else if (procMode == SEP)
      {
/*     cicsLogMessage(3,"rpcServer:  observe 2"); */
	/* start the test task which does all the real work and return */
	semGive(semSEP);
      }
    else
      {
/*     cicsLogMessage(3,"rpcServer:  observe 3"); */
	switch (uCodeType)
	  {
	  case RDD:
	    /* start the task which does all the real work and return */
	    semGive(semRDD);	 /* This will start the doRDD_Data task */
	    /* sleep(0, 5000000); */ /* wait for the task to start the acquire pipe */
	    break;
		
	  case RRD:
	    semGive(semRRD);	 /* This will start the doRRD_Data task */
	    /* 	sleep(0, 5000000); */ /* wait for the task to start the acquire pipe */
	    break;
		
	  default:
	    cicsLogMessage(0,"gnObserve error: Invalid uCodeType. Observe Failed\n");
	    sprintf(errString, "Error GOBS: Invalid uCodeType");
	    result = INVALID_UCODE;
	    error = CAR_ERROR;
	    gnPutEpics(TOP OBSERVE_CAR ".IERR", DQLONG,   &result); 
	    gnPutEpics(TOP OBSERVE_CAR ".IMSS", DQSTRING, errString); 
	    gnPutEpics(TOP OBSERVE_CAR ".IVAL", DQLONG, &error); 
	    setObsFlags(FALSE, FALSE, FALSE); /* set prep, acq & rdout false */
	    return (&result);
	  }
      }
	 
    PRT_DEBUG(rpcdebug, 10,"gnRpcServer:  observe rpc started dq\n"); 
/*     cicsLogMessage(3,"dqObserve run\n"); */
      
    /* OK the task is started and we are done. */
    result = (RPC_OK); 
    return (&result);
}

/* Remote verson of "dqObsStatus"  */
int *dqobsstatusrpc_1(int i)
{
  static int result; /* must be static! */
  char errMess[MAX_STRING];

  strcpy(errMess, "");
/*   cicsLogMessage(3,"dqObsStatus running\n"); */
  return (&result);
}


/*****************************************************************************
 * Function name:
 * 	gnObsAbort
 *
 * Invocation:
 * 	invoked by RPC call from other IOC
 *		status = gnObsAbort(  );
 *
 * PARAMETERS:
 *	None
 *
 * FUNCTION VALUE:
 * 	int - Status value returned by function 
 *
 * PURPOSE:
 * 
 *
 * DESCRIPTION:
 * 	
 *
 * EXTERNAL VARIABLES:
 * 	Lots - see gnaaDQVars.h
 *
 * PRIOR REQUIREMENTS:
 *
 *
 * DEFICIENCIES:
 * 	None known
 *
 * HISTORY:
 * 	11-June-1997  Original version  N Buchholz
 *
 *****************************************************************************/
int *dqobsabortrpc_1(int i)
{
    static int result; /* must be static! */
    int retval;

/*     cicsLogMessage(3, "dqObsAbort running\n"); */

    result = RPC_OK;
    /* on "abort", abort image taking and discard current image */
    DQ_Abort = TRUE;
    DQ_Save = FALSE;
    disposition = TOSS;
    retval = 2;

    PRT_DEBUG(rpcdebug, 10,"\nabort observation\n");
#if 0
    /* We'll need to trigger the data saving part of this code here to start
     * the data on its way to perdition
     */
    /* retval = simulateInterupt(FrameDone); */
    if (retval != OK)
    {
	dqErrPrintMesg("simulateInterupt", retval, DQ_EVERB_DETAILED);
	result = RPC_ERROR;
    }

    /* reset the system for the next frame */
    /* retval = resetDataSystem(NEXTFRAME);*/
    if (retval != OK)
    {
	dqErrPrintMesg("resetDataSystem", retval, DQ_EVERB_DETAILED);
	result = RPC_ERROR;
    }
#endif
    return (&result);

}


/*****************************************************************************
 * Function name:
 * 	gnObsStop
 *
 * Invocation:
 * 	invoked by RPC call from other IOC
 *		status = gnObsStop(  );
 *
 * PARAMETERS:
 *	None
 *
 * FUNCTION VALUE:
 * 	int - Status value returned by function 
 *
 * PURPOSE:
 * 	
 *
 * DESCRIPTION:
 * 	
 *
 * EXTERNAL VARIABLES:
 * 	Lots - see gnaaDQVars.h
 *
 * PRIOR REQUIREMENTS:
 *	
 * DEFICIENCIES:
 * 	None known
 *
 * HISTORY:
 * 	11-June-1997  Original version  N Buchholz
 *
 *****************************************************************************/
int *dqobsstoprpc_1(int i)
{
    static int result; /* must be static! */
    int retval;

/*     cicsLogMessage(3, "dqObsStop running\n"); */

    result = RPC_OK;
    /* on "stop", abort image taking & save current image */
    DQ_Abort = TRUE;
    DQ_Save = TRUE;
    disposition = SAVE;
    retval=3;
    PRT_DEBUG(rpcdebug, 10,"\nstop observation\n");

#if 0
    /* We'll need to trigger the data saving part of this code here to start
     * the data on its way to the DHS
     */
    /* retval = simulateInterupt(FrameDone); */
    if (retval != OK)
    {
	dqErrPrintMesg("simulateInterupt", retval, DQ_EVERB_DETAILED);
	result = RPC_ERROR;
    }

    /* reset the system for the next frame */
    /* retval = resetDataSystem(NEXTFRAME);*/
    if (retval != OK)
    {
	dqErrPrintMesg("resetDataSystem", retval, DQ_EVERB_DETAILED);
	result = RPC_ERROR;
    }
#endif

    return (&result);
}







