# Makefile
# CREATED BY mpp
#       FROM MakeSkel
#         ON Fri Jun  5 15:16:02 MST 1998
#



# MakeSkel - makefile skeleton for bsp/config/mv167
#
# Copyright 1984-1992 Wind River Systems, Inc.
#
# modification history
# --------------------
# 01g,10mar94,vin  changed RAM_LOW_ADRS to 0x20000 from 0x1000
# 01f,31oct92,caf  increased ROM_SIZE to 00080000, RAM_HIGH_ADRS to 00100000.
# 01e,30oct92,caf  fixed spelling of MVME167.
# 01d,29oct92,caf  increased ROM_SIZE to 00040000.
# 01c,16oct92,ccc  changed note about config.h dependancy.
# 01b,09sep92,gae  defined target macro's.
# 01a,22jun92,rrr  written.
#
# DESCRIPTION
# This file contains rules for building VxWorks for the
# Motorola MVME167.
#
# INCLUDES
#     makeTarget
#*/

CPU              = MC68040
TOOL             = gnu

TARGET_DIR       = mv167
VENDOR           = Motorola
BOARD            = MVME167

#
# The constants ROM_TEXT_ADRS, ROM_SIZE, and RAM_HIGH_ADRS are defined
# in config.h, MakeSkel, Makefile, and Makefile.*
# All definitions for these constants must be identical.
#

ROM_TEXT_ADRS    = ff800008 # ROM entry address
ROM_SIZE         = 00080000 # number of bytes of ROM space

RAM_LOW_ADRS     = 00020000 # RAM text/data address
RAM_HIGH_ADRS    = 00100000 # RAM text/data address

HEX_FLAGS        = -v -p $(ROM_TEXT_ADRS) -a 8

MACH_EXTRA       =

# makeTarget - meta makeTarget stub for building BSPs
#
# modification history
# --------------------
# 01a,22sep92,yp    added modification history
#
# DESCRIPTION
# This file contains the makeTarget and intermediate makeTarget for VxWorks.
#*/

# makeTarget2 - makefile target skeleton for BSP Targets "pass 2"
#
# modification history
# --------------------
# 03c,28mar95,kdl  fixed use of env vars to support bsp not in vw tree (spr4100)
# 03b,15mar95,caf  added rules for mips resident roms (SPR #3856).
# 03a,10dec94,caf  undid MIPS-specific resident ROM changes (SPR 3856).
# 02g,06jun94,caf  use CASFLAGS when assembling romInit.s.
# 02f,26oct94,caf  changed resident ROMs to locate the start of data with the
#		   RAM_DST_ADRS macro (previously used for standalone ROMs).
# 02h,05oct94,kdl  added missing space in depend.$(CPU)$(TOOL) rule.
# 02g,30sep94,kdl  changed "make" to "$(MAKE)" to use environment variable;
#		   changed depend.$(CPU)$(TOOL) rule to use temporary file.
# 02f,19jul94,vin  added BOOT_EXTRA macro to dependency list for
#		   bootrom and vxWorks.st_rom
# 02e,04feb93,wmd  removed setting of MV_BIN to true to make.defaults.
#		   Also remove imi before building ROM targets.
# 02d,02feb93,rrr  SPR 1817 added romInit.o to depend list
#                  SPR 1840 set MV_BIN to ``true'' so that it is not a null cmd
# 02c,13nov92,kdl  added $(IMI) to dependencies for bootrom_uncmp.hex and
#		   bootrom_res.hex (SPR #1754).
# 02b,29oct92,jcf  added back 0x to RAM_DST_ADRS, for standalone hex.
# 02a,24oct92,jcf  made xxx_st.o have more robust dependency rules.
# 01z,23oct92,yp   added BOOT_EXTRA macro for targets building compressed ROMs
#		   remove symTbl.c and symTbl.o before building them
# 01y,23oct92,wmd  restored imi target to revision 01w.
# 01x,21oct92,wmd  cannot use output of LDOUT_SYMS for relinking, use tmp file.
# 01w,20oct92,wmd  modified imi target for i960.
# 01v,01oct92,yp   move $CP macro to make.defaults so hosts can over-ride
# 01u,24sep92,yp   fixed CONFIG_ALL to have right path
# 01t,24sep92,yp   changed relative path references to use environment vars.
# 01s,23sep92,wmd  fixed so vxWorks.st works for i960.
# 01r,22sep92,jcf  added dataSegPad.o in the right places.
#		   changed vxWorks_rom to run at RAM_LOW_ADRS.
# 01q,16sep92,gae  moved 'docs' rule to first pass.
# 01p,11sep92,gae  added 'docs' rule; removed old doc & tags stuff.
# 01o,04sep92,yp   moved man rule to makeTarget1
# 01n,04sep92,yp   changed save rule to use wild card
# 01m,01sep92,yp   took out forced build of 01j. activated save rule.
#		   added documentation rule
# 01l,17aug92,yp   added CPU and TOOL to release rule
# 01k,13aug92,yp   changed release rule so we can over ride from MakeSkel
# 01j,13aug92,jcf  forced build of ../all/*.c; added $(LIB) to depedencies.
# 01i,02aug92,yp   changed title line.
# 01h,02aug92,yp   returned archiving rules to src directories;
#		   removed libraries from dependency list
# 01g,27jul92,rrr  made release programable (and also not do the save)
# 01f,21jul92,rdc  moved MACH_DEP to make.defaults, added dataSegPad.o rules.
# 01e,21jul92,rrr  added rules for save, restore, release, and clean
# 01d,17jul92,rrr  added removal of tmp files.
# 01c,08jul92,wmd  modified for i960 ROM targets.
# 01b,02jul92,ajm  fixed vxWorks.st with -o option
# 01a,22jun92,yp   created from makeTarget
#
# DESCRIPTION
# This file contains rules, definitions, and flags used in building targets.
#
# VARIABLES
# The following variables must be defined (or not, as appropriate):
#
#     ROM_SIZE          number of bytes of ROM space as in config.h
#     LOCAL_MEM_SIZE	target RAM size as in config.h
#     BINHEX		binary->hex file conversion program
#     HEX_FLAGS         BINHEX program options
#     LD_LOW_FLAGS	ld(1) options for code in low memory
#     LD_HIGH_FLAGS	ld options for code in high memory
#     LD_PARTIAL_FLAGS  ld flags for linking partially complete objects
#     LDDEPS		host-specific dependencies prerequisite to linking
#     LDOUT_CONV	hpToBsd, coffToBsd, gswab, /bin/cat, etc.
#     COMPILE_SYMTBL	hide flags needed to get compiler to swallow symTbl.c
#     ROM_ENTRY		rom entry point (typically &romInit)
#     SYS_ENTRY		system entry point (typically &sysInit)
#     USR_ENTRY		compressed system entry point (typically &usrInit)
#
# The following variables are optionally defined:
#
#     LDFLAGS		standard ld flags for vxWorks & ROMs.
#     ROM_LDFLAGS	ld flags specific to ROM image
#
# CONSTANTS
#     CPU               cpu type
#*/

RELEASE=vxWorks vxWorks.st bootrom.hex

# make.defaults - Compilation tools default definitions
#
# modification history
# --------------------
# 01k,04feb93,wmd  defined default MV_BIN = true here.
# 01j,03feb93,rrr  SPR 1841, changed CP=cp -p to CP=cp because sgi doesn't
#                  understand -p flag
# 01i,21oct92,caf  introduced ADDED_CFLAGS and ADDED_MODULES, which may be
#		   defined on make command line (SPR 1707).
# 01h,01oct92,yp   move $CP macro here from makeTarget2
# 01g,22sep92,yp   added bsp/src directories so bsps stay position independent
# 01f,22sep92,jcf  removed BOOTROMZ_DEP.  fixed MACH_DEP.
# 01e,13aug92,jcf  fixed comment of MACH_DEP.
# 01d,21jul92,rdc  moved MACH_DEP here from makeTarget2 so arch dep makefiles
#                  can redefine.
# 01c,21jul92,rrr  added TARGET= so you don't grab the environment one.
# 01b,17jul92,rrr  added LDOUT_SYMS
# 01a,17jul92,wdm  added modification history, defined LDOUT_SYMS.
#
# DESCRIPTION
# This file contains default definitions, and flags used in building targets.
# NEVER CHANGE ANYTHING IN THIS FILE, ONLY ADD TO IT. If you change something
# you would have to go through a dozen make.$(CPU)$(TOOL) files and make
# sure they didn't break.
#

CFLAGS		= $(CC_OPTIM) $(CC_WARNINGS) $(CC_INCLUDE) $(CC_COMPILER) \
			$(CC_DEFINES) $(ADDED_CFLAGS)

CASFLAGS	= -E $(CC_INCLUDE) $(CC_DEFINES)
CC_WARNINGS	= $(CC_WARNINGS_ALL)
CC_OPTIM	= $(CC_OPTIM_NORMAL)
CC_INCLUDE	= -I$(UP)/h $(INCLUDE_CC) $(EXTRA_INCLUDE) \
		  -I$(VX_BSP_BASE)/src/config/ \
		  -I$(VX_BSP_BASE)/src/drv/
CC_DEFINES	= -DCPU=$(CPU) $(DEFINE_CC) $(EXTRA_DEFINE)

RM		= rm -f
CP		= cp
SHELL		= /bin/sh

# override things below this point

.s.o :
	@ $(RM) $@
	cat $< > $*.S
	$(CC) $(CFLAGS) -c $*.S
	@ $(RM) $*.S

.c.o :
	@ $(RM) $@
	$(CC) $(CFLAGS) -c $<

CPU             = MC68020
TOOL            = gnu

CC_WARNINGS_ALL	= -Wall
CC_WARNINGS_NONE=

CC_OPTIM_DRIVER	=
CC_OPTIM_NORMAL	= -O -fstrength-reduce -fcombine-regs
CC_OPTIM_TARGET	= -O -fvolatile

CC_COMPILER	=  -ansi -pedantic -pipe -nostdinc

AR              = ar
AS              = as
CC              = cc
LD              = ld
RANLIB          = ranlib

LD_LOW_FLAGS    = -Ttext $(RAM_LOW_ADRS)
LD_HIGH_FLAGS   = -Ttext $(RAM_HIGH_ADRS)
RES_LOW_FLAGS   = -Ttext $(ROM_TEXT_ADRS) -Tdata $(RAM_LOW_ADRS)
RES_HIGH_FLAGS  = -Ttext $(ROM_TEXT_ADRS) -Tdata $(RAM_HIGH_ADRS)

ROM_ENTRY       = _romInit
SYS_ENTRY       = _sysInit
USR_ENTRY       = _usrInit

LDFLAGS         = -X -N
LD_PARTIAL_FLAGS= -X -r

MACH_DEP	= sysALib.o sysLib.o tyCoDrv.o $(MACH_EXTRA) \
		  $(ADDED_MODULES)

EXTRACT_BIN     = $(VX_HSP_BASE)/bin/$(VX_HOST_TYPE)/aoutToBin
LDOUT_SYMS      = true
LDOUT_CONV      = true 
LDOUT_HOST      = true 
BINXSYM         = $(VX_HSP_BASE)/bin/$(VX_HOST_TYPE)/xsym 
BINHEX          = $(VX_HSP_BASE)/bin/$(VX_HOST_TYPE)/hex 
 
ENV_BIN         = $(TOOLENV) $(VX_HSP_BASE)/bin/$(VX_HOST_TYPE)/
TARGET		=
MV_BIN		= true

# end of make.defaults

# make.MC68040gnu - GNU compilation tools definitions for MC68040
#
# modification history
# --------------------
# 01d,22sep92,yp   added EOF marker
# 01c,22sep92,jcf  removed redefinition of MACH_DEP.
# 01b,03sep92,yp   added -fno-builtin to drivers
# 01a,23aug92,yp   added modification history and support for GCC 2.2.2
#
# DESCRIPTION
# This file contains MC68040 specific definitions and flags for the GNU
# software generation tools (compiler, assembler, linker etc.).
#*/


CPU=MC68040
TOOL=gnu

CC_OPTIM_DRIVER = -fno-builtin
CC_OPTIM_NORMAL = -O -fstrength-reduce -fno-builtin -m68040 -m68040-only
CC_OPTIM_TARGET = -O -fvolatile -fno-builtin -m68040 -m68040-only

AR=ar68k
AS=as68k
CC=cc68k
LD=ld68k
RANLIB=ranlib68k

TOOLENV= VX_CPU_FAMILY=68k

# end of make.MC68040gnu


## alternate file directory
CONFIG_ALL = $(VX_VW_BASE)/config/all/

MAN1 	   = $(VX_BSP_BASE)/man/man1/
MAN2 	   = $(VX_BSP_BASE)/man/man2/

## flags and defines

EXTRA_INCLUDE  = -I. -I$(CONFIG_ALL) -I$(VX_BSP_BASE)/h -I$(VX_VW_BASE)/h/ \
		 -I $(VX_VW_BASE)/src/config

ASM_P1                   = cat
ASM_P2                   = cat


COMPILE_SYMTBL  = $(CC) -c $(CFLAGS)

CC_OPTIM = $(CC_OPTIM_TARGET)

## files

LIBS      =  $(VX_BSP_BASE)/lib/lib$(CPU)$(TOOL)drv.a \
	     $(VX_VW_BASE)/lib/lib$(CPU)$(TOOL)vx.a $(LIB_EXTRA)

exe	: vxWorks

clean   :
	$(RM) *.o vxWorks* bootrom* 

version.o:
	@ $(RM) version.[co]
	$(ENV_BIN)makeVersion > version.c
	$(CC) -c $(CFLAGS) version.c
	@ $(RM) version.c

####################### machine dependent modules ##########################

romInit_res.o: romInit.s
	@ $(RM) $@ tmp.c tmp.s tmp.i
	$(ASM_P1) romInit.s > tmp.c
	$(CC) $(CASFLAGS) -DROM_RESIDENT tmp.c > tmp.i
	$(ASM_P2) tmp.i > tmp.s
	$(AS) -o $@ tmp.s
	@ $(RM) tmp.c tmp.i tmp.s

romInit_res_low.o: romInit.s
	@ $(RM) $@
	$(CC) $(CASFLAGS) -DROM_RESIDENT \
	    -DRAM_DST_ADRS=0x$(RAM_LOW_ADRS) -o $@ romInit.s

romInit_res_high.o: romInit.s
	@ $(RM) $@
	$(CC) $(CASFLAGS) -DROM_RESIDENT \
	    -DRAM_DST_ADRS=0x$(RAM_HIGH_ADRS) -o $@ romInit.s

usrConfig.o : $(CONFIG_ALL)usrConfig.c
	@ $(RM) $@
	$(CC) -c $(CFLAGS) $(CONFIG_ALL)usrConfig.c

# can't use "cc -c -o"
usrConfig_st.o : $(CONFIG_ALL)usrConfig.c usrConfig.o
	@ $(RM) $@
	$(CP) $(CONFIG_ALL)usrConfig.c usrConfig_st.c
	$(CC) -c $(CFLAGS) -DSTANDALONE usrConfig_st.c
	@ $(RM) usrConfig_st.c

bootConfig.o : $(CONFIG_ALL)bootConfig.c
	@ $(RM) $@
	$(CC) -c $(CFLAGS) $(CONFIG_ALL)bootConfig.c

bootInit.o : $(CONFIG_ALL)bootInit.c
	@ $(RM) $@
	$(CC) -c $(CFLAGS) $(CONFIG_ALL)bootInit.c

bootInit_res.o : $(CONFIG_ALL)bootInit.c bootInit.o
	@ $(RM) $@
	$(CP) $(CONFIG_ALL)bootInit.c bootInit_res.c
	$(CC) -c $(CFLAGS) -DROM_RESIDENT bootInit_res.c
	@ $(RM) bootInit_res.c

bootInit_res_low.o : $(CONFIG_ALL)bootInit.c
	@ $(RM) $@
	$(CP) $(CONFIG_ALL)bootInit.c bootInit_res_low.c
	$(CC) -c $(CFLAGS) -DROM_RESIDENT \
	    -DRAM_DST_ADRS=0x$(RAM_LOW_ADRS) bootInit_res_low.c
	@ $(RM) bootInit_res_low.c

bootInit_res_high.o : $(CONFIG_ALL)bootInit.c
	@ $(RM) $@
	$(CP) $(CONFIG_ALL)bootInit.c bootInit_res_high.c
	$(CC) -c $(CFLAGS) -DROM_RESIDENT \
	    -DRAM_DST_ADRS=0x$(RAM_HIGH_ADRS) bootInit_res_high.c
	@ $(RM) bootInit_res_high.c

bootInit_uncmp.o : $(CONFIG_ALL)bootInit.c bootInit.o
	@ $(RM) $@
	$(CP) $(CONFIG_ALL)bootInit.c bootInit_uncmp.c
	$(CC) -c $(CFLAGS) -DUNCOMPRESS bootInit_uncmp.c
	@ $(RM) bootInit_uncmp.c

bootInit_st.o : $(CONFIG_ALL)bootInit.c bootInit.o
	@ $(RM) $@
	$(CP) $(CONFIG_ALL)bootInit.c bootInit_st.c
	$(CC) -c $(CFLAGS) -DRAM_DST_ADRS=0x$(RAM_LOW_ADRS) bootInit_st.c
	@ $(RM) bootInit_st.c


bootInit_uncmp_res.o : $(CONFIG_ALL)bootInit.c bootInit.o
	@ $(RM) $@
	$(CP) $(CONFIG_ALL)bootInit.c bootInit_uncmp_res.c
	$(CC) -c $(CFLAGS) -DROM_RESIDENT -DUNCOMPRESS bootInit_uncmp_res.c
	@ $(RM) bootInit_uncmp_res.c

dataSegPad.o: $(CONFIG_ALL)dataSegPad.c $(CONFIG_ALL)configAll.h config.h
	@ $(RM) $@
	$(CC) -c $(CFLAGS) $(CONFIG_ALL)dataSegPad.c

####################### vxWorks ###########################################

# vxWorks     - normal vxWorks system
# vxWorks.sym - symbol table of vxWorks

vxWorks vxWorks.sym : usrConfig.o dataSegPad.o $(MACH_DEP) $(LDDEPS) $(LIBS)
	@ $(RM) vxWorks vxWorks.sym
	@ $(MAKE) -f Makefile.$(CPU)$(TOOL) CPU=$(CPU) TOOL=$(TOOL) version.o
	$(LD) $(LDFLAGS) -e $(SYS_ENTRY) $(LD_LOW_FLAGS) \
	    -o vxWorks dataSegPad.o $(MACH_DEP) usrConfig.o version.o $(LIBS)
	$(LDOUT_HOST) vxWorks
	$(LDOUT_CONV) vxWorks
	$(BINXSYM) < vxWorks > vxWorks.sym
	$(LDOUT_SYMS) vxWorks.sym
	@ $(RM) version.o


# vxWorks_rom - rommable version of VxWorks (without standalone symbol table)
#   This is typically used when making an application in ROM that doesn't
#   include the shell and the symbol table.  Since these applications are
#   usually smaller, this version doesn't use ROM compression.

vxWorks_rom : bootInit_uncmp.o romInit.o dataSegPad.o usrConfig.o \
	      $(MACH_DEP) $(LDDEPS) $(LIBS)
	@ $(RM) $@ $(IMI) $(IBR)
	@ $(MAKE) -f Makefile.$(CPU)$(TOOL) CPU=$(CPU) TOOL=$(TOOL) version.o
	$(LD) $(LDFLAGS) -e $(ROM_ENTRY) $(LD_LOW_FLAGS) \
	    -o $@ romInit.o bootInit_uncmp.o dataSegPad.o usrConfig.o \
	    $(MACH_DEP) version.o $(LIBS)
	$(LDOUT_HOST) $@
	$(ENV_BIN)romsize -b $(ROM_SIZE) $@
	$(LDOUT_CONV) $@
	@ $(RM) version.o

vxWorks_rom.hex : vxWorks_rom $(IMI)
	@ $(RM) $@
	$(BINHEX) $(HEX_FLAGS) $(SECT_SPEC)vxWorks_rom$(TXT_OFFSET) \
		$(IMI_SPEC)$(IMI)$(IMI_OFFSET) > $@$(MAP_EXT)
	-@ $(MV_BIN)

# vxWorks.st - standalone VxWorks with symbol table linked in
#   This builds a VxWorks image that contains the symbol table linked in,
#   instead of loading it over the network.

vxWorks.st : usrConfig_st.o dataSegPad.o $(MACH_DEP) $(LDDEPS) $(LIBS)
	@ $(RM) $@ symTbl.c symTbl.o tmp.o tmp.2
	@ $(MAKE) -f Makefile.$(CPU)$(TOOL) CPU=$(CPU) TOOL=$(TOOL) version.o
	$(LD) -o tmp.o $(LD_PARTIAL_FLAGS) dataSegPad.o $(MACH_DEP) \
	    usrConfig_st.o version.o $(LIBS)
	$(CP) tmp.o tmp.2
	$(LDOUT_SYMS) tmp.o
	$(ENV_BIN)makeSymTbl tmp.o > symTbl.c
	$(COMPILE_SYMTBL) symTbl.c
	$(LD) $(LDFLAGS) -e $(SYS_ENTRY) $(LD_LOW_FLAGS) \
	    -o $@ tmp.2 symTbl.o
	$(LDOUT_SYMS) $@
	$(LDOUT_CONV) $@
	@ $(RM) tmp.?	 version.o


# vxWorks.st_rom - rommable standalone version using ROM compression
#   This builds a standalone VxWorks image that can be put in ROM.
#   It includes a linked in symbol table so that a complete VxWorks with
#   shell and symbol table can be put in ROM.  Since these systems tend to
#   be larger, ROM compression is used.
#   Note: this uses larger EEPROMs, the user is advised to check the
#   macros for ROM sizes and offsets for compatibility.

vxWorks.st.Z.s : usrConfig_st.o dataSegPad.o $(MACH_DEP) $(LDDEPS) $(LIBS)
	@ $(RM) $@ tmp.o tmp.1 tmp.2 tmp.Z symTbl.c symTbl.o
	@ $(MAKE) -f Makefile.$(CPU)$(TOOL) CPU=$(CPU) TOOL=$(TOOL) version.o
	$(LD) -o tmp.1 $(LD_PARTIAL_FLAGS) dataSegPad.o $(MACH_DEP) \
	    usrConfig_st.o version.o $(LIBS)
	$(CP) tmp.1 tmp.o
	$(LDOUT_SYMS) tmp.o
	$(ENV_BIN)makeSymTbl tmp.o >symTbl.c
	$(COMPILE_SYMTBL) symTbl.c
	$(LD) -o tmp.2 $(LDFLAGS) $(ROM_LDFLAGS) -e $(SYS_ENTRY) \
	    $(LD_LOW_FLAGS) tmp.1 symTbl.o
	$(LDOUT_HOST) tmp.2
	$(LDOUT_CONV) tmp.2
	$(EXTRACT_BIN) < tmp.2 | $(ENV_BIN)compress -f -b 15 >tmp.Z
	$(ENV_BIN)binToAsm tmp.Z > $@
	@ $(RM) version.o tmp.?

vxWorks.st_rom : bootInit_st.o romInit.o vxWorks.st.Z.o $(LDDEPS) $(LIBS) \
			$(BOOT_EXTRA)
	@ $(RM) $(IMI) $(IBR)
	@ $(MAKE) -f Makefile.$(CPU)$(TOOL) CPU=$(CPU) TOOL=$(TOOL) version.o
	$(LD) $(LDFLAGS) -e $(ROM_ENTRY) $(LD_HIGH_FLAGS) \
	    -o $@ romInit.o bootInit_st.o version.o $(LIBS) \
	       $(BOOT_EXTRA) vxWorks.st.Z.o
	$(ENV_BIN)romsize -b $(ROM_SIZE) $@
	$(LDOUT_CONV) $@
	@ $(RM) version.o

vxWorks.st_rom.hex : vxWorks.st_rom $(IMI)
	@ $(RM) $@
	$(BINHEX) $(HEX_FLAGS) $(SECT_SPEC)vxWorks.st_rom$(TXT_OFFSET) \
		$(IMI_SPEC)$(IMI)$(IMI_OFFSET) > $@$(MAP_EXT)
	-@ $(MV_BIN)

# vxWorks.res_rom - rommable standalone version without compression
#   This builds a standalone VxWorks image that can be put in ROM.
#   It includes a linked in symbol table so that a complete VxWorks with
#   shell and symbol table can be put in ROM. Only the data segment
#   of this ROM image is copied into RAM.

vxWorks.res_rom: bootInit_res.o romInit_res.o usrConfig_st.o \
		 $(MACH_DEP) $(LDDEPS) $(LIBS)
	@ $(RM) $@ tmp.o tmp.1 symTbl.c symTbl.o $(IMI) $(IBR)
	@ make -f Makefile.$(CPU)$(TOOL) CPU=$(CPU) TOOL=$(TOOL) version.o
	$(LD) -o tmp.o $(LD_PARTIAL_FLAGS) \
	    $(MACH_DEP) usrConfig_st.o version.o $(LIBS)
	$(CP) tmp.o tmp.1
	$(LDOUT_SYMS) tmp.1
	$(ENV_BIN)makeSymTbl tmp.1 > symTbl.c
	$(COMPILE_SYMTBL) symTbl.c
	$(LD) -o $@ $(LDFLAGS) $(ROM_LDFLAGS) -e $(ROM_ENTRY) \
	    $(RES_LOW_FLAGS) romInit_res.o bootInit_res.o symTbl.o tmp.o
	$(LDOUT_HOST) $@
	$(ENV_BIN)romsize -b $(ROM_SIZE) $@
	$(LDOUT_CONV) $@
	@ $(RM) tmp.? version.o

vxWorks.res_rom_mips: bootInit_res_low.o romInit_res_low.o usrConfig_st.o \
		 $(MACH_DEP) $(LDDEPS) $(LIBS)
	@ $(RM) $@ tmp.o tmp.1 symTbl.c symTbl.o $(IMI) $(IBR)
	@ $(MAKE) -f Makefile.$(CPU)$(TOOL) CPU=$(CPU) TOOL=$(TOOL) version.o
	$(LD) -o tmp.o $(LD_PARTIAL_FLAGS) \
	    $(MACH_DEP) usrConfig_st.o version.o $(LIBS)
	$(CP) tmp.o tmp.1
	$(LDOUT_SYMS) tmp.1
	$(ENV_BIN)makeSymTbl tmp.1 > symTbl.c
	$(COMPILE_SYMTBL) symTbl.c
	$(LD) -o $@ $(LDFLAGS) $(ROM_LDFLAGS) -e $(ROM_ENTRY) \
	    $(RES_LOW_FLAGS) romInit_res_low.o bootInit_res_low.o \
	    symTbl.o tmp.o
	$(LDOUT_HOST) $@
	$(ENV_BIN)romsize -b $(ROM_SIZE) $@
	$(LDOUT_CONV) $@
	@ $(RM) tmp.? version.o

vxWorks.res_rom.hex: vxWorks.res_rom $(IMI)
	@ $(RM) $@
	$(BINHEX) $(HEX_FLAGS) vxWorks.res_rom$(TXT_OFFSET) \
		$(IMI_SPEC)$(IMI)$(IMI_OFFSET) > $@$(MAP_EXT)
	-@ $(MV_BIN)

vxWorks.res_rom_mips.hex: vxWorks.res_rom_mips $(IMI)
	@ $(RM) $@
	$(BINHEX) $(HEX_FLAGS) vxWorks.res_rom_mips$(TXT_OFFSET) \
		$(IMI_SPEC)$(IMI)$(IMI_OFFSET) > $@$(MAP_EXT)
	-@ $(MV_BIN)

####################### bootrom ###########################################

# bootrom		- compressed bootrom object module
# bootrom.hex		- compressed bootrom hex format
# bootrom_uncmp		- noncompressed bootrom object module
# bootrom_uncmp.hex	- noncompressed bootrom hex format
#

bootrom.Z.s : bootConfig.o $(MACH_DEP) $(LDDEPS) $(LIBS)
	@ $(RM) $@ tmp.o tmp.Z
	@ $(MAKE) -f Makefile.$(CPU)$(TOOL) CPU=$(CPU) TOOL=$(TOOL) version.o
	$(LD) -o tmp.o $(LDFLAGS) $(ROM_LDFLAGS) -e $(USR_ENTRY) \
	    $(LD_HIGH_FLAGS) bootConfig.o version.o $(MACH_DEP) $(LIBS)
	$(LDOUT_HOST) tmp.o
	$(EXTRACT_BIN) < tmp.o | $(ENV_BIN)compress -f -b 15 > tmp.Z
	$(ENV_BIN)binToAsm tmp.Z >bootrom.Z.s
	@ $(RM) tmp.o tmp.Z version.o

bootrom : bootInit.o romInit.o bootrom.Z.o $(LDDEPS) $(LIBS) \
		$(BOOT_EXTRA)
	@ $(RM) $@ $(IMI) $(IBR)
	@ $(MAKE) -f Makefile.$(CPU)$(TOOL) CPU=$(CPU) TOOL=$(TOOL) version.o
	$(LD) $(LDFLAGS) -e $(ROM_ENTRY) $(LD_LOW_FLAGS) \
	    -o $@ romInit.o bootInit.o version.o $(LIBS) \
	       $(BOOT_EXTRA) bootrom.Z.o
	$(ENV_BIN)romsize -b $(ROM_SIZE) $@
	$(LDOUT_CONV) $@
	@ $(RM) version.o

bootrom_uncmp : bootInit_uncmp.o romInit.o bootConfig.o \
	    $(MACH_DEP) $(LDDEPS) $(LIBS)
	@ $(RM) $@ $(IMI) $(IBR)
	@ $(MAKE) -f Makefile.$(CPU)$(TOOL) CPU=$(CPU) TOOL=$(TOOL) version.o
	$(LD) $(LDFLAGS) $(ROM_LDFLAGS) -e $(ROM_ENTRY) $(LD_HIGH_FLAGS) \
	    -o $@ romInit.o bootInit_uncmp.o version.o bootConfig.o \
	    $(MACH_DEP) $(LIBS)
	$(ENV_BIN)romsize -b $(ROM_SIZE) $@
	$(LDOUT_CONV) $@
	@ $(RM) version.o

bootrom_res : bootInit_res.o romInit_res.o bootConfig.o \
	    $(MACH_DEP) $(LDDEPS) $(LIBS)
	@ $(RM) $@ $(IMI) $(IBR)
	@ make -f Makefile.$(CPU)$(TOOL) CPU=$(CPU) TOOL=$(TOOL) version.o
	$(LD) $(LDFLAGS) $(ROM_LDFLAGS) -e $(ROM_ENTRY) \
	    $(RES_HIGH_FLAGS) -o $@ romInit_res.o bootInit_res.o \
	    version.o bootConfig.o $(MACH_DEP) $(LIBS)
	$(ENV_BIN)romsize -b $(ROM_SIZE) $@
	$(LDOUT_CONV) $@
	@ $(RM) version.o

bootrom_res_mips : bootInit_res_high.o romInit_res_high.o bootConfig.o \
	    $(MACH_DEP) $(LDDEPS) $(LIBS)
	@ $(RM) $@ $(IMI) $(IBR)
	@ $(MAKE) -f Makefile.$(CPU)$(TOOL) CPU=$(CPU) TOOL=$(TOOL) version.o
	$(LD) $(LDFLAGS) $(ROM_LDFLAGS) -e $(ROM_ENTRY) \
	    $(RES_HIGH_FLAGS) -o $@ romInit_res_high.o \
	    bootInit_res_high.o version.o bootConfig.o $(MACH_DEP) $(LIBS)
	$(ENV_BIN)romsize -b $(ROM_SIZE) $@
	$(LDOUT_CONV) $@
	@ $(RM) version.o

bootrom.hex : bootrom $(IMI)
	@ $(RM) $@
	$(BINHEX) $(HEX_FLAGS) $(SECT_SPEC)bootrom$(TXT_OFFSET) \
		$(IMI_SPEC)$(IMI)$(IMI_OFFSET) > $@$(MAP_EXT)
	-@ $(MV_BIN)

imi :	$(IBR)
	$(LD) -o $@ -Ttext $(IMI_TEXT_ADRS) -Tdata $(IMI_DATA_ADRS) $(IBR)

bootrom_uncmp.hex : bootrom_uncmp $(IMI)
	@ $(RM) $@
	$(BINHEX) $(HEX_FLAGS) $(SECT_SPEC)bootrom_uncmp$(TXT_OFFSET) \
		$(IMI_SPEC)$(IMI)$(IMI_OFFSET) > $@$(MAP_EXT)
	-@ $(MV_BIN)

bootrom_res.hex : bootrom_res $(IMI)
	@ $(RM) $@
	$(BINHEX) $(HEX_FLAGS) bootrom_res$(TXT_OFFSET) \
		$(IMI_SPEC)$(IMI)$(IMI_OFFSET) > $@$(MAP_EXT)
	-@ $(MV_BIN)

bootrom_res_mips.hex : bootrom_res_mips $(IMI)
	@ $(RM) $@
	$(BINHEX) $(HEX_FLAGS) bootrom_res_mips$(TXT_OFFSET) \
		$(IMI_SPEC)$(IMI)$(IMI_OFFSET) > $@$(MAP_EXT)
	-@ $(MV_BIN)

release: 
	$(MAKE) -f Makefile.$(CPU)$(TOOL) CPU=$(CPU) TOOL=$(TOOL) $(RELEASE)

save:
	@- mkdir obj$(TOOL)
	@ $(RM) obj$(TOOL)/*
	mv -f *.o vxWorks* bootrom* symTbl.c obj$(TOOL)

_save:
	@ echo "save does not work yet"

restore:
	@ if [ ! -d obj$(TOOL) ]; then  echo "No save area .."; \
	else $(CP) obj$(TOOL)/* .;fi

depend.$(CPU)$(TOOL):
	$(VX_HSP_BASE)/bin/$(VX_HOST_TYPE)/mdepend \
	-f Makefile.$(CPU)$(TOOL).tmp  -o Makefile.$(CPU)$(TOOL) \
	$(CC_INCLUDE) $(CC_DEFINES) -- -- -- $(MACH_DEP) $(CONFIG_ALL)usrConfig.o $(CONFIG_ALL)bootConfig.o $(CONFIG_ALL)bootInit.o romInit.o

# end of makeTarget2


# end of makeTarget

subdirs:
man::
	$(VX_HSP_BASE)/bin/$(VX_HOST_TYPE)/mg $(DOC_FILES)

lib:
sysLib.o : sysLib.c $(VX_VW_BASE)/h/copyright_wrs.h \
  $(VX_VW_BASE)/h/vxWorks.h $(VX_VW_BASE)/h/types/vxCpu.h \
  $(VX_VW_BASE)/h/types/vxArch.h \
  $(VX_VW_BASE)/h/arch/mc68k/archMc68k.h \
  $(VX_VW_BASE)/h/types/vxParams.h \
  $(VX_VW_BASE)/h/types/vxTypesBase.h \
  $(VX_VW_BASE)/h/types/vxTypes.h $(VX_VW_BASE)/h/types/vxANSI.h \
  $(VX_VW_BASE)/h/types/vxTypesOld.h $(VX_VW_BASE)/h/sys/types.h \
  $(VX_VW_BASE)/h/vme.h $(VX_VW_BASE)/h/memLib.h \
  $(VX_VW_BASE)/h/vwModNum.h $(VX_VW_BASE)/h/cacheLib.h \
  $(VX_VW_BASE)/h/limits.h \
  $(VX_VW_BASE)/h/arch/mc68k/cacheMc68kLib.h \
  $(VX_VW_BASE)/h/sysLib.h $(VX_VW_BASE)/h/bootLib.h config.h \
  $(VX_VW_BASE)/config/all//configAll.h $(VX_VW_BASE)/h/smLib.h \
  $(VX_VW_BASE)/h/iv.h $(VX_VW_BASE)/h/arch/mc68k/ivMc68k.h mv167.h \
  $(VX_VW_BASE)/h/drv/serial/cd2400.h $(VX_VW_BASE)/h/tyLib.h \
  $(VX_VW_BASE)/h/iosLib.h $(VX_VW_BASE)/h/ioLib.h \
  $(VX_VW_BASE)/h/net/uio.h $(VX_VW_BASE)/h/fcntl.h \
  $(VX_VW_BASE)/h/sys/fcntlcom.h $(VX_VW_BASE)/h/unistd.h \
  $(VX_VW_BASE)/h/dllLib.h $(VX_VW_BASE)/h/rngLib.h \
  $(VX_VW_BASE)/h/selectLib.h $(VX_VW_BASE)/h/lstLib.h \
  $(VX_VW_BASE)/h/sys/times.h $(VX_VW_BASE)/h/private/semLibP.h \
  $(VX_VW_BASE)/h/semLib.h $(VX_VW_BASE)/h/qLib.h \
  $(VX_VW_BASE)/h/qClass.h $(VX_VW_BASE)/h/private/classLibP.h \
  $(VX_VW_BASE)/h/classLib.h $(VX_VW_BASE)/h/objLib.h \
  $(VX_VW_BASE)/h/errno.h $(VX_VW_BASE)/h/private/objLibP.h \
  $(VX_VW_BASE)/h/drv/multi/pccchip2.h \
  $(VX_VW_BASE)/h/drv/multi/memc040.h \
  $(VX_VW_BASE)/h/drv/multi/m68230.h \
  $(VX_VW_BASE)/h/drv/vme/vmechip2.h \
  $(VX_VW_BASE)/h/drv/vme/vsbchip2.h \
  $(VX_VW_BASE)/h/drv/timer/timerDev.h \
  $(VX_VW_BASE)/h/drv/mem/memDev.h \
  $(VX_VW_BASE)/h/drv/mem/flash28.h \
  $(VX_VW_BASE)/h/drv/scsi/ncr710.h $(VX_VW_BASE)/h/scsiLib.h \
  $(VX_VW_BASE)/h/scsi1Lib.h $(VX_VW_BASE)/h/blkIo.h \
  $(VX_VW_BASE)/h/drv/scsi/ncr710Script.h $(VX_VW_BASE)/h/string.h \
  $(VX_VW_BASE)/h/intLib.h $(VX_VW_BASE)/h/logLib.h \
  $(VX_VW_BASE)/h/taskLib.h $(VX_VW_BASE)/h/regs.h \
  $(VX_VW_BASE)/h/arch/mc68k/regsMc68k.h $(VX_VW_BASE)/h/excLib.h \
  $(VX_VW_BASE)/h/arch/mc68k/excMc68kLib.h \
  $(VX_VW_BASE)/h/private/eventP.h \
  $(VX_VW_BASE)/h/private/funcBindP.h $(VX_VW_BASE)/h/stdlib.h \
  $(VX_VW_BASE)/h/vxLib.h $(VX_VW_BASE)/h/arch/mc68k/vx68kLib.h \
  $(VX_VW_BASE)/h/bspVersion.h $(VX_VW_BASE)/h/private/vmLibP.h \
  $(VX_VW_BASE)/h/vmLib.h $(VX_VW_BASE)/h/mmuLib.h \
  $(VX_VW_BASE)/src/drv//timer/pcc2Timer.c \
  $(VX_VW_BASE)/src/drv//vme/pcc2Vme.c \
  $(VX_VW_BASE)/src/drv//mem/nvRam.c 
tyCoDrv.o : tyCoDrv.c $(VX_VW_BASE)/h/copyright_wrs.h \
  $(VX_VW_BASE)/src/drv//serial/cd2400Serial.c \
  $(VX_VW_BASE)/h/vxWorks.h $(VX_VW_BASE)/h/types/vxCpu.h \
  $(VX_VW_BASE)/h/types/vxArch.h \
  $(VX_VW_BASE)/h/arch/mc68k/archMc68k.h \
  $(VX_VW_BASE)/h/types/vxParams.h \
  $(VX_VW_BASE)/h/types/vxTypesBase.h \
  $(VX_VW_BASE)/h/types/vxTypes.h $(VX_VW_BASE)/h/types/vxANSI.h \
  $(VX_VW_BASE)/h/types/vxTypesOld.h $(VX_VW_BASE)/h/sys/types.h \
  $(VX_VW_BASE)/h/iv.h $(VX_VW_BASE)/h/arch/mc68k/ivMc68k.h \
  $(VX_VW_BASE)/h/ioLib.h $(VX_VW_BASE)/h/vwModNum.h \
  $(VX_VW_BASE)/h/limits.h $(VX_VW_BASE)/h/net/uio.h \
  $(VX_VW_BASE)/h/fcntl.h $(VX_VW_BASE)/h/sys/fcntlcom.h \
  $(VX_VW_BASE)/h/unistd.h $(VX_VW_BASE)/h/iosLib.h \
  $(VX_VW_BASE)/h/dllLib.h $(VX_VW_BASE)/h/tyLib.h \
  $(VX_VW_BASE)/h/rngLib.h $(VX_VW_BASE)/h/selectLib.h \
  $(VX_VW_BASE)/h/lstLib.h $(VX_VW_BASE)/h/sys/times.h \
  $(VX_VW_BASE)/h/private/semLibP.h $(VX_VW_BASE)/h/semLib.h \
  $(VX_VW_BASE)/h/qLib.h $(VX_VW_BASE)/h/qClass.h \
  $(VX_VW_BASE)/h/private/classLibP.h $(VX_VW_BASE)/h/memLib.h \
  $(VX_VW_BASE)/h/classLib.h $(VX_VW_BASE)/h/objLib.h \
  $(VX_VW_BASE)/h/errno.h $(VX_VW_BASE)/h/private/objLibP.h \
  $(VX_VW_BASE)/h/intLib.h $(VX_VW_BASE)/h/errnoLib.h \
  $(VX_VW_BASE)/h/drv/serial/cd2400.h 
usrConfig.o : $(VX_VW_BASE)/config/all/usrConfig.c \
  $(VX_VW_BASE)/h/copyright_wrs.h $(VX_VW_BASE)/h/vxWorks.h \
  $(VX_VW_BASE)/h/types/vxCpu.h $(VX_VW_BASE)/h/types/vxArch.h \
  $(VX_VW_BASE)/h/arch/mc68k/archMc68k.h \
  $(VX_VW_BASE)/h/types/vxParams.h \
  $(VX_VW_BASE)/h/types/vxTypesBase.h \
  $(VX_VW_BASE)/h/types/vxTypes.h $(VX_VW_BASE)/h/types/vxANSI.h \
  $(VX_VW_BASE)/h/types/vxTypesOld.h $(VX_VW_BASE)/h/sys/types.h \
  ./config.h $(VX_VW_BASE)/config/all//configAll.h \
  $(VX_VW_BASE)/h/smLib.h $(VX_VW_BASE)/h/vwModNum.h \
  $(VX_VW_BASE)/h/vme.h $(VX_VW_BASE)/h/iv.h \
  $(VX_VW_BASE)/h/arch/mc68k/ivMc68k.h ./mv167.h \
  $(VX_VW_BASE)/h/drv/serial/cd2400.h $(VX_VW_BASE)/h/tyLib.h \
  $(VX_VW_BASE)/h/iosLib.h $(VX_VW_BASE)/h/ioLib.h \
  $(VX_VW_BASE)/h/limits.h $(VX_VW_BASE)/h/net/uio.h \
  $(VX_VW_BASE)/h/fcntl.h $(VX_VW_BASE)/h/sys/fcntlcom.h \
  $(VX_VW_BASE)/h/unistd.h $(VX_VW_BASE)/h/dllLib.h \
  $(VX_VW_BASE)/h/rngLib.h $(VX_VW_BASE)/h/selectLib.h \
  $(VX_VW_BASE)/h/lstLib.h $(VX_VW_BASE)/h/sys/times.h \
  $(VX_VW_BASE)/h/private/semLibP.h $(VX_VW_BASE)/h/semLib.h \
  $(VX_VW_BASE)/h/qLib.h $(VX_VW_BASE)/h/qClass.h \
  $(VX_VW_BASE)/h/private/classLibP.h $(VX_VW_BASE)/h/memLib.h \
  $(VX_VW_BASE)/h/classLib.h $(VX_VW_BASE)/h/objLib.h \
  $(VX_VW_BASE)/h/errno.h $(VX_VW_BASE)/h/private/objLibP.h \
  $(VX_VW_BASE)/h/drv/multi/pccchip2.h \
  $(VX_VW_BASE)/h/drv/multi/memc040.h \
  $(VX_VW_BASE)/h/drv/multi/m68230.h \
  $(VX_VW_BASE)/h/drv/vme/vmechip2.h \
  $(VX_VW_BASE)/h/drv/vme/vsbchip2.h \
  $(VX_VW_BASE)/h/drv/timer/timerDev.h \
  $(VX_VW_BASE)/h/drv/mem/memDev.h \
  $(VX_VW_BASE)/h/drv/mem/flash28.h \
  $(VX_VW_BASE)/h/drv/scsi/ncr710.h $(VX_VW_BASE)/h/scsiLib.h \
  $(VX_VW_BASE)/h/scsi1Lib.h $(VX_VW_BASE)/h/blkIo.h \
  $(VX_VW_BASE)/h/drv/scsi/ncr710Script.h \
  $(VX_VW_BASE)/h/usrConfig.h $(VX_VW_BASE)/h/bootLib.h \
  $(VX_VW_BASE)/h/bspVersion.h $(VX_VW_BASE)/h/cacheLib.h \
  $(VX_VW_BASE)/h/arch/mc68k/cacheMc68kLib.h \
  $(VX_VW_BASE)/h/ctype.h $(VX_VW_BASE)/h/dbgLib.h \
  $(VX_VW_BASE)/h/regs.h $(VX_VW_BASE)/h/arch/mc68k/regsMc68k.h \
  $(VX_VW_BASE)/h/esf.h $(VX_VW_BASE)/h/arch/mc68k/esfMc68k.h \
  $(VX_VW_BASE)/h/arch/mc68k/dbgMc68kLib.h $(VX_VW_BASE)/h/reg.h \
  $(VX_VW_BASE)/h/dosFsLib.h $(VX_VW_BASE)/h/hashLib.h \
  $(VX_VW_BASE)/h/sllLib.h $(VX_VW_BASE)/h/envLib.h \
  $(VX_VW_BASE)/h/taskLib.h $(VX_VW_BASE)/h/excLib.h \
  $(VX_VW_BASE)/h/arch/mc68k/excMc68kLib.h \
  $(VX_VW_BASE)/h/private/eventP.h \
  $(VX_VW_BASE)/h/private/funcBindP.h $(VX_VW_BASE)/h/stdlib.h \
  $(VX_VW_BASE)/h/fioLib.h $(VX_VW_BASE)/h/stdarg.h \
  $(VX_VW_BASE)/h/fppLib.h $(VX_VW_BASE)/h/arch/mc68k/fppMc68kLib.h \
  $(VX_VW_BASE)/h/ftpLib.h $(VX_VW_BASE)/h/ftpdLib.h \
  $(VX_VW_BASE)/h/hostLib.h $(VX_VW_BASE)/h/netinet/in.h \
  $(VX_VW_BASE)/h/ifLib.h $(VX_VW_BASE)/h/if_bp.h \
  $(VX_VW_BASE)/h/if_sl.h $(VX_VW_BASE)/h/inetLib.h \
  $(VX_VW_BASE)/h/arpa/inet.h $(VX_VW_BASE)/h/intLib.h \
  $(VX_VW_BASE)/h/kernelLib.h $(VX_VW_BASE)/h/loadLib.h \
  $(VX_VW_BASE)/h/symLib.h $(VX_VW_BASE)/h/symbol.h \
  $(VX_VW_BASE)/h/moduleLib.h $(VX_VW_BASE)/h/logLib.h \
  $(VX_VW_BASE)/h/loginLib.h $(VX_VW_BASE)/h/math.h \
  $(VX_VW_BASE)/h/mmuLib.h $(VX_VW_BASE)/h/msgQLib.h \
  $(VX_VW_BASE)/h/netDrv.h $(VX_VW_BASE)/h/netLib.h \
  $(VX_VW_BASE)/h/netShow.h $(VX_VW_BASE)/h/xdr_nfs.h \
  $(VX_VW_BASE)/h/rpc/rpctypes.h $(VX_VW_BASE)/h/nfsDrv.h \
  $(VX_VW_BASE)/h/nfsLib.h $(VX_VW_BASE)/h/dirent.h \
  $(VX_VW_BASE)/h/sys/stat.h $(VX_VW_BASE)/h/xdr_nfsserv.h \
  $(VX_VW_BASE)/h/pipeDrv.h $(VX_VW_BASE)/h/proxyArpLib.h \
  $(VX_VW_BASE)/h/qPriBMapLib.h $(VX_VW_BASE)/h/qPriNode.h \
  $(VX_VW_BASE)/h/ramDrv.h $(VX_VW_BASE)/h/rawFsLib.h \
  $(VX_VW_BASE)/h/rebootLib.h $(VX_VW_BASE)/h/remLib.h \
  $(VX_VW_BASE)/h/rlogLib.h $(VX_VW_BASE)/h/routeLib.h \
  $(VX_VW_BASE)/h/rpcLib.h $(VX_VW_BASE)/h/rpc/clnt.h \
  $(VX_VW_BASE)/h/rpc/xdr.h $(VX_VW_BASE)/h/rpc/auth.h \
  $(VX_VW_BASE)/h/rt11FsLib.h $(VX_VW_BASE)/h/shellLib.h \
  $(VX_VW_BASE)/h/smObjLib.h $(VX_VW_BASE)/h/smDllLib.h \
  $(VX_VW_BASE)/h/private/smFixBlkLibP.h \
  $(VX_VW_BASE)/h/private/smMemLibP.h $(VX_VW_BASE)/h/smMemLib.h \
  $(VX_VW_BASE)/h/private/semSmLibP.h $(VX_VW_BASE)/h/semSmLib.h \
  $(VX_VW_BASE)/h/private/smNameLibP.h $(VX_VW_BASE)/h/smNameLib.h \
  $(VX_VW_BASE)/h/spyLib.h $(VX_VW_BASE)/h/stdio.h \
  $(VX_VW_BASE)/h/string.h $(VX_VW_BASE)/h/sysLib.h \
  $(VX_VW_BASE)/h/sysSymTbl.h $(VX_VW_BASE)/h/taskHookLib.h \
  $(VX_VW_BASE)/h/taskVarLib.h $(VX_VW_BASE)/h/telnetLib.h \
  $(VX_VW_BASE)/h/tftpLib.h $(VX_VW_BASE)/h/tftpdLib.h \
  $(VX_VW_BASE)/h/tickLib.h $(VX_VW_BASE)/h/time.h \
  $(VX_VW_BASE)/h/sigevent.h $(VX_VW_BASE)/h/timers.h \
  $(VX_VW_BASE)/h/timexLib.h $(VX_VW_BASE)/h/unldLib.h \
  $(VX_VW_BASE)/h/usrLib.h $(VX_VW_BASE)/h/version.h \
  $(VX_VW_BASE)/h/vxLib.h $(VX_VW_BASE)/h/arch/mc68k/vx68kLib.h \
  $(VX_VW_BASE)/h/wdLib.h $(VX_VW_BASE)/h/net/mbuf.h \
  $(VX_VW_BASE)/h/net/unixLib.h \
  $(VX_VW_BASE)/h/drv/netif/smNetLib.h $(VX_VW_BASE)/h/net/if.h \
  $(VX_VW_BASE)/h/sys/socket.h $(VX_VW_BASE)/h/net/if_arp.h \
  $(VX_VW_BASE)/h/netinet/if_ether.h \
  $(VX_VW_BASE)/h/drv/netif/if_sm.h $(VX_VW_BASE)/h/smPktLib.h \
  $(VX_VW_BASE)/h/ioctl.h $(VX_VW_BASE)/h/sys/ioctl.h \
  $(VX_VW_BASE)/h/etherLib.h $(VX_VW_BASE)/h/net/if_subr.h \
  $(VX_VW_BASE)/h/rpc/rpcGbl.h $(VX_VW_BASE)/h/rpc/svc.h \
  $(VX_VW_BASE)/h/private/cplusLibP.h \
  $(VX_VW_BASE)/h/private/ftpLibP.h \
  $(VX_VW_BASE)/h/private/kernelLibP.h \
  $(VX_VW_BASE)/h/private/sigLibP.h $(VX_VW_BASE)/h/signal.h \
  $(VX_VW_BASE)/h/private/vmLibP.h $(VX_VW_BASE)/h/vmLib.h \
  $(VX_VW_BASE)/h/private/workQLibP.h $(VX_VW_BASE)/h/aio.h \
  $(VX_VW_BASE)/h/private/aioPxLibP.h \
  $(VX_VW_BASE)/h/private/iosLibP.h $(VX_VW_BASE)/h/errnoLib.h \
  $(VX_VW_BASE)/h/sigLib.h $(VX_VW_BASE)/h/sigCodes.h \
  $(VX_VW_BASE)/h/arch/mc68k/sigMc68kCodes.h \
  $(VX_VW_BASE)/h/ioQLib.h $(VX_VW_BASE)/h/private/mutexPxLibP.h \
  $(VX_VW_BASE)/h/stddef.h $(VX_VW_BASE)/h/aioSysDrv.h \
  $(VX_VW_BASE)/h/private/mqPxLibP.h $(VX_VW_BASE)/h/mqueue.h \
  $(VX_VW_BASE)/h/mqPxShow.h $(VX_VW_BASE)/h/sched.h \
  $(VX_VW_BASE)/h/private/semPxLibP.h $(VX_VW_BASE)/h/semPxShow.h \
  $(VX_VW_BASE)/h/semaphore.h $(VX_VW_BASE)/h/sys/mman.h \
  $(VX_VW_BASE)/h/loadAoutLib.h \
  $(VX_VW_BASE)/src/config/usrDepend.c \
  $(VX_VW_BASE)/src/config/usrKernel.c \
  $(VX_VW_BASE)/src/config/usrExtra.c \
  $(VX_VW_BASE)/src/config/../../src/config/assertInit.c \
  $(VX_VW_BASE)/h/assert.h \
  $(VX_VW_BASE)/src/config/../../src/config/ctypeInit.c \
  $(VX_VW_BASE)/src/config/../../src/config/localeInit.c \
  $(VX_VW_BASE)/h/locale.h \
  $(VX_VW_BASE)/src/config/../../src/config/mathInit.c \
  $(VX_VW_BASE)/src/config/../../src/config/stdioInit.c \
  $(VX_VW_BASE)/src/config/../../src/config/stdlibInit.c \
  $(VX_VW_BASE)/src/config/../../src/config/stringInit.c \
  $(VX_VW_BASE)/src/config/../../src/config/timeInit.c \
  $(VX_VW_BASE)/src/config/../../src/config/usrLoadSym.c \
  $(VX_VW_BASE)/src/config/../../src/config/usrMmuInit.c \
  $(VX_VW_BASE)/src/config/../../src/config/usrNetwork.c \
  $(VX_VW_BASE)/h/rdbLib.h $(VX_VW_BASE)/h/zbufSockLib.h \
  $(VX_VW_BASE)/h/zbufLib.h $(VX_VW_BASE)/h/pingLib.h \
  $(VX_VW_BASE)/h/m2Lib.h \
  $(VX_VW_BASE)/src/config/../../src/config/usrScript.c 
bootConfig.o : $(VX_VW_BASE)/config/all/bootConfig.c \
  $(VX_VW_BASE)/h/copyright_wrs.h $(VX_VW_BASE)/h/vxWorks.h \
  $(VX_VW_BASE)/h/types/vxCpu.h $(VX_VW_BASE)/h/types/vxArch.h \
  $(VX_VW_BASE)/h/arch/mc68k/archMc68k.h \
  $(VX_VW_BASE)/h/types/vxParams.h \
  $(VX_VW_BASE)/h/types/vxTypesBase.h \
  $(VX_VW_BASE)/h/types/vxTypes.h $(VX_VW_BASE)/h/types/vxANSI.h \
  $(VX_VW_BASE)/h/types/vxTypesOld.h $(VX_VW_BASE)/h/sys/types.h \
  $(VX_VW_BASE)/h/bootEcoffLib.h $(VX_VW_BASE)/h/bootLib.h \
  $(VX_VW_BASE)/h/bootLoadLib.h $(VX_VW_BASE)/h/vwModNum.h \
  $(VX_VW_BASE)/h/symLib.h $(VX_VW_BASE)/h/symbol.h \
  $(VX_VW_BASE)/h/sllLib.h $(VX_VW_BASE)/h/classLib.h \
  $(VX_VW_BASE)/h/objLib.h $(VX_VW_BASE)/h/errno.h \
  $(VX_VW_BASE)/h/memLib.h $(VX_VW_BASE)/h/hashLib.h \
  $(VX_VW_BASE)/h/private/objLibP.h \
  $(VX_VW_BASE)/h/private/semLibP.h $(VX_VW_BASE)/h/semLib.h \
  $(VX_VW_BASE)/h/qLib.h $(VX_VW_BASE)/h/qClass.h \
  $(VX_VW_BASE)/h/private/classLibP.h $(VX_VW_BASE)/h/bootpLib.h \
  $(VX_VW_BASE)/h/netinet/in.h $(VX_VW_BASE)/h/net/if.h \
  $(VX_VW_BASE)/h/sys/socket.h $(VX_VW_BASE)/h/net/if_arp.h \
  $(VX_VW_BASE)/h/ifLib.h $(VX_VW_BASE)/h/netinet/in_systm.h \
  $(VX_VW_BASE)/h/netinet/ip.h $(VX_VW_BASE)/h/bspVersion.h \
  $(VX_VW_BASE)/h/cacheLib.h $(VX_VW_BASE)/h/limits.h \
  $(VX_VW_BASE)/h/arch/mc68k/cacheMc68kLib.h \
  $(VX_VW_BASE)/h/ctype.h $(VX_VW_BASE)/h/dosFsLib.h \
  $(VX_VW_BASE)/h/iosLib.h $(VX_VW_BASE)/h/ioLib.h \
  $(VX_VW_BASE)/h/net/uio.h $(VX_VW_BASE)/h/fcntl.h \
  $(VX_VW_BASE)/h/sys/fcntlcom.h $(VX_VW_BASE)/h/unistd.h \
  $(VX_VW_BASE)/h/dllLib.h $(VX_VW_BASE)/h/lstLib.h \
  $(VX_VW_BASE)/h/blkIo.h $(VX_VW_BASE)/h/errnoLib.h \
  $(VX_VW_BASE)/h/fioLib.h $(VX_VW_BASE)/h/stdarg.h \
  $(VX_VW_BASE)/h/ftpLib.h $(VX_VW_BASE)/h/hostLib.h \
  $(VX_VW_BASE)/h/icmpLib.h $(VX_VW_BASE)/h/if_bp.h \
  $(VX_VW_BASE)/h/if_sl.h $(VX_VW_BASE)/h/inetLib.h \
  $(VX_VW_BASE)/h/arpa/inet.h $(VX_VW_BASE)/h/intLib.h \
  $(VX_VW_BASE)/h/loadAoutLib.h $(VX_VW_BASE)/h/loadCoffLib.h \
  $(VX_VW_BASE)/h/moduleLib.h $(VX_VW_BASE)/h/loadLib.h \
  $(VX_VW_BASE)/h/logLib.h $(VX_VW_BASE)/h/msgQLib.h \
  $(VX_VW_BASE)/h/netLib.h $(VX_VW_BASE)/h/pipeDrv.h \
  $(VX_VW_BASE)/h/proxyLib.h $(VX_VW_BASE)/h/qPriBMapLib.h \
  $(VX_VW_BASE)/h/qPriNode.h $(VX_VW_BASE)/h/rebootLib.h \
  $(VX_VW_BASE)/h/remLib.h $(VX_VW_BASE)/h/routeLib.h \
  $(VX_VW_BASE)/h/scsiLib.h $(VX_VW_BASE)/h/scsi1Lib.h \
  $(VX_VW_BASE)/h/stdio.h $(VX_VW_BASE)/h/string.h \
  $(VX_VW_BASE)/h/sysLib.h $(VX_VW_BASE)/h/sysSymTbl.h \
  $(VX_VW_BASE)/h/taskHookLib.h $(VX_VW_BASE)/h/taskLib.h \
  $(VX_VW_BASE)/h/regs.h $(VX_VW_BASE)/h/arch/mc68k/regsMc68k.h \
  $(VX_VW_BASE)/h/excLib.h $(VX_VW_BASE)/h/arch/mc68k/excMc68kLib.h \
  $(VX_VW_BASE)/h/private/eventP.h \
  $(VX_VW_BASE)/h/private/funcBindP.h $(VX_VW_BASE)/h/stdlib.h \
  $(VX_VW_BASE)/h/tftpLib.h $(VX_VW_BASE)/h/tickLib.h \
  $(VX_VW_BASE)/h/trcLib.h $(VX_VW_BASE)/h/version.h \
  $(VX_VW_BASE)/h/wdLib.h $(VX_VW_BASE)/h/net/mbuf.h \
  $(VX_VW_BASE)/h/net/unixLib.h $(VX_VW_BASE)/h/netinet/if_ether.h \
  $(VX_VW_BASE)/h/drv/netif/smNetLib.h \
  $(VX_VW_BASE)/h/drv/netif/if_sm.h $(VX_VW_BASE)/h/smPktLib.h \
  $(VX_VW_BASE)/h/smLib.h $(VX_VW_BASE)/h/ioctl.h \
  $(VX_VW_BASE)/h/sys/ioctl.h $(VX_VW_BASE)/h/etherLib.h \
  $(VX_VW_BASE)/h/net/if_subr.h \
  $(VX_VW_BASE)/h/private/kernelLibP.h $(VX_VW_BASE)/h/kernelLib.h \
  $(VX_VW_BASE)/h/private/workQLibP.h ./config.h \
  $(VX_VW_BASE)/config/all//configAll.h $(VX_VW_BASE)/h/vme.h \
  $(VX_VW_BASE)/h/iv.h $(VX_VW_BASE)/h/arch/mc68k/ivMc68k.h \
  ./mv167.h $(VX_VW_BASE)/h/drv/serial/cd2400.h \
  $(VX_VW_BASE)/h/tyLib.h $(VX_VW_BASE)/h/rngLib.h \
  $(VX_VW_BASE)/h/selectLib.h $(VX_VW_BASE)/h/sys/times.h \
  $(VX_VW_BASE)/h/drv/multi/pccchip2.h \
  $(VX_VW_BASE)/h/drv/multi/memc040.h \
  $(VX_VW_BASE)/h/drv/multi/m68230.h \
  $(VX_VW_BASE)/h/drv/vme/vmechip2.h \
  $(VX_VW_BASE)/h/drv/vme/vsbchip2.h \
  $(VX_VW_BASE)/h/drv/timer/timerDev.h \
  $(VX_VW_BASE)/h/drv/mem/memDev.h \
  $(VX_VW_BASE)/h/drv/mem/flash28.h \
  $(VX_VW_BASE)/h/drv/scsi/ncr710.h \
  $(VX_VW_BASE)/h/drv/scsi/ncr710Script.h \
  $(VX_VW_BASE)/src/config/usrKernel.c 
bootInit.o : $(VX_VW_BASE)/config/all/bootInit.c \
  $(VX_VW_BASE)/h/copyright_wrs.h $(VX_VW_BASE)/h/vxWorks.h \
  $(VX_VW_BASE)/h/types/vxCpu.h $(VX_VW_BASE)/h/types/vxArch.h \
  $(VX_VW_BASE)/h/arch/mc68k/archMc68k.h \
  $(VX_VW_BASE)/h/types/vxParams.h \
  $(VX_VW_BASE)/h/types/vxTypesBase.h \
  $(VX_VW_BASE)/h/types/vxTypes.h $(VX_VW_BASE)/h/types/vxANSI.h \
  $(VX_VW_BASE)/h/types/vxTypesOld.h $(VX_VW_BASE)/h/sys/types.h \
  $(VX_VW_BASE)/h/sysLib.h $(VX_VW_BASE)/h/bootLib.h ./config.h \
  $(VX_VW_BASE)/config/all//configAll.h $(VX_VW_BASE)/h/smLib.h \
  $(VX_VW_BASE)/h/vwModNum.h $(VX_VW_BASE)/h/vme.h \
  $(VX_VW_BASE)/h/iv.h $(VX_VW_BASE)/h/arch/mc68k/ivMc68k.h \
  ./mv167.h $(VX_VW_BASE)/h/drv/serial/cd2400.h \
  $(VX_VW_BASE)/h/tyLib.h $(VX_VW_BASE)/h/iosLib.h \
  $(VX_VW_BASE)/h/ioLib.h $(VX_VW_BASE)/h/limits.h \
  $(VX_VW_BASE)/h/net/uio.h $(VX_VW_BASE)/h/fcntl.h \
  $(VX_VW_BASE)/h/sys/fcntlcom.h $(VX_VW_BASE)/h/unistd.h \
  $(VX_VW_BASE)/h/dllLib.h $(VX_VW_BASE)/h/rngLib.h \
  $(VX_VW_BASE)/h/selectLib.h $(VX_VW_BASE)/h/lstLib.h \
  $(VX_VW_BASE)/h/sys/times.h $(VX_VW_BASE)/h/private/semLibP.h \
  $(VX_VW_BASE)/h/semLib.h $(VX_VW_BASE)/h/qLib.h \
  $(VX_VW_BASE)/h/qClass.h $(VX_VW_BASE)/h/private/classLibP.h \
  $(VX_VW_BASE)/h/memLib.h $(VX_VW_BASE)/h/classLib.h \
  $(VX_VW_BASE)/h/objLib.h $(VX_VW_BASE)/h/errno.h \
  $(VX_VW_BASE)/h/private/objLibP.h \
  $(VX_VW_BASE)/h/drv/multi/pccchip2.h \
  $(VX_VW_BASE)/h/drv/multi/memc040.h \
  $(VX_VW_BASE)/h/drv/multi/m68230.h \
  $(VX_VW_BASE)/h/drv/vme/vmechip2.h \
  $(VX_VW_BASE)/h/drv/vme/vsbchip2.h \
  $(VX_VW_BASE)/h/drv/timer/timerDev.h \
  $(VX_VW_BASE)/h/drv/mem/memDev.h \
  $(VX_VW_BASE)/h/drv/mem/flash28.h \
  $(VX_VW_BASE)/h/drv/scsi/ncr710.h $(VX_VW_BASE)/h/scsiLib.h \
  $(VX_VW_BASE)/h/scsi1Lib.h $(VX_VW_BASE)/h/blkIo.h \
  $(VX_VW_BASE)/h/drv/scsi/ncr710Script.h 
sysALib.o : sysALib.s $(VX_VW_BASE)/h/vxWorks.h \
  $(VX_VW_BASE)/h/types/vxCpu.h $(VX_VW_BASE)/h/types/vxArch.h \
  $(VX_VW_BASE)/h/arch/mc68k/archMc68k.h $(VX_VW_BASE)/h/sysLib.h \
  $(VX_VW_BASE)/h/asm.h $(VX_VW_BASE)/h/arch/mc68k/asmMc68k.h \
  config.h $(VX_VW_BASE)/config/all//configAll.h \
  $(VX_VW_BASE)/h/smLib.h $(VX_VW_BASE)/h/vwModNum.h \
  $(VX_VW_BASE)/h/vme.h $(VX_VW_BASE)/h/iv.h \
  $(VX_VW_BASE)/h/arch/mc68k/ivMc68k.h mv167.h \
  $(VX_VW_BASE)/h/drv/serial/cd2400.h \
  $(VX_VW_BASE)/h/drv/multi/pccchip2.h \
  $(VX_VW_BASE)/h/drv/multi/memc040.h \
  $(VX_VW_BASE)/h/drv/multi/m68230.h \
  $(VX_VW_BASE)/h/drv/vme/vmechip2.h \
  $(VX_VW_BASE)/h/drv/vme/vsbchip2.h \
  $(VX_VW_BASE)/h/drv/timer/timerDev.h \
  $(VX_VW_BASE)/h/drv/mem/memDev.h \
  $(VX_VW_BASE)/h/drv/mem/flash28.h \
  $(VX_VW_BASE)/h/drv/scsi/ncr710.h 
romInit.o : romInit.s $(VX_VW_BASE)/h/vxWorks.h \
  $(VX_VW_BASE)/h/types/vxCpu.h $(VX_VW_BASE)/h/types/vxArch.h \
  $(VX_VW_BASE)/h/arch/mc68k/archMc68k.h $(VX_VW_BASE)/h/sysLib.h \
  $(VX_VW_BASE)/h/asm.h $(VX_VW_BASE)/h/arch/mc68k/asmMc68k.h \
  config.h $(VX_VW_BASE)/config/all//configAll.h \
  $(VX_VW_BASE)/h/smLib.h $(VX_VW_BASE)/h/vwModNum.h \
  $(VX_VW_BASE)/h/vme.h $(VX_VW_BASE)/h/iv.h \
  $(VX_VW_BASE)/h/arch/mc68k/ivMc68k.h mv167.h \
  $(VX_VW_BASE)/h/drv/serial/cd2400.h \
  $(VX_VW_BASE)/h/drv/multi/pccchip2.h \
  $(VX_VW_BASE)/h/drv/multi/memc040.h \
  $(VX_VW_BASE)/h/drv/multi/m68230.h \
  $(VX_VW_BASE)/h/drv/vme/vmechip2.h \
  $(VX_VW_BASE)/h/drv/vme/vsbchip2.h \
  $(VX_VW_BASE)/h/drv/timer/timerDev.h \
  $(VX_VW_BASE)/h/drv/mem/memDev.h \
  $(VX_VW_BASE)/h/drv/mem/flash28.h \
  $(VX_VW_BASE)/h/drv/scsi/ncr710.h 
