
include Target.include
include .applTop/config/CONFIG

# The resource.def will be placed in the data data directory
DATA	= $(wildcard ../resource.def ../resource.def.flex)

include .applTop/config/RULES.Build
