
include Target.include
include .applTop/config/CONFIG

# The *.vws scripts will be edited and put in the bin/$(T_A) directory
PROD    = $(patsubst ../%.vws, %, $(wildcard ../*.vws)) $(patsubst ../%.VWS, %, $(wildcard ../*.VWS))

TARGETS += Distfile.$(T_A)

include .applTop/config/RULES.Build

../%.vws: ../%.VWS ../subst .applTop/config.par
	../subst < ../$*.VWS > ../$*.vws 
