#! /bin/sh

#
# This script is used by the Makefiles to make the following substitutions
# to a text file:
#
#     @(astlibdir) is replaced by the shell variable ${astlibdir}
#     @(name) is replaced by the shell variable ${name}
#     @(prefix) is replaced by the shell variable ${prefix}
#     @(sadprefix) is replaced by the shell variable ${sadprefix}
#     @(slalibdir) is replaced by the shell variable ${slalibdir}
#     @(timelibdir) is replaced by the shell variable ${timelibdir}
#     @(usevxtime) is replaced by the shell variable ${usevxtime}
#     @(engdir) is replaced by the shell variable ${engdir}
#

. .applTop/config.par

sed \
	-e "s;@(astlibdir);${astlibdir};g" \
	-e "s;@(engdir);${engdir};g" \
	-e "s;@(name);${name};g" \
	-e "s;@(prefix);${prefix};g" \
	-e "s;@(sadprefix);${sadprefix};g" \
	-e "s;@(slalibdir);${slalibdir};g" \
	-e "s;@(timelibdir);${timelibdir};g" \
	-e "s;@(usevxtime);${usevxtime};g"
