#! /bin/sh
#
# Sets up the NIRI LIB EPICS UAE application directory after unpacking.
#
# Invocation:
#   source niriSetup
#
# Steven M Beard, Hubert Yamada
# 17 Mar 1997: CICS version.
# 27 May 1997: NIRI version.
#

#######################################################################
# Start with a few sanity checks.
#######################################################################

#
# Check that the EPICS startup script has been executed.
#

if [ ${EPICS-undefined} = undefined ]; then
	echo "*** EPICS environment variables have not been defined. Please"
	echo "*** source your local EPICS setup script (see \"niriLogin\""
	echo "for an example)."
	exit 1
fi

#
# Check that the local login script has been executed.
#

if [ ${NIRI_LIBDIR-undefined} = undefined ]; then
	echo "*** ERROR: NIRI_LIBDIR environment variable not defined."
	echo "*** Please set up NIRI from the top level 'niriSetup' script."
	exit 1
fi

#######################################################################
# Now set up the application directory.
#######################################################################

cd ${NIRI_LIBDIR}

#
# If this file already exists, then it is not overwritten.  Remove it,
# to be safe.
#

if [ -f config/CONFIG.Defs ]; then
	echo "* Removing old CONFIG.Defs"
	rm -f config/CONFIG.Defs
fi

applSetup -install ${NIRI_LIBDIR} -targets ${NIRI_TARGETS} \
	-subdir_file Makefile.subdirs \
	-I dl -I capfast -I src \
	-depends ${NIRI_ENGDIR} -depends ${NIRI_ASTLIBDIR} \
	-depends ${NIRI_SLALIBDIR} -depends ${NIRI_TIMELIBDIR}

exit $?
