#+
#  Trecs::CC
#
#  Implements the TRECS components controller class. 
#
#  Options:
#
#  Methods:
#          apply args    Applies the configuration to the Acquisition 
#                        camera by setting the values of the command
#                        parameters. Any arguments are ignored.
#
#          init          Returns the object to its initial state.
#
#          save file     Writes the values of the configuration
#                        to the channel identifier "file".
#
#
#  Matthieu Bec - 19 November 2002
#
#+

itcl::class Trecs::CC {
   public {
   }
   public {
      method apply args
      method init
      method save chan
      method configCCaction { action } { set ccaction $action }
      method configCClogcommand { logcommand } { set cclogcommand $logcommand }
   }
   private {
      method log {cs}
      
      variable cclogcommand ""
      variable ccaction
   }
}

itcl::body Trecs::CC::apply args {
   after idle [$ccaction cget -onok]
}

itcl::body Trecs::CC::log {cs} {
   if { ![string is space $cclogcommand] } {
      uplevel #0 $cclogcommand $cs
   }
}
