#+
#  Trecs <- CC, DC
#
#  A Trecs object configures TRECS.
#
#  Options:
#           none in addition to those inherited from DC and CC
#
#  Methods:
#           apply controller    Applies the configuration to the specified
#                               controller (detector or components) or both
#                               controllers.
#
#           init                Sets the object to its initial state.
#
#           save chan           Writes the object definition to the specified
#                               I/O channel.
#
#
#  Matthieu Bec - 19 November 2002
#
#+

itcl::class Trecs::Trecs {
   inherit Trecs::CC Trecs::DC
   public {
      constructor {args} {eval configure $args}
      method apply {{controller ""}}
      method init {}
      method save {chan}
      variable observeType
   }
}

itcl::body Trecs::Trecs::apply {{controller ""}} {
   switch $controller {
      detector {
         Trecs::DC::apply
      }
      components {
         Trecs::CC::apply
      }
      default {
         Trecs::CC::apply
         Trecs::DC::apply
      }
   }
}

itcl::body Trecs::Trecs::init {} {
   Trecs::CC::init
   Trecs::DC::init
}

itcl::body Trecs::Trecs::save {chan} {
   Trecs::CC::save $chan
   Trecs::DC::save $chan
}
