#!/usr/bin/csh -f
#

if ( ${?EPICS} == 0 ) then

   echo "EPICS environment variables have not been defined. Please execute" 
   echo "your local EPICS setup script (see 'niriLogin' for an example)."
   exit
endif

if ( ${?EPICS_DISPLAY_PATH} ) then

    setenv EPICS_DISPLAY_PATH ${NIRI_DIR}/DC/data:${EPICS_DISPLAY_PATH}
    setenv EPICS_DISPLAY_PATH ${NIRI_DIR}/WFS/data:${EPICS_DISPLAY_PATH}
    setenv EPICS_DISPLAY_PATH ${NIRI_DIR}/CC/data:${EPICS_DISPLAY_PATH}
    setenv EPICS_DISPLAY_PATH ${NIRI_DIR}/ENG/data:${EPICS_DISPLAY_PATH}
    setenv EPICS_DISPLAY_PATH ${NIRI_DIR}/LIB/data:${EPICS_DISPLAY_PATH}
    setenv EPICS_DISPLAY_PATH ${NIRI_DIR}/data:${EPICS_DISPLAY_PATH}
    setenv EPICS_DISPLAY_PATH .:${EPICS_DISPLAY_PATH}
else

    setenv EPICS_DISPLAY_PATH ${NIRI_DIR}/DC/data
    setenv EPICS_DISPLAY_PATH ${NIRI_DIR}/CICSWFS/data:${EPICS_DISPLAY_PATH}
    setenv EPICS_DISPLAY_PATH ${NIRI_DIR}/CC/data:${EPICS_DISPLAY_PATH}
    setenv EPICS_DISPLAY_PATH ${NIRI_DIR}/ENG/data:${EPICS_DISPLAY_PATH}
    setenv EPICS_DISPLAY_PATH ${NIRI_DIR}/LIB/data:${EPICS_DISPLAY_PATH}
    setenv EPICS_DISPLAY_PATH ${NIRI_DIR}/data:${EPICS_DISPLAY_PATH}
    setenv EPICS_DISPLAY_PATH .:${EPICS_DISPLAY_PATH}
endif

dm testCarMenu.dl "T=$NIRI_PREFIX,  S=$NIRI_SADPREFIX" &
