#+
#  Michelle::CC
#
#  Implements the MICHELLE components controller class. 
#
#  Options:
#
#  Methods:
#          apply args    Applies the configuration to the Acquisition 
#                        camera by setting the values of the command
#                        parameters. Any arguments are ignored.
#
#          init          Returns the object to its initial state.
#
#          save file     Writes the values of the configuration
#                        to the channel identifier "file".
#
#  D Terrett 24 July 2001
#+

itcl::class Michelle::CC {
   public {
   }
   public {
      method apply args
      method init
      method save chan
      method configCCaction { action } { set ccaction $action }
      method configCClogcommand { logcommand } { set cclogcommand $logcommand }

      variable camera ""
      variable beamSplitter ""
      variable mask ""
      variable filter ""
      variable disperser ""
      variable observeType ""
   }
   private {
      variable cclogcommand ""
      variable ccaction
      method log {cs}
   }
}

itcl::body Michelle::CC::apply args {
   $ccaction unset michelle::config camera
   $ccaction unset michelle::config beamSplitter
   $ccaction unset michelle::config mask
   $ccaction unset michelle::config filter
   $ccaction unset michelle::config disperser
   
	if {![string is space $camera]} {
		$ccaction set michelle::config camera "$camera"
		}

	if {![string is space $beamSplitter]} {
		$ccaction set michelle::config beamSplitter "$beamSplitter"
		}

	if {![string is space $mask]} {
		$ccaction set michelle::config mask "$mask"
		}
   
   if { [string is space $observeType] } {
      # try and get it from the display
      if [info exists dhshdr::obstype] {
         $this configure -observeType $dhshdr::obstype
         }
      }

   if { [string equal $observeType DARK] } {
      $ccaction set michelle::config filter blank
		} \
   elseif {![string is space $filter]} {
		$ccaction set michelle::config filter "$filter"
		}

	if {![string is space $disperser]} {
		$ccaction set michelle::config disperser "$disperser"
		}
      
   $ccaction start
}

itcl::body Michelle::CC::save file {
}

itcl::body Michelle::CC::init {} {
}

itcl::body Michelle::CC::log {cs} {
   if { ![string is space $cclogcommand] } {
      uplevel #0 $cclogcommand $cs
   }
}

#==============================================================================
# camera
#==============================================================================
itcl::configbody Michelle::CC::camera {
   switch $camera {
      "f/6" {
         }
      "f/14" {
         }
      "f/32" {
         }
      "" {
         }
      default {
         error "cannot set camera to $camera"
         }
      }
   }

#==============================================================================
# beamSplitter
#==============================================================================
itcl::configbody Michelle::CC::beamSplitter {
   switch $beamSplitter {
      "default"
         -
      "same-as-camera"
         -
      "same as camera" {
         set beamSplitter "same-as-camera"
         }
      "f/6" {
         }
      "f/14" {
         }
      "f/32" {
         }
      "" {
         }
      default {
         error "cannot set beamSplitter to $beamSplitter"
         }
      }
   }
   
#==============================================================================
# mask
#==============================================================================
itcl::configbody Michelle::CC::mask {
   switch $mask {
      "default"
         -
      "imaging" {
         set mask "imaging"
         }
      "0.226 arcsec center" {
         set mask "0.23'' center"
         }
      "2-pix slit center" {
	      set mask "0.23'' center"
         }
      "0.226 arcsec blue" {
         set mask "0.23'' blue"
         }
      "2-pix slit blue" {
         set mask "0.23'' blue"
         }
      "0.470 arcsec center" {
        set mask "0.46'' center"
          }
      "4-pix slit center" {
        set mask "0.46'' center"
          }
      "0.409 arcsec blue" {
         set mask "0.46'' blue"
         }
      "4-pix slit blue" {
         set mask "0.46'' blue"
         }
      "0.675 arcsec center" {
         set mask "0.70'' center"
         }
      "6-pix slit center" {
         set mask "0.70'' center"
         }
      "0.696 arcsec blue" {
         set mask "0.70'' blue"
         }
      "6-pix slit blue" {
         set mask "0.70'' blue"
         }
      "pinholemask" {
         }
      "polarmask" {
         }
      "polarmask2" {
         }
      "Polarimetry 1-2.5 um" {
         set mask polarmask
         }
      "" {
         }
      default {
         error "cannot set mask to $mask"
         }
      }
   }  
   
#==============================================================================
# filter
#==============================================================================
itcl::configbody Michelle::CC::filter {
   switch $filter {
      "J" {
         }         
      "H" {
         }
      "K(prime)" {
         }
      "K(short)" {
         }
      "K" {
         }
      "L(prime)" {
         }
      "M(prime)" {
         }
      "Pa(beta)" {
         }
      "CH4(short)" {
         }
      "H-continuum(1.57)" {
         set filter "H-continuum"
         }
      "\[FeII]" {
         set filter "FeII"
         }
      "CH4(long)" {
         set filter "CH4(long)"
         }
      "K-continuum(2.09)" {
         set filter "Kcon(209)"
         }
      "H2 1-0 S(1)" {
         set filter "H2 1-0 S1"
         }
      "H2 2-1 S(1)" {
         set filter "H2 2-1 S1"
         }
      "Br(gamma)" {
         }
      "K-continuum(2.27)" {
         set filter "Kcon(227)"
         }
      "CO 2-0 (bh)" {
         set filter "CO 2-0(bh)"
         }
      "Order sorting J" {
         set filter "J order sort"
         }
      "Order sorting H" {
         set filter "H order sort"
         }
      "Order sorting K" {
         set filter "K order sort"
         }
      "Order sorting L" {
         set filter "L order sort"
         }
      "Order sorting M" {
         set filter "M order sort"
         }
      "H2O ice" {
         set filter "H2Oice_G0230"
         }
      "hydrocarbon" {
         set filter "hydrocarb_G0231"
         }
      "blank" {
         set filter "blank"
         }
      "" {
         }
      default {
         error "cannot set filter to $filter"
         }
      }

}
   
#==============================================================================
# disperser
#==============================================================================
itcl::configbody Michelle::CC::disperser {
   switch $disperser {
      "J-grism" {
         }
      "H-grism" {
         }
      "K-grism" {
         }
      "L-grism" {
         }
      "M-grism" {
         }
      "Wollaston" {
         }
      "none" {
         }
      "" {
         }
      default {
         error "cannot set disperser to $disperser"
         }
      }
   }
   
#==============================================================================
# observeType
#==============================================================================
itcl::configbody Michelle::CC::observeType {
   switch $observeType {
      "OBJECT"
         -
      "FLAT"
         -
      "ARC" {
         }
      "DARK" {
         }
      "BIAS" {
         }
	   }
   }   
