#+
#  Michelle::DC
#
#  Implements the Acquisition camera detector controller class. 
#
#  Options:
#
#  Methods:
#          apply args    Applies the configuration to the Acquisition 
#                        camera by setting the values of the command
#                        parameters. Any arguments are ignored.
#
#          init          Returns the object to its initial state.
#
#          save file     Writes the values of the configuration
#                        to the channel identifier "file".
#
#  D Terrett 24 July 2001
#+

itcl::class Michelle::DC {
   public {
      method calcTimeout
   }
   public {
      method apply args
      method init
      method save chan
      method configDCaction { action } { set dcaction $action }
      method configDClogcommand { logcommand } { set dclogcommand $logcommand }
      variable readMode ""
      variable exposureTime ""
      variable coadds ""
      variable builtinROI ""
   }
   private {
      variable dclogcommand ""
      variable dcaction
      method log {cs}
      variable readMode_lnr ""
      variable readMode_davg ""
      variable readMode_bvolt ""
   }
}

itcl::body Michelle::DC::apply args {
   $dcaction unset michelle::dcconfig readMode
   $dcaction unset michelle::dcconfig exposureTime
   $dcaction unset michelle::dcconfig numCoAdds
   $dcaction unset michelle::dcconfig builtinROI

	if {![string is space $readMode_lnr]} {
		$dcaction set michelle::dcconfig readMode_lnr "$readMode_lnr"
		}
	if {![string is space $readMode_davg]} {
		$dcaction set michelle::dcconfig readMode_davg "$readMode_davg"
		}
	if {![string is space $readMode_bvolt]} {
		$dcaction set michelle::dcconfig readMode_bvolt "$readMode_bvolt"
		}

	if {![string is space $exposureTime]} {
		$dcaction set michelle::dcconfig exposureTime "$exposureTime"
		}
   if { ![string is space $coadds] } {
      $dcaction set michelle::dcconfig numCoAdds "$coadds"
      }

	if {![string is space $builtinROI]} {
		$dcaction set michelle::dcconfig builtinROI "$builtinROI"
		}
   #$dcaction set michelle::dcconfig bitsperpix INT32
   $dcaction set michelle::dcconfig numPics 1
   $dcaction set michelle::dcconfig hdrDetail FULL
   $dcaction set michelle::dcconfig hdrTiming BOTH
   $dcaction start
}

itcl::body Michelle::DC::save file {
}

itcl::body Michelle::DC::init {} {
}

itcl::body Michelle::DC::log {cs} {
   if { ![string is space $dclogcommand] } {
      uplevel #0 $dclogcommand $cs
   }
}
#==============================================================================
# calcTimeout
#==============================================================================
itcl::body Michelle::DC::calcTimeout {} {
         set coadds [sa michelle::dcstatus get numCoAdds value]
         set inttime [sa michelle::dcstatus get intTime value]
         set minint [sa michelle::dcstatus get minInt value]
         if { [string is integer -strict $coadds] &&
            [string is double -strict $inttime] &&
            [string is double -strict $minint] } {
         set to [expr { int ( 30.0 + 2.5 * ( $inttime + $minint ) * $coadds )}]
         } else {
         puts "Unable to determine Michelle observe timeout"
         set to 360
         }
      return $to
      }
#==============================================================================
# readMode
#==============================================================================
itcl::configbody Michelle::DC::readMode {
   switch $readMode {
      "1-2.5um narrow-band imaging/spectroscopy" {
         set readMode_lnr 16
         set readMode_davg 16
         set readMode_bvolt 0.6
         }
      "narrow-band imaging/spectroscopy" {
         set readMode_lnr 16
         set readMode_davg 16
         set readMode_bvolt 0.6
         }
      "1-2.5um broad-band imaging" {
         set readMode_lnr 1
         set readMode_davg 16
         set readMode_bvolt 0.6
         }
      "1-2.5 um imaging" {
         set readMode_lnr 1
         set readMode_davg 16
         set readMode_bvolt 0.6
         }
      "fast readout (shallow well)" {
         set readMode_lnr 1
         set readMode_davg 1
         set readMode_bvolt 0.6
         }
      "fast readout" {
         set readMode_lnr 1
         set readMode_davg 1
         set readMode_bvolt 0.6
         }
      "3-5um imaging/spectroscopy (deep well)" {
         set readMode_lnr 1
         set readMode_davg 1
         set readMode_bvolt 0.9
         }
      "3-5um imaging/spectroscopy" {
         set readMode_lnr 1
         set readMode_davg 1
         set readMode_bvolt 0.9
         }
      "med RN (deep)" {
         set readMode_lnr 1
         set readMode_davg 16
         set readMode_bvolt 0.9
         }
      "" {
         }
      default {
         error "cannot set readMode to $readMode"
         }
      }
   }
#==============================================================================
# exposureTime
#==============================================================================
itcl::configbody Michelle::DC::exposureTime {
   # check for double, will truncate to int
   if { ![string is space $exposureTime] && ![ string is double $exposureTime] } {
      error "cannot set exposureTime to $exposureTime"
      }
   }
#==============================================================================
# coadds
#==============================================================================
itcl::configbody Michelle::DC::coadds {
   # check for double, will truncate to int
   if { ![string is space $coadds] && ![ string is double $coadds] } {
      error "cannot set coadds to $coadds"
      }
   }
#==============================================================================
# builtinROI
#==============================================================================
itcl::configbody Michelle::DC::builtinROI {
   switch $builtinROI {
      "Full Frame Readout" {
         set builtinROI 1024
         }
      "full frame readout" {
         set builtinROI 1024
         }
      "Central 768x768" {
         set builtinROI 768
         }
      "Central 512x512" {
         set builtinROI 512
         }
      "Central 256x256" {
         set builtinROI 256
         }
      "Central 128x128" {
         puts "ERROR: ignoring builtinROI Central 128x128 is an OT aberation"
         set builtinROI ""
         }
	   }
   }

      

