#+
#  Michelle <- CC, DC
#
#  A Michelle object configures MICHELLE.
#
#  Options:
#           none in addition to those inherited from DC and CC
#
#  Methods:
#           apply controller    Applies the configuration to the specified
#                               controller (detector or components) or both
#                               controllers.
#
#           init                Sets the object to its initial state.
#
#           save chan           Writes the object definition to the specified
#                               I/O channel.
#
#  D Terrett 24 July 2001
#
#  Copyright CCLRC
#+

itcl::class Michelle::Michelle {
   inherit Michelle::CC Michelle::DC
   public {
      constructor {args} {eval configure $args}
      method apply {{controller ""}}
      method init {}
      method save {chan}
   }
}

itcl::body Michelle::Michelle::apply {{controller ""}} {
   switch $controller {
      detector {
         Michelle::DC::apply
      }
      components {
         Michelle::CC::apply
      }
      default {
         Michelle::CC::apply
         Michelle::DC::apply
      }
   }
}

itcl::body Michelle::Michelle::init {} {
   Michelle::CC::init
   Michelle::DC::init
}

itcl::body Michelle::Michelle::save {chan} {
   Michelle::CC::save $chan
   Michelle::DC::save $chan
}
